### ISSUE TITLE
OSError: [WinError 87] The parameter is incorrect

### ISSUE THREAD

**Issue by CYST084** [KillianLucas/open-interpreter#1040]
### Describe the bug

(interpreter1_env) C:\Users\user\interpreter1>interpreter
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\interpreter1\interpreter1_env\Scripts\interpreter.exe\__main__.py", line 4, in <module>
  File "C:\Users\user\interpreter1\interpreter1_env\Lib\site-packages\interpreter\__init__.py", line 1, in <module>
    from .core.core import OpenInterpreter
  File "C:\Users\user\interpreter1\interpreter1_env\Lib\site-packages\interpreter\core\core.py", line 11, in <module>
    from ..terminal_interface.start_terminal_interface import start_terminal_interface
  File "C:\Users\user\interpreter1\interpreter1_env\Lib\site-packages\interpreter\terminal_interface\start_terminal_inte
rface.py", line 11, in <module>
    from .conversation_navigator import conversation_navigator
  File "C:\Users\user\interpreter1\interpreter1_env\Lib\site-packages\interpreter\terminal_interface\conversation_naviga
tor.py", line 10, in <module>
    import inquirer
  File "C:\Users\user\interpreter1\interpreter1_env\Lib\site-packages\inquirer\__init__.py", line 1, in <module>
    from inquirer.prompt import prompt
  File "C:\Users\user\interpreter1\interpreter1_env\Lib\site-packages\inquirer\prompt.py", line 1, in <module>
    import inquirer.themes as themes
  File "C:\Users\user\interpreter1\interpreter1_env\Lib\site-packages\inquirer\themes.py", line 9, in <module>
    term = Terminal()
           ^^^^^^^^^^
  File "C:\Users\user\interpreter1\interpreter1_env\Lib\site-packages\blessed\terminal.py", line 167, in __init__
    self._kind = kind or curses.get_term(self._init_descriptor)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\interpreter1\interpreter1_env\Lib\site-packages\jinxed\win32.py", line 331, in get_term
    set_console_mode(filehandle, mode | ENABLE_VIRTUAL_TERMINAL_PROCESSING)
  File "C:\Users\user\interpreter1\interpreter1_env\Lib\site-packages\jinxed\win32.py", line 181, in set_console_mode
    return bool(KERNEL32.SetConsoleMode(filehandle, mode))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\interpreter1\interpreter1_env\Lib\site-packages\jinxed\win32.py", line 86, in _check_bool
    raise ctypes.WinError(ctypes.get_last_error())
OSError: [WinError 87] The parameter is incorrect.

(interpreter1_env) C:\Users\user\interpreter1>

### Reproduce

create a new folder, cd to the folder, create a venv
upgrade pip
pip install open-interpreter
After installation is done, run interpreter.
The error below shows:
(interpreter1_env) C:\Users\user\interpreter1>interpreter
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\interpreter1\interpreter1_env\Scripts\interpreter.exe\__main__.py", line 4, in <module>
  File "C:\Users\user\interpreter1\interpreter1_env\Lib\site-packages\interpreter\__init__.py", line 1, in <module>
    from .core.core import OpenInterpreter
  File "C:\Users\user\interpreter1\interpreter1_env\Lib\site-packages\interpreter\core\core.py", line 11, in <module>
    from ..terminal_interface.start_terminal_interface import start_terminal_interface
  File "C:\Users\user\interpreter1\interpreter1_env\Lib\site-packages\interpreter\terminal_interface\start_terminal_inte
rface.py", line 11, in <module>
    from .conversation_navigator import conversation_navigator
  File "C:\Users\user\interpreter1\interpreter1_env\Lib\site-packages\interpreter\terminal_interface\conversation_naviga
tor.py", line 10, in <module>
    import inquirer
  File "C:\Users\user\interpreter1\interpreter1_env\Lib\site-packages\inquirer\__init__.py", line 1, in <module>
    from inquirer.prompt import prompt
  File "C:\Users\user\interpreter1\interpreter1_env\Lib\site-packages\inquirer\prompt.py", line 1, in <module>
    import inquirer.themes as themes
  File "C:\Users\user\interpreter1\interpreter1_env\Lib\site-packages\inquirer\themes.py", line 9, in <module>
    term = Terminal()
           ^^^^^^^^^^
  File "C:\Users\user\interpreter1\interpreter1_env\Lib\site-packages\blessed\terminal.py", line 167, in __init__
    self._kind = kind or curses.get_term(self._init_descriptor)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\interpreter1\interpreter1_env\Lib\site-packages\jinxed\win32.py", line 331, in get_term
    set_console_mode(filehandle, mode | ENABLE_VIRTUAL_TERMINAL_PROCESSING)
  File "C:\Users\user\interpreter1\interpreter1_env\Lib\site-packages\jinxed\win32.py", line 181, in set_console_mode
    return bool(KERNEL32.SetConsoleMode(filehandle, mode))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\interpreter1\interpreter1_env\Lib\site-packages\jinxed\win32.py", line 86, in _check_bool
    raise ctypes.WinError(ctypes.get_last_error())
OSError: [WinError 87] The parameter is incorrect.

(interpreter1_env) C:\Users\user\interpreter1>

### Expected behavior

To run normally as in various tutorials

### Open Interpreter version

0.2..0

### Python version

3.11.1

### Operating System name and version

Windows 10

**Comment by MikeBirdTech** [comment]
Hi @CYST084 
Thanks for raising this and sorry to hear that you're having issues. What terminal are you using? Do any permissions need to be granted?

**Comment by CYST084** [comment]
Oh I sorted the error
It was a problem with python package management
When I purged python from my system and reinstalled it afresh everything
worked perfectly.

**Comment by interpreterwork** [comment]
Thank you for reporting this and for helping build the classic Python version of Open Interpreter. This issue concerns the earlier Python/LiteLLM/Jupyter product; this repository now tracks the Rust Open Interpreter built on Codex. We are closing the legacy report here so current product tracking starts clean. If you still want to pursue it, the community-maintained classic fork is https://github.com/endolith/open-interpreter. If the same problem affects the current Interpreter release, please open a new issue with the current template and include the version, provider, model, wire API, harness, platform, and reproduction.
