### ISSUE TITLE
Google Gemini API Support

### ISSUE THREAD

**Issue by snipeart007** [KillianLucas/open-interpreter#1055]
### Describe the solution you'd like

Google Gemini API is generally available now. Please add support for it. Also give clear instructions on how to use it. The others issues do not seem to address the issue properly. I intend to use it on the cli.

**Comment by maruel** [comment]
I believe litellm is used. See litellm documentation how to use gemini at  https://docs.litellm.ai/docs/providers/gemini.

**Comment by Saedbhati** [comment]
can you assign these task to me?

**Comment by MikeBirdTech** [comment]
@snipeart007 
Did you still have questions about how to use Gemini? Did you check the documentation? https://docs.openinterpreter.com/getting-started/introduction

**Comment by omarnahdi** [comment]
@MikeBirdTech first of all loved your videos, thanks for your resources but can you help me with gemini too? At first it was generating the output but failed in between, this is the following error:

Traceback (most recent call last):
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\lib\site-packages\litellm\utils.py", line
7541, in __next__
    chunk = next(self.completion_stream)
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model
Testing\venv\lib\site-packages\litellm\llms\vertex_ai_and_google_ai_studio\gemini\vertex_and_google_ai_studio_gemini.py"
, line 1618, in __next__
    return self._common_chunk_parsing_logic(chunk=chunk)
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model
Testing\venv\lib\site-packages\litellm\llms\vertex_ai_and_google_ai_studio\gemini\vertex_and_google_ai_studio_gemini.py"
, line 1592, in _common_chunk_parsing_logic
    return self.handle_valid_json_chunk(chunk=chunk)
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model
Testing\venv\lib\site-packages\litellm\llms\vertex_ai_and_google_ai_studio\gemini\vertex_and_google_ai_studio_gemini.py"
, line 1558, in handle_valid_json_chunk
    return self.chunk_parser(chunk=json_chunk)
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model
Testing\venv\lib\site-packages\litellm\llms\vertex_ai_and_google_ai_studio\gemini\vertex_and_google_ai_studio_gemini.py"
, line 1491, in chunk_parser
    name=gemini_chunk["content"]["parts"][0]["functionCall"][
KeyError: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python 3.10\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Python 3.10\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\Scripts\interpreter.exe\__main__.py", line
7, in <module>
    sys.exit(main())
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model
Testing\venv\lib\site-packages\interpreter\terminal_interface\start_terminal_interface.py", line 612, in main
    start_terminal_interface(interpreter)
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model
Testing\venv\lib\site-packages\interpreter\terminal_interface\start_terminal_interface.py", line 578, in
start_terminal_interface
    interpreter.chat()
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model
Testing\venv\lib\site-packages\interpreter\core\core.py", line 191, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model
Testing\venv\lib\site-packages\interpreter\core\core.py", line 223, in _streaming_chat
    yield from terminal_interface(self, message)
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model
Testing\venv\lib\site-packages\interpreter\terminal_interface\terminal_interface.py", line 162, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model
Testing\venv\lib\site-packages\interpreter\core\core.py", line 259, in _streaming_chat
    yield from self._respond_and_store()
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model
Testing\venv\lib\site-packages\interpreter\core\core.py", line 318, in _respond_and_store
    for chunk in respond(self):
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model
Testing\venv\lib\site-packages\interpreter\core\respond.py", line 87, in respond
    for chunk in interpreter.llm.run(messages_for_llm):
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model
Testing\venv\lib\site-packages\interpreter\core\llm\llm.py", line 322, in run
    yield from run_tool_calling_llm(self, params)
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model
Testing\venv\lib\site-packages\interpreter\core\llm\run_tool_calling_llm.py", line 178, in run_tool_calling_llm
    for chunk in llm.completions(**request_params):
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model
Testing\venv\lib\site-packages\interpreter\core\llm\llm.py", line 466, in fixed_litellm_completions
    raise first_error  # If all attempts fail, raise the first error
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model
Testing\venv\lib\site-packages\interpreter\core\llm\llm.py", line 443, in fixed_litellm_completions
    yield from litellm.completion(**params)
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\lib\site-packages\litellm\utils.py", line
7634, in __next__
    raise exception_type(
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model
Testing\venv\lib\site-packages\litellm\litellm_core_utils\exception_mapping_utils.py", line 2126, in exception_type
    raise e
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model
Testing\venv\lib\site-packages\litellm\litellm_core_utils\exception_mapping_utils.py", line 2102, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: litellm.APIConnectionError: 'name'
Traceback (most recent call last):
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\lib\site-packages\litellm\utils.py", line
7541, in __next__
    chunk = next(self.completion_stream)
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model
Testing\venv\lib\site-packages\litellm\llms\vertex_ai_and_google_ai_studio\gemini\vertex_and_google_ai_studio_gemini.py"
, line 1618, in __next__
    return self._common_chunk_parsing_logic(chunk=chunk)
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model
Testing\venv\lib\site-packages\litellm\llms\vertex_ai_and_google_ai_studio\gemini\vertex_and_google_ai_studio_gemini.py"
, line 1592, in _common_chunk_parsing_logic
    return self.handle_valid_json_chunk(chunk=chunk)
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model
Testing\venv\lib\site-packages\litellm\llms\vertex_ai_and_google_ai_studio\gemini\vertex_and_google_ai_studio_gemini.py"
, line 1558, in handle_valid_json_chunk
    return self.chunk_parser(chunk=json_chunk)
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model
Testing\venv\lib\site-packages\litellm\llms\vertex_ai_and_google_ai_studio\gemini\vertex_and_google_ai_studio_gemini.py"
, line 1491, in chunk_parser
    name=gemini_chunk["content"]["parts"][0]["functionCall"][
KeyError: 'name'


  Plan:

   1 Use the computer.browser.go_to_url() function to open youtube.

  I can do that. I'll open youtube in the default browser.

  Plan:

   1 Use the computer.browser tools to open youtube.

  ●

**Comment by MikeBirdTech** [comment]
@omarnahdi Thanks!

What command did you use to run it? You'll probably need to pass a flag about function calling

https://docs.openinterpreter.com/settings/all-settings#llm-supports-functions

**Comment by omarnahdi** [comment]
@MikeBirdTech Hey mike! I tried with the `--llm_supports_functions` but it still gave me an error. Below is the log file attach hope it'll help. I tried with gemini-pro gemini-1.5-pro but it didn't help.

`(venv) C:\Users\Infinix>interpreter --model gemini/gemini-1.5-pro --llm_supports_functions

▌ Model set to gemini/gemini-1.5-pro

Open Interpreter will require approval before running code.

Use interpreter -y to bypass this.

Press CTRL-C to exit.

> Hello!

  Hello Infinix! How can I help you today?

> Can you search for the latest news about OpenAI?
Traceback (most recent call last):
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\lib\site-packages\litellm\utils.py", line 7541, in __next__
    chunk = next(self.completion_stream)
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\lib\site-packages\litellm\llms\vertex_ai_and_google_ai_studio\gemini\vertex_and_google_ai_studio_gemini.py", line 1618, in __next__
    return self._common_chunk_parsing_logic(chunk=chunk)
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\lib\site-packages\litellm\llms\vertex_ai_and_google_ai_studio\gemini\vertex_and_google_ai_studio_gemini.py", line 1592, in _common_chunk_parsing_logic
    return self.handle_valid_json_chunk(chunk=chunk)
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\lib\site-packages\litellm\llms\vertex_ai_and_google_ai_studio\gemini\vertex_and_google_ai_studio_gemini.py", line 1558, in handle_valid_json_chunk
    return self.chunk_parser(chunk=json_chunk)
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\lib\site-packages\litellm\llms\vertex_ai_and_google_ai_studio\gemini\vertex_and_google_ai_studio_gemini.py", line 1491, in chunk_parser
    name=gemini_chunk["content"]["parts"][0]["functionCall"][
KeyError: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python 3.10\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Python 3.10\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\Scripts\interpreter.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\lib\site-packages\interpreter\terminal_interface\start_terminal_interface.py", line 612, in main
    start_terminal_interface(interpreter)
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\lib\site-packages\interpreter\terminal_interface\start_terminal_interface.py", line 578, in start_terminal_interface
    interpreter.chat()
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\lib\site-packages\interpreter\core\core.py", line 191, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\lib\site-packages\interpreter\core\core.py", line 223, in _streaming_chat
    yield from terminal_interface(self, message)
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\lib\site-packages\interpreter\terminal_interface\terminal_interface.py", line 162, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\lib\site-packages\interpreter\core\core.py", line 259, in _streaming_chat
    yield from self._respond_and_store()
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\lib\site-packages\interpreter\core\core.py", line 318, in _respond_and_store
    for chunk in respond(self):
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\lib\site-packages\interpreter\core\respond.py", line 87, in respond
    for chunk in interpreter.llm.run(messages_for_llm):
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\lib\site-packages\interpreter\core\llm\llm.py", line 322, in run
    yield from run_tool_calling_llm(self, params)
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\lib\site-packages\interpreter\core\llm\run_tool_calling_llm.py", line 178, in run_tool_calling_llm
    for chunk in llm.completions(**request_params):
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\lib\site-packages\interpreter\core\llm\llm.py", line 466, in fixed_litellm_completions
    raise first_error  # If all attempts fail, raise the first error
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\lib\site-packages\interpreter\core\llm\llm.py", line 443, in fixed_litellm_completions
    yield from litellm.completion(**params)
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\lib\site-packages\litellm\utils.py", line 7634, in __next__
    raise exception_type(
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\lib\site-packages\litellm\litellm_core_utils\exception_mapping_utils.py", line 2126, in exception_type
    raise e
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\lib\site-packages\litellm\litellm_core_utils\exception_mapping_utils.py", line 2102, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: litellm.APIConnectionError: 'name'
Traceback (most recent call last):
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\lib\site-packages\litellm\utils.py", line 7541, in __next__
    chunk = next(self.completion_stream)
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\lib\site-packages\litellm\llms\vertex_ai_and_google_ai_studio\gemini\vertex_and_google_ai_studio_gemini.py", line 1618, in __next__
    return self._common_chunk_parsing_logic(chunk=chunk)
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\lib\site-packages\litellm\llms\vertex_ai_and_google_ai_studio\gemini\vertex_and_google_ai_studio_gemini.py", line 1592, in _common_chunk_parsing_logic
    return self.handle_valid_json_chunk(chunk=chunk)
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\lib\site-packages\litellm\llms\vertex_ai_and_google_ai_studio\gemini\vertex_and_google_ai_studio_gemini.py", line 1558, in handle_valid_json_chunk
    return self.chunk_parser(chunk=json_chunk)
  File "C:\Users\Infinix\Desktop\Pycharm code\Hugging Face Model Testing\venv\lib\site-packages\litellm\llms\vertex_ai_and_google_ai_studio\gemini\vertex_and_google_ai_studio_gemini.py", line 1491, in chunk_parser
    name=gemini_chunk["content"]["parts"][0]["functionCall"][
KeyError: 'name'
`

**Comment by MikeBirdTech** [comment]
@omarnahdi did you try with `--no-llm_supports_functions`?

**Comment by omarnahdi** [comment]
@MikeBirdTech still failed even worse it breaks the code execution function of the model, I tried with gemini-pro, gemini-1.5-pro even with flash variants too, yet it failed,
![image](https://github.com/user-attachments/assets/e06fd3a9-9445-43ef-8708-0dab4a299c08)

**Comment by interpreterwork** [comment]
Thank you for reporting this and for helping build the classic Python version of Open Interpreter. This issue concerns the earlier Python/LiteLLM/Jupyter product; this repository now tracks the Rust Open Interpreter built on Codex. We are closing the legacy report here so current product tracking starts clean. If you still want to pursue it, the community-maintained classic fork is https://github.com/endolith/open-interpreter. If the same problem affects the current Interpreter release, please open a new issue with the current template and include the version, provider, model, wire API, harness, platform, and reproduction.
