### ISSUE TITLE
Code Llama doesn’t work on my Macbook 

### ISSUE THREAD

**Issue by Swallow74** [KillianLucas/open-interpreter#108]
I successfully installed Open Interpreter on my Macbook Air M1 with 16GB of RAM. If I use GPT everything is ok, but if I try Code Llama (in all possible variations of parameters, quality and CPU/GPU) after sending any command I always get the same error:

Traceback (most recent call last):
  File "/Users/macbookair/anaconda3/bin/interpreter", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/macbookair/anaconda3/lib/python3.11/site-packages/interpreter/interpreter.py", line 91, in cli
    cli(self)
  File "/Users/macbookair/anaconda3/lib/python3.11/site-packages/interpreter/cli.py", line 42, in cli
    interpreter.chat()
  File "/Users/macbookair/anaconda3/lib/python3.11/site-packages/interpreter/interpreter.py", line 245, in chat
    self.respond()
  File "/Users/macbookair/anaconda3/lib/python3.11/site-packages/interpreter/interpreter.py", line 302, in respond
    messages = tt.trim(self.messages, self.model, system_message=system_message)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookair/anaconda3/lib/python3.11/site-packages/tokentrim/tokentrim.py", line 145, in trim
    raise ValueError("System message exceeds token limit")
ValueError: System message exceeds token limit

**Comment by Swallow74** [comment]
Ok, the updated version of tokentrim.py has resolved issue
