### ISSUE TITLE
Parent appears to have exited, shutting down.

### ISSUE THREAD

**Issue by tomwarias** [KillianLucas/open-interpreter#1083]
### Describe the bug

C:\Users\NZXT>interpreter

▌ Model set to gpt-4

Open Interpreter will require approval before running code.

Use interpreter -y to bypass this.

Press CTRL-C to exit.

> Hello

        Python Version: 3.10.4
        Pip Version: 24.0
        Open-interpreter Version: cmd: Open Interpreter 0.2.2 New Computer Update
, pkg: 0.2.2
        OS Version and Architecture: Windows-10-10.0.22000-SP0
        CPU Info: Intel64 Family 6 Model 165 Stepping 5, GenuineIntel
        RAM Info: 15.92 GB, used: 9.32, free: 6.61

        # Interpreter Info

        Vision: False
        Model: gpt-4
        Function calling: None
        Context window: None
        Max tokens: None

        Auto run: False
        API base: None
        Offline: False

        Curl output: Not local

        # Messages

        System Message: You are Open Interpreter, a world-class programmer that can complete any goal by executing code.First, write a plan. **Always recap the plan between each code block** (you have extreme short-term memory loss, so you need to recap the plan between each message block to retain it).
When you execute code, it will be executed **on the user's machine**. The user has given you **full and complete permission** to execute any code necessary to complete the task. Execute the code.
If you want to send data between programming languages, save the data to a txt or json.
You can access the internet. Run **any code** to achieve the goal, and if at first you don't succeed, try again and again.
You can install new packages.
When a user refers to a filename, they're likely referring to an existing file in the directory you're currently executing code in.
Write messages to the user in Markdown.
In general, try to **make plans** with as few steps as possible. As for actually executing code to carry out that plan, for *stateful* languages (like python, javascript, shell, but NOT for html which starts from 0 every time) **it's critical not to try to do everything in one code block.** You should try something, print information about it, then continue from there in tiny, informed steps. You will never get it on the first try, and attempting it in one go will often lead to errors you cant see.
You are capable of **any** task.

# THE COMPUTER API

A python `computer` module is ALREADY IMPORTED, and can be used for many tasks:

```python
computer.browser.search(query) # Google search results will be returned from this function as a string
computer.files.edit(path_to_file, original_text, replacement_text) # Edit a file
computer.calendar.create_event(title="Meeting", start_date=datetime.datetime.now(), end=datetime.datetime.now() + datetime.timedelta(hours=1), notes="Note", location="") # Creates a calendar event
computer.calendar.get_events(start_date=datetime.date.today(), end_date=None) # Get events between dates. If end_date is None, only gets events for start_date
computer.calendar.delete_event(event_title="Meeting", start_date=datetime.datetime) # Delete a specific event with a matching title and start date, you may need to get use get_events() to find the specific event object first
computer.contacts.get_phone_number("John Doe")
computer.contacts.get_email_address("John Doe")
computer.mail.send("john@email.com", "Meeting Reminder", "Reminder that our meeting is at 3pm today.", ["path/to/attachment.pdf", "path/to/attachment2.pdf"]) # Send an email with a optional attachments
computer.mail.get(4, unread=True) # Returns the {number} of unread emails, or all emails if False is passed
computer.mail.unread_count() # Returns the number of unread emails
computer.sms.send("555-123-4567", "Hello from the computer!") # Send a text message. MUST be a phone number, so use computer.contacts.get_phone_number frequently here
```

Do not import the computer module, or any of its sub-modules. They are already imported.

User Info{{import getpass
import os
import platform}}
Name: {{getpass.getuser()}}
CWD: {{os.getcwd()}}
SHELL: {{os.environ.get('SHELL')}}
OS: {{platform.system()}}"

        {'role': 'user', 'type': 'message', 'content': 'Hello'}

Traceback (most recent call last):
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\llms\openai.py", line 376, in completion
    raise e
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\llms\openai.py", line 294, in completion
    return self.streaming(
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\llms\openai.py", line 476, in streaming
    response = openai_client.chat.completions.create(**data, timeout=timeout)
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\_utils\_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\resources\chat\completions.py", line 663, in create
    return self._post(
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\_base_client.py", line 1200, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\_base_client.py", line 889, in request
    return self._request(
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\_base_client.py", line 980, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: x. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\main.py", line 958, in completion
    raise e
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\main.py", line 931, in completion
    response = openai_chat_completions.completion(
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\llms\openai.py", line 382, in completion
    raise OpenAIError(status_code=e.status_code, message=str(e))
litellm.llms.openai.OpenAIError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: x. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\core\llm\llm.py", line 235, in fixed_litellm_completions
    yield from litellm.completion(**params)
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 2727, in wrapper    raise e
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 2628, in wrapper    result = original_function(*args, **kwargs)
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\main.py", line 2056, in completion
    raise exception_type(
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 8146, in exception_type
    raise e
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 6964, in exception_type
    raise AuthenticationError(
litellm.exceptions.AuthenticationError: OpenAIException - Error code: 401 - {'error': {'message': 'Incorrect API key provided: x. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\Scripts\interpreter.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\terminal_interface\start_terminal_interface.py", line 415, in main
    start_terminal_interface(interpreter)
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\terminal_interface\start_terminal_interface.py", line 393, in start_terminal_interface
    interpreter.chat()
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\core\core.py", line 154, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\core\core.py", line 183, in _streaming_chat
    yield from terminal_interface(self, message)
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\terminal_interface\terminal_interface.py", line 136, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\core\core.py", line 222, in _streaming_chat
    yield from self._respond_and_store()
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\core\core.py", line 268, in _respond_and_store
    for chunk in respond(self):
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\core\respond.py", line 68, in respond
    for chunk in interpreter.llm.run(messages_for_llm):
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\core\llm\llm.py", line 205, in run
    yield from run_function_calling_llm(self, params)
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\core\llm\run_function_calling_llm.py", line 44, in run_function_calling_llm
    for chunk in llm.completions(**request_params):
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\core\llm\llm.py", line 238, in fixed_litellm_completions
    raise first_error
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\core\llm\llm.py", line 219, in fixed_litellm_completions
    yield from litellm.completion(**params)
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 2727, in wrapper    raise e
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 2628, in wrapper    result = original_function(*args, **kwargs)
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\main.py", line 2056, in completion
    raise exception_type(
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 8146, in exception_type
    raise e
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 6995, in exception_type
    raise RateLimitError(
litellm.exceptions.RateLimitError: OpenAIException - Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.

### Reproduce

Reproduce
set openAI API key
start Interpreter
prompt
Expected behavior
I'd expect it to work as it did before. Sorry for not being more helpful.

Screenshots
No response

Open Interpreter version
0.2.2

Python version
3.10.4

Operating System name and version
Windows 11 

### Expected behavior

It worked fine until i updated for new version,  when i install older version it doesnt work even on local

### Open Interpreter version

0.2.2

### Python version

3.10.4

### Operating System name and version

Windows 11

**Comment by tomwarias** [comment]
I tried on computer and laptop, got the same result

**Comment by MikeBirdTech** [comment]
Hi @tomwarias 

It looks like you've passed your OpenAI quota

```
raise RateLimitError(
litellm.exceptions.RateLimitError: OpenAIException - Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
```

Are you able to try with a local model to see if that allows you to use OI?

**Comment by abhishekvijayakumar** [comment]
@MikeBirdTech I am also facing the same quota error as well. However, I don't understand why I am receiving it since my usage and billing show that I haven't used any of it.

<img width="1498" alt="Screenshot 2024-03-17 at 10 57 34 AM" src="https://github.com/KillianLucas/open-interpreter/assets/71229160/6f825a98-047f-4396-a819-f4737567f7bc">

**Comment by MikeBirdTech** [comment]
@abhishekvijayakumar Are you able to make curl requests using the same API key that you're using with OI?

https://platform.openai.com/docs/api-reference/making-requests

**Comment by tomwarias** [comment]
@MikeBirdTech  It doesnt work on local model either, i should have metioned that @MikeBirdTech

**Comment by tomwarias** [comment]
I have reinstalled python and interpreter, if i try to use openai it gaves me the same error if  I use local it dowlands Phi model and the opens local webserver
![image](https://github.com/KillianLucas/open-interpreter/assets/105791364/ab0fdea2-fee6-43aa-ac03-87514bf5aadb)

**Comment by MikeBirdTech** [comment]
Local mode fix is coming in the next day or two!

**Comment by abhishekvijayakumar** [comment]
> @abhishekvijayakumar Are you able to make curl requests using the same API key and OpenAI model that you're using with OI?
> 
> https://platform.openai.com/docs/api-reference/making-requests

@MikeBirdTech yes, please see screenshot of response results:
<img width="652" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/71229160/d413fb89-edbc-487d-8683-989238e4115e">

**Comment by filip-van-hoeckel** [comment]
Having the same issue, but without the OpenAI quota errors. Just performing any basic tasks leads to the '[IPKernelApp] WARNING | Parent appears to have exited, shutting down.' error.

**Comment by MikeBirdTech** [comment]
@filip-van-hoeckel The error `[IPKernelApp] WARNING | Parent appears to have exited, shutting down` typically occurs in the context of Jupyter notebooks or similar interactive Python environments. It indicates that the "parent" process, which is usually the Jupyter server that manages your notebook or interactive Python session, has unexpectedly stopped or is no longer communicating with the "child" process, which is the kernel running your Python code.

What is the error you're seeing prior to that?

**Comment by filip-van-hoeckel** [comment]
@MikeBirdTech see https://github.com/OpenInterpreter/open-interpreter/issues/1125#issuecomment-2016929036 for an example.

**Comment by interpreterwork** [comment]
Thank you for reporting this and for helping build the classic Python version of Open Interpreter. This issue concerns the earlier Python/LiteLLM/Jupyter product; this repository now tracks the Rust Open Interpreter built on Codex. We are closing the legacy report here so current product tracking starts clean. If you still want to pursue it, the community-maintained classic fork is https://github.com/endolith/open-interpreter. If the same problem affects the current Interpreter release, please open a new issue with the current template and include the version, provider, model, wire API, harness, platform, and reproduction.
