### ISSUE TITLE
installing problem

### ISSUE THREAD

**Issue by bedouinbro** [KillianLucas/open-interpreter#1088]
### Is your feature request related to a problem? Please describe.

having trouble installing the open interper, https://docs.openinterpreter.com/getting-started/setup followed this guide, python 3.11 is already installed, here are the errors https://i.postimg.cc/cJpsJXs3/Screenshot-48.png

https://i.postimg.cc/Kztm3BzH/Screenshot-49.png

https://i.postimg.cc/8cDNRcfP/Screenshot-50.png

### Describe the solution you'd like

one click installer would be great !

**Comment by MikeBirdTech** [comment]
Hi @bedouinbro 
Sorry to hear that you're having trouble.
In the first screenshot, I can see multiple packages that are for python 3.12. Can you please make sure that you are installing in an environment with python 3.11? Tiktoken doesn't play nice with 3.12 yet.

Also, did you try using the installer in https://github.com/KillianLucas/open-interpreter/tree/main/installers?

**Comment by bedouinbro** [comment]
Hi @MikeBirdTech 
installed the python 3.10 and 3.11, after installing those I'm getting these responses. also ran it locally https://github.com/KillianLucas/open-interpreter/tree/main/installers
and I'm using  llama2-uncensored using ollama 

![Screenshot (57)](https://github.com/KillianLucas/open-interpreter/assets/160074076/928e2fa1-e17c-4947-ba9d-dfce4015e02e)
![Screenshot (58)](https://github.com/KillianLucas/open-interpreter/assets/160074076/322c58bf-6602-4305-8bbd-4500c0e7b239)
![Screenshot (59)](https://github.com/KillianLucas/open-interpreter/assets/160074076/62a66563-0d74-4073-b3b9-73d71d2955bd)
![Screenshot (60)](https://github.com/KillianLucas/open-interpreter/assets/160074076/e2a64135-fc10-45cf-8cee-0068d93a9c7c)

what am I missing ?

**Comment by fibirj** [comment]
So I have a new laptop specifically for running LLM experiments. Win11. Installed Python 3.11.8. Created a virtual environment. Installed open-interpreter with pip. Then, when I type `interpreter` in the virtual environment (Win command line with admin rights), the window just freezes *every time*...

I'd guess everyone would be advised to run this in virtual environment, so I find it strange that there's no mention about it in the "setup guide".

Or maybe it's the newer Python? Does anyone have problems with venv or Py3.11.8?

**Comment by fibirj** [comment]
Ok I needed to run `interpreter --os` first to download some additional packages it seems. Now it worked, only that after my first question, the interpreter searched the web, gave the answer, but then kept repeating whether it could do something else - without me being able to type any command in... 

Pretty fucking scary first experience... this is a ticking time bomb imo.

**Comment by fibirj** [comment]
1. Install Python 3.11.8
2. Open command line in a folder
3. Set up virtual environment `py -3.11 -m venv venv`
4. Activate virtual environment `.\venv\Scripts\activate`
5. Install `pip install open-interpreter`
6. Run it with `interpreter` -> freeze, did not work
7. Run `interpreter --os` --> asked to install other components (y), asked for API key (*api key*)
8. Run `interpreter.chat(*asked what a spren is*)` --> found great info online, but never stopped and kept asking what else it can do for me every 15s or so. scary.

**Comment by bedouinbro** [comment]
> 1. Install Python 3.11.8
> 2. Open command line in a folder
> 3. Set up virtual environment `py -3.11 -m venv venv`
> 4. Activate virtual environment `.\venv\Scripts\activate`
> 5. Install `pip install open-interpreter`
> 6. Run it with `interpreter` -> freeze, did not work
> 7. Run `interpreter --os` --> asked to install other components (y), asked for API key (_api key_)
> 8. Run `interpreter.chat(*asked what a spren is*)` --> found great info online, but never stopped and kept asking what else it can do for me every 15s or so. scary.

everything works till step 7 until it asks for an API key 
So I am using local ollama, llama2-uncensored, there's a guide for it but can't get it to work !
btw how long does a free open API key lasts ? any easy guides to get them ?
https://docs.openinterpreter.com/language-models/local-models/ollama
![Screenshot (61)](https://github.com/KillianLucas/open-interpreter/assets/160074076/6da374c5-ca89-401a-b8a6-cb3ce0da565f)
![Screenshot (62)](https://github.com/KillianLucas/open-interpreter/assets/160074076/629e2cfb-fb9a-4db3-9054-fe026d5b0b6b)

**Comment by bedouinbro** [comment]
> 1. Install Python 3.11.8
> 2. Open command line in a folder
> 3. Set up virtual environment `py -3.11 -m venv venv`
> 4. Activate virtual environment `.\venv\Scripts\activate`
> 5. Install `pip install open-interpreter`
> 6. Run it with `interpreter` -> freeze, did not work
> 7. Run `interpreter --os` --> asked to install other components (y), asked for API key (_api key_)
> 8. Run `interpreter.chat(*asked what a spren is*)` --> found great info online, but never stopped and kept asking what else it can do for me every 15s or so. scary.

edit 2 - figured how to get open API key but getting errors when executing them 
![Screenshot (63)](https://github.com/KillianLucas/open-interpreter/assets/160074076/8fdcad49-7bca-4cf6-a3d4-4faa919ad80c)
![Screenshot (64)](https://github.com/KillianLucas/open-interpreter/assets/160074076/6b256e9f-3d77-4d9b-a3a7-2d89af4f6cbd)

**Comment by bedouinbro** [comment]
here's the full response after entering the API 
[open interpreter error.txt](https://github.com/KillianLucas/open-interpreter/files/14670724/open.interpreter.error.txt)




Welcome to Open Interpreter.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

▌ OpenAI API key not found

To use GPT-4 (highly recommended) please provide an OpenAI API key.

To use another language model, consult the documentation at docs.openinterpreter.com.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

OpenAI API key: ***************************************************


Tip: To save this key for later, run export OPENAI_API_KEY=your_api_key on Mac/Linux or setx OPENAI_API_KEY your_api_key
on Windows.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

▌ Model set to gpt-4

Open Interpreter will require approval before running code.

Use interpreter -y to bypass this.

Press CTRL-C to exit.

> What time is it in Seattle?
  You do not have access to gpt-4. You will need to add a payment method and purchase credits for the OpenAI API billing page (different from ChatGPT) to use `GPT-4`.

https://platform.openai.com/account/billing/overview

Would you like to try GPT-3.5-TURBO instead? (y/n)

  y


▌ Model set to gpt-3.5-turbo-1106

> What time is it in Seattle?
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.

        Python Version: 3.11.8
        Pip Version: 24.0
        Open-interpreter Version: cmd: Open Interpreter 0.2.3 New Computer Update
, pkg: 0.2.3
        OS Version and Architecture: Windows-10-10.0.19045-SP0
        CPU Info: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
        RAM Info: 15.94 GB, used: 13.33, free: 2.61


        # Interpreter Info

        Vision: False
        Model: gpt-3.5-turbo-1106
        Function calling: True
        Context window: 16000
        Max tokens: 4096

        Auto run: False
        API base: None
        Offline: False

        Curl output: Not local

        # Messages

        System Message: You are Open Interpreter, a world-class programmer that can complete any goal by executing code.
First, write a plan. **Always recap the plan between each code block** (you have extreme short-term memory loss, so you need to recap the plan between each message block to retain it).
When you execute code, it will be executed **on the user's machine**. The user has given you **full and complete permission** to execute any code necessary to complete the task. Execute the code.
If you want to send data between programming languages, save the data to a txt or json.
You can access the internet. Run **any code** to achieve the goal, and if at first you don't succeed, try again and again.
You can install new packages.
When a user refers to a filename, they're likely referring to an existing file in the directory you're currently executing code in.
Write messages to the user in Markdown.
In general, try to **make plans** with as few steps as possible. As for actually executing code to carry out that plan, for *stateful* languages (like python, javascript, shell, but NOT for html which starts from 0 every time) **it's critical not to try to do everything in one code block.** You should try something, print information about it, then continue from there in tiny, informed steps. You will never get it on the first try, and attempting it in one go will often lead to errors you cant see.
You are capable of **any** task.

# THE COMPUTER API

A python `computer` module is ALREADY IMPORTED, and can be used for many tasks:

```python
computer.browser.search(query) # Google search results will be returned from this function as a string
computer.files.edit(path_to_file, original_text, replacement_text) # Edit a file
computer.calendar.create_event(title="Meeting", start_date=datetime.datetime.now(), end=datetime.datetime.now() + datetime.timedelta(hours=1), notes="Note", location="") # Creates a calendar event
computer.calendar.get_events(start_date=datetime.date.today(), end_date=None) # Get events between dates. If end_date is None, only gets events for start_date
computer.calendar.delete_event(event_title="Meeting", start_date=datetime.datetime) # Delete a specific event with a matching title and start date, you may need to get use get_events() to find the specific event object first
computer.contacts.get_phone_number("John Doe")
computer.contacts.get_email_address("John Doe")
computer.mail.send("john@email.com", "Meeting Reminder", "Reminder that our meeting is at 3pm today.", ["path/to/attachment.pdf", "path/to/attachment2.pdf"]) # Send an email with a optional attachments
computer.mail.get(4, unread=True) # Returns the {number} of unread emails, or all emails if False is passed
computer.mail.unread_count() # Returns the number of unread emails
computer.sms.send("555-123-4567", "Hello from the computer!") # Send a text message. MUST be a phone number, so use computer.contacts.get_phone_number frequently here
```

Do not import the computer module, or any of its sub-modules. They are already imported.

User Info{{import getpass
import os
import platform

print(f"Name: {getpass.getuser()}")
print(f"CWD: {os.getcwd()}")
print(f"SHELL: {os.environ.get('SHELL')}")
print(f"OS: {platform.system()}")

}}

        {'role': 'user', 'type': 'message', 'content': 'What time is it in Seattle?'}

{'role': 'user', 'type': 'message', 'content': 'What time is it in Seattle?'}

Traceback (most recent call last):
  File "C:\Users\Mehdi\venv\Lib\site-packages\litellm\llms\openai.py", line 376, in completion
    raise e
  File "C:\Users\Mehdi\venv\Lib\site-packages\litellm\llms\openai.py", line 294, in completion
    return self.streaming(
           ^^^^^^^^^^^^^^^
  File "C:\Users\Mehdi\venv\Lib\site-packages\litellm\llms\openai.py", line 476, in streaming
    response = openai_client.chat.completions.create(**data, timeout=timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mehdi\venv\Lib\site-packages\openai\_utils\_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mehdi\venv\Lib\site-packages\openai\resources\chat\completions.py", line 667, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\Mehdi\venv\Lib\site-packages\openai\_base_client.py", line 1208, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mehdi\venv\Lib\site-packages\openai\_base_client.py", line 897, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\Mehdi\venv\Lib\site-packages\openai\_base_client.py", line 988, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: x. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mehdi\venv\Lib\site-packages\litellm\main.py", line 958, in completion
    raise e
  File "C:\Users\Mehdi\venv\Lib\site-packages\litellm\main.py", line 931, in completion
    response = openai_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mehdi\venv\Lib\site-packages\litellm\llms\openai.py", line 382, in completion
    raise OpenAIError(status_code=e.status_code, message=str(e))
litellm.llms.openai.OpenAIError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: x. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mehdi\venv\Lib\site-packages\interpreter\core\llm\llm.py", line 234, in fixed_litellm_completions
    yield from litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mehdi\venv\Lib\site-packages\litellm\utils.py", line 2792, in wrapper
    raise e
  File "C:\Users\Mehdi\venv\Lib\site-packages\litellm\utils.py", line 2693, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mehdi\venv\Lib\site-packages\litellm\main.py", line 2058, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\Mehdi\venv\Lib\site-packages\litellm\utils.py", line 8265, in exception_type
    raise e
  File "C:\Users\Mehdi\venv\Lib\site-packages\litellm\utils.py", line 7083, in exception_type
    raise AuthenticationError(
litellm.exceptions.AuthenticationError: OpenAIException - Error code: 401 - {'error': {'message': 'Incorrect API key provided: x. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Mehdi\venv\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\Mehdi\venv\Lib\site-packages\interpreter\terminal_interface\start_terminal_interface.py", line 437, in main
    start_terminal_interface(interpreter)
  File "C:\Users\Mehdi\venv\Lib\site-packages\interpreter\terminal_interface\start_terminal_interface.py", line 415, in start_terminal_interface
    interpreter.chat()
  File "C:\Users\Mehdi\venv\Lib\site-packages\interpreter\core\core.py", line 167, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "C:\Users\Mehdi\venv\Lib\site-packages\interpreter\core\core.py", line 196, in _streaming_chat
    yield from terminal_interface(self, message)
  File "C:\Users\Mehdi\venv\Lib\site-packages\interpreter\terminal_interface\terminal_interface.py", line 136, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "C:\Users\Mehdi\venv\Lib\site-packages\interpreter\core\core.py", line 235, in _streaming_chat
    yield from self._respond_and_store()
  File "C:\Users\Mehdi\venv\Lib\site-packages\interpreter\core\core.py", line 281, in _respond_and_store
    for chunk in respond(self):
  File "C:\Users\Mehdi\venv\Lib\site-packages\interpreter\core\respond.py", line 69, in respond
    for chunk in interpreter.llm.run(messages_for_llm):
  File "C:\Users\Mehdi\venv\Lib\site-packages\interpreter\core\llm\llm.py", line 204, in run
    yield from run_function_calling_llm(self, params)
  File "C:\Users\Mehdi\venv\Lib\site-packages\interpreter\core\llm\run_function_calling_llm.py", line 44, in run_function_calling_llm
    for chunk in llm.completions(**request_params):
  File "C:\Users\Mehdi\venv\Lib\site-packages\interpreter\core\llm\llm.py", line 237, in fixed_litellm_completions
    raise first_error
  File "C:\Users\Mehdi\venv\Lib\site-packages\interpreter\core\llm\llm.py", line 218, in fixed_litellm_completions
    yield from litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mehdi\venv\Lib\site-packages\litellm\utils.py", line 2792, in wrapper
    raise e
  File "C:\Users\Mehdi\venv\Lib\site-packages\litellm\utils.py", line 2693, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mehdi\venv\Lib\site-packages\litellm\main.py", line 2058, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\Mehdi\venv\Lib\site-packages\litellm\utils.py", line 8265, in exception_type
    raise e
  File "C:\Users\Mehdi\venv\Lib\site-packages\litellm\utils.py", line 7114, in exception_type
    raise RateLimitError(
litellm.exceptions.RateLimitError: OpenAIException - Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
(venv) PS C:\Users\Mehdi>

**Comment by nikkoxgonzales** [comment]
I can't believe you are launching a product called 01 and yet the installation of this whatever this is doesn't even work. At least make your instructions clearer, you're too focused on saying "Oh its just these 2 lines", well your 2 lines doesn't even work.
