### ISSUE TITLE
Crashes when using Llama on fedora linux in a virtual environment

### ISSUE THREAD

**Issue by mak448a** [KillianLucas/open-interpreter#147]
```shell
Open Interpreter will require approval before running code. Use interpreter -y to bypass this.               

Press CTRL-C to exit.                                                                                        

> Write me a wxpython program
Traceback (most recent call last):
  File "/home/user/venve/bin/interpreter", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/user/venve/lib64/python3.11/site-packages/interpreter/interpreter.py", line 104, in cli
    cli(self)
  File "/home/user/venve/lib64/python3.11/site-packages/interpreter/cli.py", line 46, in cli
    interpreter.chat()
  File "/home/user/venve/lib64/python3.11/site-packages/interpreter/interpreter.py", line 256, in chat
    self.respond()
  File "/home/user/venve/lib64/python3.11/site-packages/interpreter/interpreter.py", line 456, in respond
    response = self.llama_instance(
               ^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
```

**Comment by mak448a** [comment]
Whoops my bad. Make sure to pip install wheel if you're getting this error
