### ISSUE TITLE
UnicodeDecodeError - help will be appriciate! 

### ISSUE THREAD

**Issue by zivafgin** [KillianLucas/open-interpreter#209]
_Exception in thread Thread-1 (save_and_display_stream):
Traceback (most recent call last):
  File "C:\Users\ziv\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\ziv\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ziv\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\code_interpreter.py", line
293, in save_and_display_stream
    for line in iter(stream.readline, ''):
  File "C:\Users\ziv\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1255.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8e in position 3284: character maps to <undefined>_

I am a Windows User, running with Conda, on Python version 3.11.2
 should I change the encoding?

**Comment by Everminds** [comment]
Getting the same error

**Comment by Everminds** [comment]
Notice that #231 does not solve this issue. I implemented it locally, still getting this error:
```
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\envs\openinterpreter\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\User\anaconda3\envs\openinterpreter\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\anaconda3\envs\openinterpreter\Lib\site-packages\interpreter\code_interpreter.py", line 298, in
save_and_display_stream
    for line in iter(stream.readline, ''):
  File "C:\Users\User\anaconda3\envs\openinterpreter\Lib\encodings\cp1255.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8c in position 30: character maps to <undefined>
```

**Comment by zivafgin** [comment]
Does someone know how to solve it?

**Comment by CodeAKrome** [comment]
That looks like a Hebrew code page reference. cp1255.
https://en.wikipedia.org/wiki/Windows-1255
That's a right to left language. I do I18N. It was challenging.
Are you using Hebrew?

**Comment by sadolano** [comment]
Hi. I have a similar error on Windows 10 german, python 3.11.3. In my case its cp1252:

` Exception in thread Thread-102 (save_and_display_stream):
Traceback (most recent call last):
  File "C:\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python311\Lib\site-packages\interpreter\code_interpreter.py", line 326, in save_and_display_stream
    for line in iter(stream.readline, ''):
  File "C:\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1482: character maps to <undefined>`

**Comment by ericrallen** [comment]
Hey there, folks!

Going to try to consolidate the conversation around UnicodeDecodeError and UnicodeEncodeError into #93

Please feel encouraged to continue the discussion in that thread so we’ve got everything in one spot.
