### ISSUE TITLE
 Failed to install Code-LLama.

### ISSUE THREAD

**Issue by zzzqqq555** [KillianLucas/open-interpreter#212]
[?] `Code-Llama` interface package not found. Install `llama-cpp-python`? (Y/n):
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Python311\Lib\site-packages\pip\__main__.py", line 22, in <module>
    from pip._internal.cli.main import main as _main
  File "D:\Python311\Lib\site-packages\pip\_internal\cli\main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "D:\Python311\Lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "D:\Python311\Lib\site-packages\pip\_internal\cli\main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "D:\Python311\Lib\site-packages\pip\_internal\build_env.py", line 19, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "D:\Python311\Lib\site-packages\pip\_internal\cli\spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "D:\Python311\Lib\site-packages\pip\_internal\utils\logging.py", line 29, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "D:\Python311\Lib\site-packages\pip\_internal\utils\misc.py", line 37, in <module>
    from pip._vendor.tenacity import retry, stop_after_delay, wait_fixed
  File "D:\Python311\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 548, in <module>
    from pip._vendor.tenacity._asyncio import AsyncRetrying  # noqa:E402,I100
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\pip\_vendor\tenacity\_asyncio.py", line 21, in <module>
    from asyncio import sleep
  File "D:\Python311\Lib\asyncio\__init__.py", line 42, in <module>
    from .windows_events import *
  File "D:\Python311\Lib\asyncio\windows_events.py", line 8, in <module>
    import _overlapped
OSError: [WinError 10106] 无法加载或初始化请求的服务提供程序。
Error during installation with OpenBLAS: Command '['D:\\Python311\\python.exe', '-m', 'pip', 'install',
'llama-cpp-python']' returned non-zero exit status 1.

▌ Failed to install Code-LLama.

**Comment by ozanbilal** [comment]
You should follow these steps:

 https://github.com/KillianLucas/open-interpreter/blob/main/docs/WINDOWS.md

**Comment by zzzqqq555** [comment]
Okay, it's resolved
