### ISSUE TITLE
When I'm interacting, I encounter Python code errors.KeyError: 'python or'

### ISSUE THREAD

**Issue by chongthon** [KillianLucas/open-interpreter#217]
**Describe the bug**
When I interact in the terminal and enter "hello," it displays an error.

**To Reproduce**
1. ```interpreter -y```
2. OpenAI API key not found,press "Enter"
3. Parameter count,choose 7B
4. Quality,choose Low
5. Use GPU,choose no
6. Model set to Code-Llama
7. enter "hello",press "Enter"
8. An error appeared after 10 seconds
```bash
[User Info] Name: chong CWD: /Users/chong/work/open_interpereter OS: Darwin                                   
                                                                                                                
  To run code, write a fenced code block (i.e                                                                   
                                                                                                                


Traceback (most recent call last):
  File "/Users/chong/pyenv/open_interpreter_py_3_10/bin/interpreter", line 8, in <module>
    sys.exit(cli())
  File "/Users/chong/pyenv/open_interpreter_py_3_10/lib/python3.10/site-packages/interpreter/interpreter.py", line 104, in cli
    cli(self)
  File "/Users/chong/pyenv/open_interpreter_py_3_10/lib/python3.10/site-packages/interpreter/cli.py", line 46, in cli
    interpreter.chat()
  File "/Users/chong/pyenv/open_interpreter_py_3_10/lib/python3.10/site-packages/interpreter/interpreter.py", line 256, in chat
    self.respond()
  File "/Users/chong/pyenv/open_interpreter_py_3_10/lib/python3.10/site-packages/interpreter/interpreter.py", line 665, in respond
    code_interpreter.run()
  File "/Users/chong/pyenv/open_interpreter_py_3_10/lib/python3.10/site-packages/interpreter/code_interpreter.py", line 128, in run
    open_subrocess = language_map[self.language].get("open_subrocess", True)
KeyError: 'python or'
```

**Expected behavior**
I should see a normal response

**Screenshots**
<img width="932" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/51406582/39de8129-f223-46d5-bb61-641b0ab9e5be">

**System**
 - OS: mac os ventura 13.4.1
 - Python version: 3.10.13
 - Open Interpreter version: 0.1.1
 - Computer chip: Intel

**Comment by 0xVelo** [comment]
I am having the same issue

**Comment by 0xVelo** [comment]
well I just figured it out, for python prompt, you just need to add ```  ``` around your input prompt, so the input should be like ``` your prompt ```
Check line 175 in 'interpreter.py'

**Comment by ericrallen** [comment]
I’m going to close this as stale, but please reopen it if you experience the same issue with the latest version of Open Interpreter.
