### ISSUE TITLE
Replit connection error

### ISSUE THREAD

**Issue by 0xbboyd** [KillianLucas/open-interpreter#22]
Using python 3.10.0 in conda 

Interpreter opens with an initial chat When entering any basic prompt, interpreter crashes with the error below. Is this a problem with my install, or is this a legit internal exception? Thank you.

`
▌ Model set to GPT-4                                                                                                                                          

Tip: To run locally, use interpreter --local                                                                                                                    

Open Interpreter will require approval before running code. Use interpreter -y to bypass this.                                                                  

Press CTRL-C to exit.                                                                                                                                           

> Traceback (most recent call last):
  File "/home/bboyd/anaconda3/envs/open-interpreter/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/home/bboyd/anaconda3/envs/open-interpreter/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "/home/bboyd/anaconda3/envs/open-interpreter/lib/python3.10/site-packages/urllib3/connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/home/bboyd/anaconda3/envs/open-interpreter/lib/python3.10/site-packages/urllib3/connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/home/bboyd/anaconda3/envs/open-interpreter/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/home/bboyd/anaconda3/envs/open-interpreter/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/bboyd/anaconda3/envs/open-interpreter/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/bboyd/anaconda3/envs/open-interpreter/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/home/bboyd/anaconda3/envs/open-interpreter/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL] unknown error (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bboyd/anaconda3/envs/open-interpreter/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/home/bboyd/anaconda3/envs/open-interpreter/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL] unknown error (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bboyd/anaconda3/envs/open-interpreter/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/bboyd/anaconda3/envs/open-interpreter/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/home/bboyd/anaconda3/envs/open-interpreter/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='open-procedures.replit.app', port=443): Max retries exceeded with url: /search/?query=%5B%7B%27role%27%3A%20%27user%27%2C%20%27content%27%3A%20%27create%20an%20example%20python%20class%27%7D%5D (Caused by SSLError(SSLError(1, '[SSL] unknown error (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bboyd/anaconda3/envs/open-interpreter/bin/interpreter", line 8, in <module>
    sys.exit(cli())
  File "/home/bboyd/anaconda3/envs/open-interpreter/lib/python3.10/site-packages/interpreter/interpreter.py", line 90, in cli
    cli(self)
  File "/home/bboyd/anaconda3/envs/open-interpreter/lib/python3.10/site-packages/interpreter/cli.py", line 59, in cli
    interpreter.chat()
  File "/home/bboyd/anaconda3/envs/open-interpreter/lib/python3.10/site-packages/interpreter/interpreter.py", line 216, in chat
    self.respond()
  File "/home/bboyd/anaconda3/envs/open-interpreter/lib/python3.10/site-packages/interpreter/interpreter.py", line 272, in respond
    info = self.get_info_for_system_message()
  File "/home/bboyd/anaconda3/envs/open-interpreter/lib/python3.10/site-packages/interpreter/interpreter.py", line 118, in get_info_for_system_message
    relevant_procedures = requests.get(url).json()["procedures"]
  File "/home/bboyd/anaconda3/envs/open-interpreter/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/bboyd/anaconda3/envs/open-interpreter/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/bboyd/anaconda3/envs/open-interpreter/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bboyd/anaconda3/envs/open-interpreter/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/bboyd/anaconda3/envs/open-interpreter/lib/python3.10/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='open-procedures.replit.app', port=443): Max retries exceeded with url: /search/?query=%5B%7B%27role%27%3A%20%27user%27%2C%20%27content%27%3A%20%27create%20an%20example%20python%20class%27%7D%5D (Caused by SSLError(SSLError(1, '[SSL] unknown error (_ssl.c:997)')))
`

**Comment by KillianLucas** [comment]
Hi Brendan, thanks for opening this issue!

Since [Open Procedures](https://open-procedures.replit.app/) isn't essential (just helpful), with 8a247cba336168844d49ff9ecd331ac2a900c76b we put it in a Try/Except block so if it fails, we don't crash the whole thing. This will be in the official pip release by the end of the weekend.

In this case it looks like an SSL error of some kind, perhaps there's some network security settings that keep the package from accessing that URL? [ChatGPT suggested](https://chat.openai.com/share/390cd475-28c4-4f85-b670-2505906bfc30) reinstalling `requests` and `urllib31` with `pip install --upgrade --force-reinstall requests urllib31`.
