### ISSUE TITLE
error when launching llama 7b

### ISSUE THREAD

**Issue by DmitriSochlioukov** [KillianLucas/open-interpreter#223]
whenever I try to launch llama 7b model i get the following:

  [User Info] Name: dsoch CWD: C:\Users\dsoch OS: Windows

  To run code, write a fenced code block (i.e

  Would you like to run this code? (y/n)

  y

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\dsoch\AppData\Local\Programs\Python\Python311\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\dsoch\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\interpreter.py", line 104, in cli
    cli(self)
  File "C:\Users\dsoch\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\cli.py", line 46, in cli
    interpreter.chat()
  File "C:\Users\dsoch\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\interpreter.py", line 256, in chat
    self.respond()
  File "C:\Users\dsoch\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\interpreter.py", line 665, in respond
    code_interpreter.run()
  File "C:\Users\dsoch\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\code_interpreter.py", line 128, in run
    open_subrocess = language_map[self.language].get("open_subrocess", True)
                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'python or'

![image](https://github.com/KillianLucas/open-interpreter/assets/120190171/4f5ff377-873c-44fa-81ac-86c83ef7266a)

**Comment by 0xVelo** [comment]
I have the same issue

**Comment by 0xVelo** [comment]
well I just figured it out, for python prompt, you just need to add three ` at the beginning and end of your input prompt
Check line 175 in 'interpreter.py'

**Comment by ericrallen** [comment]
I’m going to close this one as stale, but please reopen it if you experience the same issue with the latest version of Open Interpreter.
