### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by jdnguyenswin** [KillianLucas/open-interpreter#245]
**Describe the bug**
I'm having trouble running any commands.

**To Reproduce**
After inputting my OpenAI key, when I give any command I get the following sort of error message:

**Screenshots**

NoneType: None
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/interpreter", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/interpreter.py", line 131, in cli
    cli(self)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/cli.py", line 207, in cli
    interpreter.chat()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/interpreter.py", line 287, in chat
    self.respond()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/interpreter.py", line 509, in respond
    raise Exception("")
Exception

**System (please complete the following information):**
 - OS: iOS
 - Python version: 3.11
 - Open Interpreter version (`pip show open-interpreter`): [e.g. 0.1.1] 

**Additional context**

**Comment by Michael-Jiahao-Zhang** [comment]
facing the exact same issue lol

**Comment by shenzo1** [comment]
same here on MacOs 13.2 
Open-interpreter 0.1.2
Python 3.11
in conda env

**Comment by diegodp-zz** [comment]
exactly same problem here

**Comment by Snape888** [comment]
Same here

**Comment by joewebbxp** [comment]
Same issue

**Comment by devxch** [comment]
Same

**Comment by SwannSchilling** [comment]
Same here Windows 10 
Python 3.10.4

**Comment by Zoheb-Malik** [comment]
This seems like the same issue someone else made, here is a suggested solution that has worked for some people: https://github.com/KillianLucas/open-interpreter/issues/247#issuecomment-1712959310

**Comment by TanmayDoesAI** [comment]
https://github.com/KillianLucas/open-interpreter/issues/247#issuecomment-1712978985
Should be fixed by this, if someone still faces any issues, feel free to reopen!

**Comment by diegodp-zz** [comment]
> [#247 (comment)](https://github.com/KillianLucas/open-interpreter/issues/247#issuecomment-1712978985)
> Should be fixed by this, if someone still faces any issues, feel free to reopen!

I am still getting the error. 

`Traceback (most recent call last):
  File "/opt/homebrew/bin/interpreter", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/interpreter.py", line 131, in cli
    cli(self)
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/cli.py", line 207, in cli
    interpreter.chat()
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/interpreter.py", line 287, in chat
    self.respond()
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/interpreter.py", line 510, in respond
    raise Exception(error)
Exception: Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/interpreter.py", line 495, in respond
    response = litellm.completion(
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/utils.py", line 584, in wrapper
    raise e
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/utils.py", line 544, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/timeout.py", line 44, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/timeout.py", line 33, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/main.py", line 850, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/utils.py", line 1960, in exception_type
    raise e
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/utils.py", line 1606, in exception_type
    raise original_exception
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/main.py", line 273, in completion
    raise e
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/main.py", line 256, in completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 106, in __prepare_create_request
    requestor = api_requestor.APIRequestor(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/openai/api_requestor.py", line 138, in __init__
    self.api_key = key or util.default_api_key()
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/openai/util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.

diegosilveira@MacBook-Air-de-Diego open-interpreter % `


have tried to use this. 
export OPENAI_API_KEY=<your key>

**Comment by TanmayDoesAI** [comment]
Could you share your open-interpreter version?

**Comment by diegodp-zz** [comment]
> 

sure.

Open Interpreter 0.1.3

**Comment by jordanbtucker** [comment]
> [#247 (comment)](https://github.com/KillianLucas/open-interpreter/issues/247#issuecomment-1712978985)
> Should be fixed by this, if someone still faces any issues, feel free to reopen!

@TanmayDoesAI Unfortunately, that doesn't fix the underlying error. It just makes the error message visible when OI crashes.

**Comment by TanmayDoesAI** [comment]
ah got you, apologies for the misunderstanding

**Comment by ishaan-jaff** [comment]
there was an issue where litellm was not correctly using

```python
litellm.api_base
litellm.api_key
litellm.api_version

```

This is now fixed in litellm 0.1.590 
Pr here: https://github.com/KillianLucas/open-interpreter/pull/284
