### ISSUE TITLE
Error NoneType: None Traceback (most recent call last):

### ISSUE THREAD

**Issue by joewebbxp** [KillianLucas/open-interpreter#247]
Imm getting this on Mac OS. Why would this be?

NoneType: None
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/interpreter", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/interpreter.py", line 131, in cli
    cli(self)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/cli.py", line 207, in cli
    interpreter.chat()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/interpreter.py", line 287, in chat
    self.respond()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/interpreter.py", line 509, in respond
    raise Exception("")
Exception

**Comment by metincc** [comment]
I see the same issue on Windows as well as WSL

**Comment by giswqs** [comment]
Same error on Linux

**Comment by Somnath6646** [comment]
same on mac m2

**Comment by kccchiu** [comment]
Same error on Linux with py3.10

**Comment by SwannSchilling** [comment]
Same Error here...

**Comment by cnguyenWurl** [comment]
this problem is because setting the openai key in the interpreter doesn't work. To make it work use this command before starting interpreter. There is probably a bug in the code where it tries to set the key when it asks you for the key if you didn't set export first.

`export OPENAI_API_KEY=<your key>`

**Comment by moniljo** [comment]
> 

This fixed it, thank you!

**Comment by joewebbxp** [comment]
Absolute legend!!!

**Comment by KillianLucas** [comment]
Hey all, my apologies for this. That exception should have contained relevant info (like that an API key was missing, if it was)— the last version would just `raise Exception("")` if it had any error with OpenAI at all.

Fixed in 0.1.3:

```
pip install --upgrade open-interpreter
```

**Comment by SwannSchilling** [comment]
Btw depending on your system you might have to change the syntax, on Windows it is
set OPENAI_API_KEY=sk-...
