### ISSUE TITLE
InvalidRequestError: The model `gpt-4` does not exist

### ISSUE THREAD

**Issue by giswqs** [KillianLucas/open-interpreter#252]
I just installed v0.1.3. Got the following error. The API key has been set properly. 

```
> interpreter -y                                                                       
> hello world
Traceback (most recent call last):
  File "/home/user/.conda/envs/geo/bin/interpreter", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/user/.conda/envs/geo/lib/python3.11/site-packages/interpreter/interpreter.py", line 131, in cli
    cli(self)
  File "/home/user/.conda/envs/geo/lib/python3.11/site-packages/interpreter/cli.py", line 207, in cli
    interpreter.chat()
  File "/home/user/.conda/envs/geo/lib/python3.11/site-packages/interpreter/interpreter.py", line 287, in chat
    self.respond()
  File "/home/user/.conda/envs/geo/lib/python3.11/site-packages/interpreter/interpreter.py", line 510, in respond
    raise Exception(error)
Exception: Traceback (most recent call last):
  File "/home/user/.conda/envs/geo/lib/python3.11/site-packages/interpreter/interpreter.py", line 495, in respond
    response = litellm.completion(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/user/.conda/envs/geo/lib/python3.11/site-packages/litellm/utils.py", line 584, in wrapper
    raise e
  File "/home/user/.conda/envs/geo/lib/python3.11/site-packages/litellm/utils.py", line 544, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.conda/envs/geo/lib/python3.11/site-packages/litellm/timeout.py", line 44, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.conda/envs/geo/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/user/.conda/envs/geo/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/user/.conda/envs/geo/lib/python3.11/site-packages/litellm/timeout.py", line 33, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.conda/envs/geo/lib/python3.11/site-packages/litellm/main.py", line 850, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/home/user/.conda/envs/geo/lib/python3.11/site-packages/litellm/utils.py", line 1960, in exception_type
    raise e
  File "/home/user/.conda/envs/geo/lib/python3.11/site-packages/litellm/utils.py", line 1606, in exception_type
    raise original_exception
  File "/home/user/.conda/envs/geo/lib/python3.11/site-packages/litellm/main.py", line 273, in completion
    raise e
  File "/home/user/.conda/envs/geo/lib/python3.11/site-packages/litellm/main.py", line 256, in completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.conda/envs/geo/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.conda/envs/geo/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/home/user/.conda/envs/geo/lib/python3.11/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.conda/envs/geo/lib/python3.11/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/home/user/.conda/envs/geo/lib/python3.11/site-packages/openai/api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.

```

**Comment by okisdev** [comment]
Please ensure that you have granted access to `GPT-4`. 

You can find more information about how to do this through your error message at https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.
