### ISSUE TITLE
Seems to have issues trying to run linux commands on windows

### ISSUE THREAD

**Issue by echogit** [KillianLucas/open-interpreter#254]
I managed to make it install but when I run it tries to run linux commands on windows:

```
Open Interpreter will require approval before running code. Use interpreter -y to bypass this.

Press CTRL-C to exit.

> my operational system is windows 10, please find out the biggest files on my C: drive. You cn use python directly.

  To find the biggest files on your C: drive, you can use the du command in the terminal. The du command stands for
  "disk usage," and it shows you how much space each file or directory takes up on your hard drive. To see the biggest
  files on your C: drive, you can run this command:



  du -ah /c/


  Would you like to run this code? (y/n)

  y


  du -ah /c/


  Traceback (most recent call last):
    File "C:\Users\echof\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\code_interpreter.py",
  line 177, in run
      code = self.add_active_line_prints(code)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\echof\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\code_interpreter.py",
  line 268, in add_active_line_prints
      return add_active_line_prints_to_python(code)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\echof\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\code_interpreter.py",
  line 430, in add_active_line_prints_to_python
      tree = ast.parse(code)
             ^^^^^^^^^^^^^^^
    File "C:\Users\echof\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 50, in parse
      return compile(source, filename, mode, flags,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<unknown>", line 1
      du -ah /c/
                ^
  SyntaxError: invalid syntax
```

**Comment by ericrallen** [comment]
Hey there!

Is this still an issue with the latest version of Open Interpreter?

**Comment by ericrallen** [comment]
I’m going to close this one as stale for now.

Please reopen it if there is more to discuss or the issue still exists with the latest version.
