### ISSUE TITLE
How to use gpt 3.5 instead of GPT -4 with open interpreter. 

### ISSUE THREAD

**Issue by maheshbasavaraj** [KillianLucas/open-interpreter#260]
trying to start the interpreter with my openai key with access to gpt 3.5 turbo .

command run : interpreter.exe 

ERROR : Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Mahesh\openInterpreter\openint\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Mahesh\openInterpreter\openint\lib\site-packages\interpreter\interpreter.py", line 131, in cli
    cli(self)
  File "C:\Mahesh\openInterpreter\openint\lib\site-packages\interpreter\cli.py", line 207, in cli
    interpreter.chat()
  File "C:\Mahesh\openInterpreter\openint\lib\site-packages\interpreter\interpreter.py", line 287, in chat
    self.respond()
  File "C:\Mahesh\openInterpreter\openint\lib\site-packages\interpreter\interpreter.py", line 510, in respond
    raise Exception(error)
Exception: Traceback (most recent call last):
  File "C:\Mahesh\openInterpreter\openint\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "C:\Mahesh\openInterpreter\openint\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Mahesh\openInterpreter\openint\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Mahesh\openInterpreter\openint\lib\site-packages\urllib3\connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "C:\Mahesh\openInterpreter\openint\lib\site-packages\urllib3\connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "C:\Mahesh\openInterpreter\openint\lib\site-packages\urllib3\connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "C:\Mahesh\openInterpreter\openint\lib\site-packages\urllib3\util\ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Mahesh\openInterpreter\openint\lib\site-packages\urllib3\util\ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Python310\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Python310\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "C:\Python310\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

Can anyone tell me why i am getting this error? i had pasted my key  but  getting this error. i am guessing since i dont have gpt -4 access, i am getting the error? pls help

**Comment by codeacme17** [comment]
hi @maheshbasavaraj , you can use `--fast` param to switch gpt-3.5-turbo. like `interpreter --fast`

**Comment by diegodp-zz** [comment]
i have changed to fast and I am still facing this problem

**Comment by Maki9009** [comment]
i changed to fast and it doesnt do anything.. it just assumes i want to install local llm

**Comment by codeacme17** [comment]
@Maki9009, I'm not entirely sure where your issue lies, because after I use the `interpreter --fast` command and enter my API key, I can access the GPT-3.5 dialogue.

![Screenshot 2023-09-12 at 19:28:51](https://github.com/KillianLucas/open-interpreter/assets/67408722/e836b94e-04fc-4489-9fca-8875de94700a)

If possible, could you provide more details about the problem you're facing and share a screenshot?
