### ISSUE TITLE
Exception encountered

### ISSUE THREAD

**Issue by FacadeCloud** [KillianLucas/open-interpreter#267]
### Describe the bug

Environment:
- Python 3.11.5
- Ventura 13.2.1

```
interpreter --use-azure

▌ Model set to GPT-4                                                          

Open Interpreter will require approval before running code. Use interpreter -y  
to bypass this.                                                                 

Press CTRL-C to exit.                                                           

> Hi
Traceback (most recent call last):
  File "/usr/local/bin/interpreter", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/interpreter/interpreter.py", line 131, in cli
    cli(self)
  File "/usr/local/lib/python3.11/site-packages/interpreter/cli.py", line 207, in cli
    interpreter.chat()
  File "/usr/local/lib/python3.11/site-packages/interpreter/interpreter.py", line 287, in chat
    self.respond()
  File "/usr/local/lib/python3.11/site-packages/interpreter/interpreter.py", line 510, in respond
    raise Exception(error)
Exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/interpreter/interpreter.py", line 475, in respond
    response = litellm.completion(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 584, in wrapper
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 544, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/timeout.py", line 44, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/site-packages/litellm/timeout.py", line 33, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 850, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 1960, in exception_type
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 1606, in exception_type
    raise original_exception
  File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 203, in completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Unrecognized request argument supplied: functions
```

### Reproduce

1. Set required environment variables about Azure OpenAI endpoint.
2. Run `interpreter --use-azure`
3. Type "Hi" and enter

### Expected behavior

Response from GPT-4 model

### Open Interpreter version

0.1.3

### Python version

3.11.5

### Operating System name and version

Ventura 13.2.1

**Comment by ishaan-jaff** [comment]
i'm the maintainer of litellm - taking a look at this. 

@FacadeCloud are you trying to use Azure OpenAI GPT-4 with function calling ? 


Trying to repro from my side

**Comment by ishaan-jaff** [comment]
@FacadeCloud are you using a version that supports function calling? 

gpt-4-0613 and gpt-3.5-turbo-0613 

https://openai.com/blog/function-calling-and-other-api-updates

**Comment by FacadeCloud** [comment]
> @FacadeCloud are you using a version that supports function calling?
> 
> gpt-4-0613 and gpt-3.5-turbo-0613
> 
> https://openai.com/blog/function-calling-and-other-api-updates

Hi ishaan, it's 2023-07-01-preview, something even newer. Is there any breaking change in the API?

**Comment by ericrallen** [comment]
Hey there!

Is this still an issue with the latest version of Open Interpreter?

**Comment by ericrallen** [comment]
I’m going to close this one as stale for now.

Please reopen it if there is more to discuss or the issue still exists with the latest version.
