### ISSUE TITLE
GPT-4 Not Working API

### ISSUE THREAD

**Issue by sirbastiano** [KillianLucas/open-interpreter#275]
### Describe the bug

Selecting GPT-4 thraws this error on my mac:

Traceback (most recent call last):
  File "/Users/robertodelprete/opt/anaconda3/envs/interpreter/bin/interpreter", line 8, in <module>
    sys.exit(cli())
  File "/Users/robertodelprete/opt/anaconda3/envs/interpreter/lib/python3.10/site-packages/interpreter/interpreter.py", line 131, in cli
    cli(self)
  File "/Users/robertodelprete/opt/anaconda3/envs/interpreter/lib/python3.10/site-packages/interpreter/cli.py", line 207, in cli
    interpreter.chat()
  File "/Users/robertodelprete/opt/anaconda3/envs/interpreter/lib/python3.10/site-packages/interpreter/interpreter.py", line 287, in chat
    self.respond()
  File "/Users/robertodelprete/opt/anaconda3/envs/interpreter/lib/python3.10/site-packages/interpreter/interpreter.py", line 510, in respond
    raise Exception(error)
Exception: Traceback (most recent call last):
  File "/Users/robertodelprete/opt/anaconda3/envs/interpreter/lib/python3.10/site-packages/interpreter/interpreter.py", line 495, in respond
    response = litellm.completion(
  File "/Users/robertodelprete/opt/anaconda3/envs/interpreter/lib/python3.10/site-packages/litellm/utils.py", line 584, in wrapper
    raise e
  File "/Users/robertodelprete/opt/anaconda3/envs/interpreter/lib/python3.10/site-packages/litellm/utils.py", line 544, in wrapper
    result = original_function(*args, **kwargs)
  File "/Users/robertodelprete/opt/anaconda3/envs/interpreter/lib/python3.10/site-packages/litellm/timeout.py", line 44, in wrapper
    result = future.result(timeout=local_timeout_duration)
  File "/Users/robertodelprete/opt/anaconda3/envs/interpreter/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/Users/robertodelprete/opt/anaconda3/envs/interpreter/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/robertodelprete/opt/anaconda3/envs/interpreter/lib/python3.10/site-packages/litellm/timeout.py", line 33, in async_func
    return func(*args, **kwargs)
  File "/Users/robertodelprete/opt/anaconda3/envs/interpreter/lib/python3.10/site-packages/litellm/main.py", line 850, in completion
    raise exception_type(
  File "/Users/robertodelprete/opt/anaconda3/envs/interpreter/lib/python3.10/site-packages/litellm/utils.py", line 1960, in exception_type
    raise e
  File "/Users/robertodelprete/opt/anaconda3/envs/interpreter/lib/python3.10/site-packages/litellm/utils.py", line 1606, in exception_type
    raise original_exception
  File "/Users/robertodelprete/opt/anaconda3/envs/interpreter/lib/python3.10/site-packages/litellm/main.py", line 273, in completion
    raise e
  File "/Users/robertodelprete/opt/anaconda3/envs/interpreter/lib/python3.10/site-packages/litellm/main.py", line 256, in completion
    response = openai.ChatCompletion.create(
  File "/Users/robertodelprete/opt/anaconda3/envs/interpreter/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/Users/robertodelprete/opt/anaconda3/envs/interpreter/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/Users/robertodelprete/opt/anaconda3/envs/interpreter/lib/python3.10/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/Users/robertodelprete/opt/anaconda3/envs/interpreter/lib/python3.10/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/Users/robertodelprete/opt/anaconda3/envs/interpreter/lib/python3.10/site-packages/openai/api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.

### Reproduce

1. Install
2. Run gpt-4
3. insert API key
4. try 

### Expected behavior

Should answer correcyly

### Open Interpreter version

0.1.3

### Python version

3.10

### Operating System name and version

macOS13

**Comment by sirbastiano** [comment]
Yes, I inserted my openAI key and I had that error

**Comment by JavierLopatin** [comment]
Hi, I am facing a similar error and have access to the GPT4 model (ChatGPT Plus user). Thanks for your help.

**Comment by krrishdholakia** [comment]
Closing the issue as this appears to be an openai access issue, not litellm. But please re-open if you're able to get it working with the openai python sdk but not litellm.

**Comment by JavierLopatin** [comment]
Hi @krrishdholakia. You are right! I do have that problem: I have a Premium account at https://chat.openai.com/, but that account is not reflected in the https://platform.openai.com/ webpage (i.e., zero payment and access here, only gpt-3.5 access on the playground).

Do you know a way of unifying the accounts? 

Cheers, J

**Comment by alexaldearroyo** [comment]
Exactly same problem on my mac. Provided my API, ChatGPT-4 user.

**Comment by wxtt522** [comment]
My test is that neither 3.5 nor 4 can be executed. it's always hallucinate that the code has been executed, but in fact it has not been executed.

**Comment by CORALC123** [comment]
I have the exact same issue as per OP's issue, but I am also able to see that I have access to GPT-4 in Playground, so I do have full access and have a funded account (playground.openai.com).
Flow:
% typed <<interpreter>>

Welcome to Open Interpreter.                                                    

────────────────────────────────────────────────────────────────────────────────

▌ OpenAI API key not found                                                    

To use GPT-4 (recommended) please provide an OpenAI API key.                    

To use Code-Llama (free but less capable) press enter.                          

────────────────────────────────────────────────────────────────────────────────

OpenAI API key: <<Key is pasted in / entered>>

Tip: To save this key for later, run export OPENAI_API_KEY=your_api_key on      
Mac/Linux or setx OPENAI_API_KEY your_api_key on Windows.                       

────────────────────────────────────────────────────────────────────────────────

▌ Model set to GPT-4                                                          

Open Interpreter will require approval before running code. Use interpreter -y  
to bypass this.                                                                 

Press CTRL-C to exit. 

Typed <<interpreter -y>>

Traceback in full that then ends in the following gpt4 error:
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openai/util.py", line 188, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.

It just looks like it does not store the key on macOS, even after exporting as per instruction. Anyone with ideas?
(MacBook Pro M2 Max - macOS Ventura 13.5.2 (22G91))

**Comment by 0xcha05** [comment]
create a new openai api key

**Comment by CORALC123** [comment]
Hi @Oxcha05 we have attempted to use several actually as we assumed the original keys or tokens may have gone stale or expired. Generated new keys in Playground, used them and still see the above failure.

**Comment by Vaillus** [comment]
Hello,
I have a problem here.
I recently switched from a chatgt plus subscription to that openai api.
On another app, I have no trouble connecting to GPT4. But here, the default is apparently GPT-3.5-turbo even though it tells me initially that it is running on GPT4.
When I try to switch to GPT4, it says: 
```
> interpreter.model = "gpt-4"                                                                                                                                                                                                                                                                         
  I'm sorry, but "gpt-4" is not a valid model. The available models are "gpt-3.5-turbo" and "text-davinci-003". Please specify one of these.   
```

**Comment by jordanbtucker** [comment]
@Vaillus Unfortunately, we don't have any control over how the GPT model responds. If it doesn't think it's GPT-4 (even though it is) then I'm not sure we can solve that.

Also, `interpreter.model = "gpt-4"` isn't a command you can run within interpreter, so you're just getting a response back from GPT when you type that.

**Comment by jordanbtucker** [comment]
Please try running the following command. If that doesn't fix the API error, then it may be on OpenAI's side and you'll need to contact them.

```
pip install litellm==0.1.590
```

**Comment by grexzen** [comment]
> Please try running the following command. If that doesn't fix the API error, then it may be on OpenAI's side and you'll need to contact them.
> 
> ```
> pip install litellm==0.1.590
> ```

Hi Jordan - is there a way to use gpt4-32k? I don't see how to change that in the console. Thanks!

**Comment by ericrallen** [comment]
@grexzen You should be able to use the `--model` argument, the `model` parameter in your `config.yaml`, or the `interpreter.model` property if you’re using Python and not the Terminal Interface.

**Comment by ericrallen** [comment]
I’m going to close this one as resolved as it seems to be related to the [known challenges with accessing GPT-4 via the API](https://github.com/KillianLucas/open-interpreter/issues/164#issuecomment-1711992453).

Please reopen this issue if I’m wrong or you think there is more to dig into here.
