### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by skywalk163** [KillianLucas/open-interpreter#277]
### Describe the bug

Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/bin/interpreter", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/interpreter/interpreter.py", line 131, in cli
    cli(self)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/interpreter/cli.py", line 207, in cli
    interpreter.chat()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/interpreter/interpreter.py", line 291, in chat
    self.respond()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/interpreter/interpreter.py", line 598, in respond
    for chunk in response:
TypeError: 'NoneType' object is not iterable

### Reproduce

after change version to 0.1.3 , got this error

### Expected behavior

response shouldn't be  'NoneType' 

### Open Interpreter version

0.1.3

### Python version

3.10.10

### Operating System name and version

Linux jupyter-141218-6730729 5.4.0-104-generic #118-Ubuntu

**Comment by PhilRandWu** [comment]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "Programs\Python\Python311\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "Programs\Python\Python311\Lib\site-packages\interpreter\interpreter.py", line 131, in cli
    cli(self)
  File "Programs\Python\Python311\Lib\site-packages\interpreter\cli.py", line 207, in cli
    interpreter.chat()
  File "Programs\Python\Python311\Lib\site-packages\interpreter\interpreter.py", line 412, in chat
    self.respond()
  File "Programs\Python\Python311\Lib\site-packages\interpreter\interpreter.py", line 705, in respond
    response = self.llama_instance(
               ^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
————————————————————————————————————————————————————————

I also ran into this issue

**Comment by jordanbtucker** [comment]
Does this happen immediate after you start Open Interpreter, or is this during a conversation with the AI? If it's during a conversation, can you please provide enough of the conversation to see what triggered the error?

**Comment by MayueCif** [comment]
> Does this happen immediate after you start Open Interpreter, or is this during a conversation with the AI? If it's during a conversation, can you please provide enough of the conversation to see what triggered the error?

happen this during a conversation with the AI

**Comment by Dix01** [comment]
im also getting the same error.. happens right after i choose the downloaded model, it loads the model then starts repeating this :

using windows 11, rtx 2080, 7b medium sized llama model

![Screenshot 2023-09-16 163408](https://github.com/KillianLucas/open-interpreter/assets/125991063/3c5e6baa-f9bc-4493-9a10-72756d44e435)
![Screenshot 2023-09-16 163418](https://github.com/KillianLucas/open-interpreter/assets/125991063/3fcdbacb-95fc-45e1-8aaa-805291b2bbeb)

**Comment by Ionaut** [comment]
> im also getting the same error.. happens right after i choose the downloaded model, it loads the model then starts repeating this :
> 
> using windows 11, rtx 2080, 7b medium sized llama model
> 
> ![Screenshot 2023-09-16 163408](https://user-images.githubusercontent.com/125991063/268450743-3c5e6baa-f9bc-4493-9a10-72756d44e435.png) ![Screenshot 2023-09-16 163418](https://user-images.githubusercontent.com/125991063/268450749-3fcdbacb-95fc-45e1-8aaa-805291b2bbeb.png)

I'm getting the exact same thing as Dix01.  I'm trying the 13B medium model but the result is the same. Win 11 RTX3060 12GB VRAM.

**Comment by Ionaut** [comment]
This Code seems to be the culprit:
![image](https://github.com/KillianLucas/open-interpreter/assets/8879570/58cacbfb-277d-467c-8d5d-037432332c3e)
Causing:
![image](https://github.com/KillianLucas/open-interpreter/assets/8879570/56ab8b69-e58f-4ff2-8b8d-b1fa88120b97)

**Comment by maxpetrusenko** [comment]
have the same issue 0.1.15 when trying to run "interpreter" in command line  after successful install (m2, python 3.11 conda env)

**Comment by ericrallen** [comment]
Hey there, @maxpetrusenko!

Could you share some more info about your experience? What model were you using? What was your prompt?

A screenshot or text dump of the error output would be helpful, especially because the error messages in this thread appear to come from pyreadline3 which should only be loaded on Windows.

**Comment by maxpetrusenko** [comment]
@ericrallen ,

```
(base) MacBook-Pro-2:~ maxpetrusenko$ interpreter
Traceback (most recent call last):
  File "/Users/maxpetrusenko/miniforge3/bin/interpreter", line 5, in <module>
    from interpreter import cli
  File "/Users/maxpetrusenko/miniforge3/lib/python3.10/site-packages/interpreter/__init__.py", line 8, in <module>
    sys.modules["interpreter"] = Interpreter()
  File "/Users/maxpetrusenko/miniforge3/lib/python3.10/site-packages/interpreter/core/core.py", line 60, in __init__
    self.extend_config(self.config_file)
  File "/Users/maxpetrusenko/miniforge3/lib/python3.10/site-packages/interpreter/core/core.py", line 79, in extend_config
    self.__dict__.update(config)
TypeError: 'NoneType' object is not iterable
```

**Comment by Notnaton** [comment]
@maxpetrusenko 
please post your config.yaml
`interpreter --config`

**Comment by maxpetrusenko** [comment]
@Notnaton i see the same error

```
maxpetrusenko$ interpreter --config
Traceback (most recent call last):
  File "/Users/maxpetrusenko/miniforge3/bin/interpreter", line 5, in <module>
    from interpreter import cli
  File "/Users/maxpetrusenko/miniforge3/lib/python3.10/site-packages/interpreter/__init__.py", line 8, in <module>
    sys.modules["interpreter"] = Interpreter()
  File "/Users/maxpetrusenko/miniforge3/lib/python3.10/site-packages/interpreter/core/core.py", line 60, in __init__
    self.extend_config(self.config_file)
  File "/Users/maxpetrusenko/miniforge3/lib/python3.10/site-packages/interpreter/core/core.py", line 79, in extend_config
    self.__dict__.update(config)
TypeError: 'NoneType' object is not iterable
```

**Comment by Notnaton** [comment]
@maxpetrusenko you need to delete your config.yaml file and let it generate again.
go to `C:\Users\USERNAME\AppData\Local\Open Interpreter\Open Interpreter` and delete it
