### ISSUE TITLE
llama cpp isntall error

### ISSUE THREAD

**Issue by pyoneerC** [KillianLucas/open-interpreter#289]
### Describe the bug

[?] Local LLM interface package not found. Install `llama-cpp-python`? (Y/n): Y

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\__main__.py", line 22, in <module>
    from pip._internal.cli.main import main as _main
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_internal\cli\main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_internal\cli\main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_internal\build_env.py", line 19, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_internal\cli\spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_internal\utils\logging.py", line 29, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_internal\utils\misc.py", line 37, in <module>
    from pip._vendor.tenacity import retry, stop_after_delay, wait_fixed
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 548, in <module>
    from pip._vendor.tenacity._asyncio import AsyncRetrying  # noqa:E402,I100
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\tenacity\_asyncio.py", line 21, in <module>
    from asyncio import sleep
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\asyncio\__init__.py", line 42, in <module>
    from .windows_events import *
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 8, in <module>
    import _overlapped
OSError: [WinError 10106] The requested service provider could not be loaded or initialized
Error during installation with OpenBLAS: Command
'['C:\\Users\\Usuario\\AppData\\Local\\Programs\\Python\\Python311\\python.exe', '-m', 'pip', 'install',
'llama-cpp-python']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\get_hf_llm.py", line 141, in get_hf_llm
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\interpreter.py", line 203, in chat
    self.llama_instance = get_hf_llm(self.model, self.debug_mode, self.context_window)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\get_hf_llm.py", line 200, in get_hf_llm
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'

▌ Failed to install TheBloke/CodeLlama-13B-Instruct-GGUF

### Reproduce

s

### Expected behavior

s

### Screenshots

s

### Open Interpreter version

last

### Python version

last

### Operating System name and version

w11

**Comment by jordanbtucker** [comment]
Please see https://github.com/KillianLucas/open-interpreter/blob/main/docs/WINDOWS.md

**Comment by jackfood** [comment]
You may refer to the documentation on installing llama cpp, which requires cmake from visual studio community.

**Comment by animathakurr** [comment]
is llma cpp working fine on your computer? I installed the 7b version just to check and it is just not working rest all versions take soo much RAM . What should i do ? or in google collab how to install llma ?

**Comment by ericrallen** [comment]
Hey there, folks!

I'm going to close this one as stale for now, but please feel encouraged to reopen it if you still experience the issue in the latest version of Open Interpreter.
