### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by bowencool** [KillianLucas/open-interpreter#293]
### Describe the bug

IndexError: list index out of range

### Reproduce

```
interpreter --fast

▌ Model set to GPT-3.5-TURBO

Open Interpreter will require approval before running code. Use interpreter -y to bypass this.

Press CTRL-C to exit.

> set my system to light mode
Traceback (most recent call last):
  File "/opt/homebrew/bin/interpreter", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/interpreter.py", line 131, in cli
    cli(self)
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/cli.py", line 207, in cli
    interpreter.chat()
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/interpreter.py", line 287, in chat
    self.respond()
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/interpreter.py", line 606, in respond
    delta = chunk["choices"][0]["delta"]
            ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

### Expected behavior

no errors.

### Open Interpreter version

0.1.3

### Python version

3.11.5

### Operating System name and version

macos 13.5.2

**Comment by s88101088** [comment]
face same issue with it , i already export my API .but still not working .anyone could help ?

**Comment by ericrallen** [comment]
Is this still an issue with the latest version of Open Interpreter?

**Comment by ericrallen** [comment]
I’m going to close this one as stale for now.

Please reopen it if there is more to discuss or the issue still exists with the latest version.
