### ISSUE TITLE
Can not run on MacOS v0.1.3

### ISSUE THREAD

**Issue by lolieatapple** [KillianLucas/open-interpreter#313]
### Describe the bug

$ interpreter
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/interpreter", line 5, in <module>
    from interpreter import cli
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/interpreter/__init__.py", line 1, in <module>
    from .interpreter import Interpreter
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/interpreter/interpreter.py", line 35, in <module>
    import litellm
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/litellm/__init__.py", line 224, in <module>
    from .utils import (
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/litellm/utils.py", line 11, in <module>
    encoding = tiktoken.get_encoding("cl100k_base")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tiktoken/registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tiktoken_ext/openai_public.py", line 64, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tiktoken/load.py", line 117, in load_tiktoken_bpe
    return {
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tiktoken/load.py", line 119, in <dictcomp>
    for token, rank in (line.split() for line in contents.splitlines() if line)
ValueError: not enough values to unpack (expected 2, got 1)

### Reproduce

$ interpreter

### Expected behavior

success to run.

### Screenshots

<img width="1020" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/54833180/5725ffcb-b55c-4611-b32a-085262004597">

### Open Interpreter version

0.1.3

### Python version

Python 3.10.4

### Operating System name and version

macOS 13.5.2

**Comment by stromal** [comment]
Same

**Comment by lolieatapple** [comment]
I found a work around solution:
vi /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tiktoken/load.py

use this function to instead of the old load_tiktoken_bpe function in the end of the file:
```
def load_tiktoken_bpe(tiktoken_bpe_file: str) -> dict[bytes, int]:
    # NB: do not add caching to this function
    contents = read_file_cached(tiktoken_bpe_file)
    
    bpe_data = {}
    for line in contents.splitlines():
        if line:
            tokens = line.split()
            if len(tokens) != 2:
                print(f"Warning: Unexpected format in line: '{line}'. Skipping.")
                continue
            
            token, rank = tokens
            try:
                decoded_token = base64.b64decode(token)
                rank_int = int(rank)
                bpe_data[decoded_token] = rank_int
            except Exception as e:
                print(f"Warning: Error processing line: '{line}'. Error: {e}. Skipping.")

    return bpe_data

```
