### ISSUE TITLE
Using Azure Openai, after input get the error openai.error.InvalidRequestError: Unrecognized request argument supplied: functions

### ISSUE THREAD

**Issue by hellangleZ** [KillianLucas/open-interpreter#331]
### Describe the bug

Press CTRL-C to exit.                                                                                             

> hello
Traceback (most recent call last):
  File "/aml/conda/bin/interpreter", line 8, in <module>
    sys.exit(cli())
  File "/aml/conda/lib/python3.10/site-packages/interpreter/interpreter.py", line 131, in cli
    cli(self)
  File "/aml/conda/lib/python3.10/site-packages/interpreter/cli.py", line 207, in cli
    interpreter.chat()
  File "/aml/conda/lib/python3.10/site-packages/interpreter/interpreter.py", line 287, in chat
    self.respond()
  File "/aml/conda/lib/python3.10/site-packages/interpreter/interpreter.py", line 510, in respond
    raise Exception(error)
Exception: Traceback (most recent call last):
  File "/aml/conda/lib/python3.10/site-packages/interpreter/interpreter.py", line 475, in respond
    response = litellm.completion(
  File "/aml/conda/lib/python3.10/site-packages/litellm/utils.py", line 584, in wrapper
    raise e
  File "/aml/conda/lib/python3.10/site-packages/litellm/utils.py", line 544, in wrapper
    result = original_function(*args, **kwargs)
  File "/aml/conda/lib/python3.10/site-packages/litellm/timeout.py", line 44, in wrapper
    result = future.result(timeout=local_timeout_duration)
  File "/aml/conda/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/aml/conda/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/aml/conda/lib/python3.10/site-packages/litellm/timeout.py", line 33, in async_func
    return func(*args, **kwargs)
  File "/aml/conda/lib/python3.10/site-packages/litellm/main.py", line 865, in completion
    raise exception_type(
  File "/aml/conda/lib/python3.10/site-packages/litellm/utils.py", line 2074, in exception_type
    raise e
  File "/aml/conda/lib/python3.10/site-packages/litellm/utils.py", line 1667, in exception_type
    raise original_exception
  File "/aml/conda/lib/python3.10/site-packages/litellm/main.py", line 207, in completion
    response = openai.ChatCompletion.create(
  File "/aml/conda/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/aml/conda/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/aml/conda/lib/python3.10/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/aml/conda/lib/python3.10/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/aml/conda/lib/python3.10/site-packages/openai/api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Unrecognized request argument supplied: functions

### Reproduce

![image](https://github.com/KillianLucas/open-interpreter/assets/15274284/20391b10-0f9d-4a6c-aedc-1d03b73c39c3)

### Expected behavior

Should be use like document said to work

### Screenshots

![image](https://github.com/KillianLucas/open-interpreter/assets/15274284/bf8152dd-fbb1-4e2f-8706-81f3f9ef27b1)

### Open Interpreter version

0.1.3

### Python version

3.10.9

### Operating System name and version

Ubuntu 22.04

**Comment by zhechenghu** [comment]
What's your api version? You should use 2023-07-01-preview or a newer version for the function feature:

<img width="887" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/100691508/d4b8bee7-737f-4418-b432-62cfad19d84b">

**Comment by hellangleZ** [comment]
> What's your api version? You should use 2023-07-01-preview or a newer version for the function feature:
> 
> <img alt="image" width="887" src="https://user-images.githubusercontent.com/100691508/267836209-d4b8bee7-737f-4418-b432-62cfad19d84b.png">
Hi, you are right, I fixed this issue

**Comment by gltanaka** [comment]
Is there a way to not use this? Some Azure models don't support this. Otherwise, we have to choose between the more accurate March model vs. the less accurate but function supporting July model.

**Comment by ian-reay** [comment]
Can I confirm which combination of settings work? 

I'm using
* AZURE_API_VERSION=2023-07-01-preview
* gpt-35-turbo version 0613

And when I use this I get this error
* openai.error.InvalidRequestError: 'content' is a required property - 'messages.2' 

I've also tried
* gpt-35-turbo version 0301

Is there a known combination that works?

**Comment by ericrallen** [comment]
Hey there, folks!

I’m going to close this one as stale for now.

Feel feee to reopen if it’s still as issue with the latest version of Open Interpreter, but keep in mind that code execution requires a model that is capable of calling functions, and Open Interpreter is designed for function calling.
