### ISSUE TITLE
Falcon fails to run commands

### ISSUE THREAD

**Issue by sebas-benme** [KillianLucas/open-interpreter#351]
### Describe the bug

Running 40B falcon and just asked it to read the files in directory. Here's the error I get:
```
Traceback (most recent call last):
  File "/home/sebas/open_interpreter/bin/interpreter", line 8, in <module>
    sys.exit(cli())
  File "/home/sebas/open_interpreter/lib/python3.10/site-packages/interpreter/interpreter.py", line 131, in cli
    cli(self)
  File "/home/sebas/open_interpreter/lib/python3.10/site-packages/interpreter/cli.py", line 207, in cli
    interpreter.chat()
  File "/home/sebas/open_interpreter/lib/python3.10/site-packages/interpreter/interpreter.py", line 287, in chat
    self.respond()
  File "/home/sebas/open_interpreter/lib/python3.10/site-packages/interpreter/interpreter.py", line 798, in respond
    code_interpreter.run()
  File "/home/sebas/open_interpreter/lib/python3.10/site-packages/interpreter/code_interpreter.py", line 147, in run
    open_subrocess = language_map[self.language].get("open_subrocess", True)
KeyError: 'ls -l /home/sebas'
```

### Reproduce

1. Run interpreter: `interpreter --y --falcon`
2. Select `40B`
3. Select `Large`
4. Use GPU: `Yes` (tried both Yes and No)
5. Write prompt: `read the files in directory and decide what they're about`

### Expected behavior

The model runs the command without errors

### Open Interpreter version

0.1.3

### Python version

3.10.12

### Operating System name and version

Ubuntu 22.04 (GCP VM)

**Comment by jakegibbonsdev** [comment]
Similar error when trying to run 40B falcon with 0.1.4:

Traceback (most recent call last):
  File "/home/user/openinterpreter/bin/interpreter", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/user/openinterpreter/lib64/python3.11/site-packages/interpreter/interpreter.py", line 131, in cli
    cli(self)
  File "/home/user/openinterpreter/lib64/python3.11/site-packages/interpreter/cli.py", line 207, in cli
    interpreter.chat()
  File "/home/user/openinterpreter/lib64/python3.11/site-packages/interpreter/interpreter.py", line 412, in chat
    self.respond()
  File "/home/user/openinterpreter/lib64/python3.11/site-packages/interpreter/interpreter.py", line 924, in respond
    code_interpreter.run()
  File "/home/user/openinterpreter/lib64/python3.11/site-packages/interpreter/code_interpreter.py", line 153, in run
    open_subprocess = language_map[self.language].get("open_subprocess", True)
                      ~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'ls'

Reproduce
    Run interpreter: interpreter --y --falcon
    Select 40B
    Select Large
    Use GPU: Yes (tried both Yes and No)
    Write prompt: list files

Expected behaviour
The model runs the command without errors

Screenshots
None

Open Interpreter version
0.1.4

Python version
3.11.5

Operating System name and version
Fedora Core 38 with kernel 6.4.12-200.fc38.x86_64
