### ISSUE TITLE
OI exits out when pip installing beautifulsoup

### ISSUE THREAD

**Issue by markredito** [KillianLucas/open-interpreter#368]
### Describe the bug

I prompted OI to do some research through the internet. It tried to install beautifulsoup via `pip install beautifulsoup4`. Upon confirmation, the OI interface exited out.

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Mark\anaconda3\envs\oi\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\Mark\anaconda3\envs\oi\Lib\site-packages\interpreter\interpreter.py", line 131, in cli
    cli(self)
  File "C:\Users\Mark\anaconda3\envs\oi\Lib\site-packages\interpreter\cli.py", line 207, in cli
    interpreter.chat()
  File "C:\Users\Mark\anaconda3\envs\oi\Lib\site-packages\interpreter\interpreter.py", line 412, in chat
    self.respond()
  File "C:\Users\Mark\anaconda3\envs\oi\Lib\site-packages\interpreter\interpreter.py", line 924, in respond
    code_interpreter.run()
  File "C:\Users\Mark\anaconda3\envs\oi\Lib\site-packages\interpreter\code_interpreter.py", line 201, in run
    code = wrap_in_try_except(code)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mark\anaconda3\envs\oi\Lib\site-packages\interpreter\code_interpreter.py", line 464, in wrap_in_try_except
    parsed_code = ast.parse(code)
                  ^^^^^^^^^^^^^^^
  File "C:\Users\Mark\anaconda3\envs\oi\Lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 2
    pip install beautifulsoup4
        ^^^^^^^
SyntaxError: invalid syntax
```

### Reproduce

On a windows machine, running anaconda venv, python 3.11:
1. prompt "do research on this individual (name)"
2. oi will ask for confirmation to run code, enter "y"
3. oi prompts user that beautifulsoup is not installed and asks for confirmation to install.
4. user confirms "y"

### Expected behavior

beautifulsoup installs without any problems and OI continues with research.

### Open Interpreter version

0.1.4

### Python version

3.11.4

### Operating System name and version

Windows 10

**Comment by jordanbtucker** [comment]
Looks like it tried to run it as Python code instead of a terminal command.

**Comment by markredito** [comment]
ah. maybe i should prompt it to run a bash command instead?

**Comment by dorianherle** [comment]
Happened to me as weel. Every time it wants to install it shuts down the interpreter.

**Comment by ericrallen** [comment]
Hey there, @markredito and @dorianherle!

Can you confirm if this is still an issue with the latest version of Open Interpreter?

**Comment by markredito** [comment]
> Hey there, @markredito and @dorianherle!
> 
> 
> 
> Can you confirm if this is still an issue with the latest version of Open Interpreter?

It seems to be fixed in the newst ver. I'll go and test it some more and will open another issue if i encounter errors again. Thank you!
