### ISSUE TITLE
🎉 Access Claude-2/Llama-70b/etc. [community-supported API]

### ISSUE THREAD

**Issue by krrishdholakia** [KillianLucas/open-interpreter#387]
### Is your feature request related to a problem? Please describe.

Hi, 

I noticed a few people trying to access new / run larger LLMs than their computers could support: 
* claude-2
* Llama-2-70b
* CodeLlama
etc. 

So I hosted a proxy API to give people access to these models (~20 hosted models) through my keys.

Tutorial for how to add to openinterpreter: https://docs.litellm.ai/docs/proxy_api

🚨 UPDATED CODE:
Note: You will need to clone and modify the Github repo, until [this PR is merged.](https://github.com/KillianLucas/open-interpreter/pull/288)
```
git clone https://github.com/krrishdholakia/open-interpreter-litellm-fork
```

```
poetry build 

# call gpt-4 - always add 'litellm_proxy/' in front of the model name
poetry run interpreter --model litellm_proxy/gpt-4

# call llama-70b - always add 'litellm_proxy/' in front of the model name
poetry run interpreter --model litellm_proxy/togethercomputer/llama-2-70b-chat

# call claude-2 - always add 'litellm_proxy/' in front of the model name
poetry run interpreter --model litellm_proxy/claude-2
```

**Comment by jackfood** [comment]
do i need llama-70b api? Is it free? I saw the instructions and still does not know which line to add. Please guide me.

**Comment by krrishdholakia** [comment]
* yes, it's free

>  still does not know which line to add

This should be easier. I'll see if i can make a PR to help simplify this. @jackfood

**Comment by jackfood** [comment]
Thanks @krrishdholakia.

**Comment by haseeb-heaven** [comment]
```python
os.environ["OPENAI_API_KEY"] = "openinterpreter-key"
litellm.api_base = "https://proxy.litellm.ai"
```
What is value of `openinterpreter-key` key here ? where do we get this key from

**Comment by krrishdholakia** [comment]
Update @jackfood @haseeb-heaven, open-interpreter kept thinking our model names were local models. So had to make a fork. Here's the simplified code: 

```
git clone https://github.com/krrishdholakia/open-interpreter-litellm-fork
```

```
poetry build 

# call gpt-4 - always add 'litellm_proxy/' in front of the model name
poetry run interpreter --model litellm_proxy/gpt-4

# call llama-70b - always add 'litellm_proxy/' in front of the model name
poetry run interpreter --model litellm_proxy/togethercomputer/llama-2-70b-chat

# call claude-2 - always add 'litellm_proxy/' in front of the model name
poetry run interpreter --model litellm_proxy/claude-2
```

**Comment by lisanhu** [comment]
@krrishdholakia Thanks for the work! I'm still not sure how to run it. I wish to try the WizardLM/WizardCoder-Python-34B-V1.0 model on the documentation page, so this is what I did:
```
$ poetry build 
Building open-interpreter (0.1.3)
  - Building sdist
  - Built open_interpreter-0.1.3.tar.gz
  - Building wheel
  - Built open_interpreter-0.1.3-py3-none-any.whl
$ poetry run interpreter --model litellm_proxy/togethercomputer/llama-2-70b-chat
Warning: 'interpreter' is an entry point defined in pyproject.toml, but it's not installed as a script. You may get improper `sys.argv[0]`.

The support to run uninstalled scripts will be removed in a future release.

Run `poetry install` to resolve and get rid of this message.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lisanhu/mine/workspace/LLM/open-interpreter-litellm-fork/interpreter/interpreter.py", line 135, in cli
    cli(self)
  File "/home/lisanhu/mine/workspace/LLM/open-interpreter-litellm-fork/interpreter/cli.py", line 210, in cli
    interpreter.chat()
  File "/home/lisanhu/mine/workspace/LLM/open-interpreter-litellm-fork/interpreter/interpreter.py", line 196, in chat
    self.verify_api_key()
  File "/home/lisanhu/mine/workspace/LLM/open-interpreter-litellm-fork/interpreter/interpreter.py", line 394, in verify_api_key
    self._print_welcome_message()
  File "/home/lisanhu/mine/workspace/LLM/open-interpreter-litellm-fork/interpreter/interpreter.py", line 844, in _print_welcome_message
    current_version = pkg_resources.get_distribution("open-interpreter").version
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lisanhu/anaconda3/envs/open-interpreter/lib/python3.11/site-packages/pkg_resources/__init__.py", line 528, in get_distribution
    dist = get_provider(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/home/lisanhu/anaconda3/envs/open-interpreter/lib/python3.11/site-packages/pkg_resources/__init__.py", line 400, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lisanhu/anaconda3/envs/open-interpreter/lib/python3.11/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lisanhu/anaconda3/envs/open-interpreter/lib/python3.11/site-packages/pkg_resources/__init__.py", line 829, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/lisanhu/anaconda3/envs/open-interpreter/lib/python3.11/site-packages/pkg_resources/__init__.py", line 870, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'open-interpreter' distribution was not found and is required by the application
$ poetry install
Installing dependencies from lock file
Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.

Package operations: 3 installs, 3 updates, 0 removals

  • Downgrading smmap (5.0.1 -> 5.0.0)
  • Updating setuptools (68.0.0 -> 68.2.2)
  • Installing iniconfig (2.0.0)
  • Installing pluggy (1.3.0)
  • Installing pytest (7.4.2)
  • Downgrading rich (13.5.3 -> 13.5.2)

Installing the current project: open-interpreter (0.1.3)
$ poetry run interpreter --model litellm_proxy/WizardLM/WizardCoder-Python-34B-V1.0
A new version is available. Please run 'pip install --upgrade open-interpreter'.

 Hello, Welcome to ⬤ Open Interpreter. (v0.1.3)

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

▌ LLM API key not found                                                                                                                                                                                             

To use GPT-4 (recommended) please provide an OpenAI API key.                                                                                                                                                          

To use Claude-2 please provide an Anthropic API key.                                                                                                                                                                  

To use Code-Llama (free but less capable) press enter.                                                                                                                                                                

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

LLM API [OpenAI/Anthropic] key: 

▌ Switching to Code-Llama...                                                                                                                                                                                        

Tip: Run interpreter --local to automatically use Code-Llama.                                                                                                                                                         

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Open Interpreter will use Code Llama for local execution. Use your arrow keys to set up the model.                                                                                                                    

[?] Parameter count (smaller is faster, larger is more capable): 34B
   7B
   13B
 > 34B

[?] Quality (smaller is faster, larger is more capable): Small | Size: 13.2 GB, Estimated RAM usage: 15.7 GB
 > Small | Size: 13.2 GB, Estimated RAM usage: 15.7 GB
   Medium | Size: 18.8 GB, Estimated RAM usage: 21.3 GB
   Large | Size: 33.4 GB, Estimated RAM usage: 35.9 GB
   See More

[?] Use GPU? (Large models might crash on GPU, but will run more quickly) (Y/n): n

Model found at /home/lisanhu/.local/share/Open Interpreter/models/codellama-34b-instruct.Q2_K.gguf                                                                                                                    

▌ Model set to TheBloke/CodeLlama-34B-Instruct-GGUF                                                                                                                                                                 

Open Interpreter will require approval before running code. Use interpreter -y to bypass this.                                                                                                                        

Press CTRL-C to exit.                                                                                                                                                                                                 

> 
```

to summarize:
```
$ poetry build
$ poetry install
$ poetry run interpreter --model litellm_proxy/WizardLM/WizardCoder-Python-34B-V1.0
```
And it seems to use the local codellama-34b model

What I did wrong? Thanks a lot!

**Comment by jackfood** [comment]
Just a thought, It would be great if I can use this with huggingface chat (API) as it is free. I myself see some idea and created a half-codeinterpreter hugging face in GitHub using got 3.5, but far from what this open-interpreter can achieve.

**Comment by haseeb-heaven** [comment]
> Just a thought, It would be great if I can use this with huggingface chat (API) as it is free. I myself see some idea and created a (jackfood/CodeInterpreter_huggingchat-free-api) in GitHub, using huggingface chat API. Just login email and password in .env. It currently runs python only, but far from what this open-interpreter can achieve. I hope one day, I can run this with huggingface chat.

We can just use Custom OpenAI base it can be free as well it would be better than using Hugging face directly.

**Comment by krrishdholakia** [comment]
@lisanhu this is with the forked open-interpreter? 


you need to add a random key here - just input `hi`
<img width="395" alt="Screenshot 2023-09-18 at 8 59 55 AM" src="https://github.com/KillianLucas/open-interpreter/assets/17561003/1b94854e-495f-40b9-9880-2bed8c253bb4">

**Comment by gill15** [comment]
> hello
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kabir/open-interpreter-litellm-fork/interpreter/interpreter.py", line 135, in cli
    cli(self)
  File "/home/kabir/open-interpreter-litellm-fork/interpreter/cli.py", line 210, in cli
    interpreter.chat()
  File "/home/kabir/open-interpreter-litellm-fork/interpreter/interpreter.py", line 297, in chat
    self.respond()
  File "/home/kabir/open-interpreter-litellm-fork/interpreter/interpreter.py", line 530, in respond
    raise Exception(error)
Exception: Traceback (most recent call last):
  File "/home/kabir/.cache/pypoetry/virtualenvs/open-interpreter-lCw68mdF-py3.10/lib/python3.10/site-packages/openai/api_requestor.py", line 403, in handle_error_response
    error_data = resp["error"]
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kabir/open-interpreter-litellm-fork/interpreter/interpreter.py", line 516, in respond
    response = litellm.completion(
  File "/home/kabir/.cache/pypoetry/virtualenvs/open-interpreter-lCw68mdF-py3.10/lib/python3.10/site-packages/litellm/utils.py", line 638, in wrapper
    raise e
  File "/home/kabir/.cache/pypoetry/virtualenvs/open-interpreter-lCw68mdF-py3.10/lib/python3.10/site-packages/litellm/utils.py", line 598, in wrapper
    result = original_function(*args, **kwargs)
  File "/home/kabir/.cache/pypoetry/virtualenvs/open-interpreter-lCw68mdF-py3.10/lib/python3.10/site-packages/litellm/timeout.py", line 44, in wrapper
    result = future.result(timeout=local_timeout_duration)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/kabir/.cache/pypoetry/virtualenvs/open-interpreter-lCw68mdF-py3.10/lib/python3.10/site-packages/litellm/timeout.py", line 33, in async_func
    return func(*args, **kwargs)
  File "/home/kabir/.cache/pypoetry/virtualenvs/open-interpreter-lCw68mdF-py3.10/lib/python3.10/site-packages/litellm/main.py", line 948, in completion
    raise exception_type(
  File "/home/kabir/.cache/pypoetry/virtualenvs/open-interpreter-lCw68mdF-py3.10/lib/python3.10/site-packages/litellm/utils.py", line 2284, in exception_type
    raise e
  File "/home/kabir/.cache/pypoetry/virtualenvs/open-interpreter-lCw68mdF-py3.10/lib/python3.10/site-packages/litellm/utils.py", line 1787, in exception_type
    raise original_exception
  File "/home/kabir/.cache/pypoetry/virtualenvs/open-interpreter-lCw68mdF-py3.10/lib/python3.10/site-packages/litellm/main.py", line 310, in completion
    raise e
  File "/home/kabir/.cache/pypoetry/virtualenvs/open-interpreter-lCw68mdF-py3.10/lib/python3.10/site-packages/litellm/main.py", line 292, in completion
    response = openai.ChatCompletion.create(
  File "/home/kabir/.cache/pypoetry/virtualenvs/open-interpreter-lCw68mdF-py3.10/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/kabir/.cache/pypoetry/virtualenvs/open-interpreter-lCw68mdF-py3.10/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/kabir/.cache/pypoetry/virtualenvs/open-interpreter-lCw68mdF-py3.10/lib/python3.10/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/kabir/.cache/pypoetry/virtualenvs/open-interpreter-lCw68mdF-py3.10/lib/python3.10/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/home/kabir/.cache/pypoetry/virtualenvs/open-interpreter-lCw68mdF-py3.10/lib/python3.10/site-packages/openai/api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
  File "/home/kabir/.cache/pypoetry/virtualenvs/open-interpreter-lCw68mdF-py3.10/lib/python3.10/site-packages/openai/api_requestor.py", line 405, in handle_error_response
    raise error.APIError(
openai.error.APIError: Invalid response object from API: 'Internal Server Error' (HTTP response code was 500)

**Comment by Wawawes** [comment]
Did it work?

**Comment by lisanhu** [comment]
> @lisanhu this is with the forked open-interpreter?
> 
> you need to add a random key here - just input `hi` <img alt="Screenshot 2023-09-18 at 8 59 55 AM" width="395" src="https://user-images.githubusercontent.com/17561003/268705330-1b94854e-495f-40b9-9880-2bed8c253bb4.png">

Thank you so much! It worked!

**Comment by wf744** [comment]
@krrishdholakia   unwork, how to solve?

(venv) PS D:\open-interpreter-litellm-fork> poetry run interpreter --model litellm_proxy/claude-2
A new version is available. Please run 'pip install --upgrade open-interpreter'.


────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

▌ LLM API key not found

To use GPT-4 (recommended) please provide an OpenAI API key.

To use Claude-2 please provide an Anthropic API key.

To use Code-Llama (free but less capable) press enter.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

LLM API [OpenAI/Anthropic] key: hi

Tip: To save this key for later, run export OPENAI_API_KEY=your_api_key on Mac/Linux or setx OPENAI_API_KEY your_api_key
on Windows.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

▌ Model set to LITELLM_PROXY/CLAUDE-2

Tip: To run locally, use interpreter --local

Open Interpreter will require approval before running code. Use interpreter -y to bypass this.

Press CTRL-C to exit.

> hi
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\open-interpreter-litellm-fork\interpreter\interpreter.py", line 135, in cli
    cli(self)
  File "D:\open-interpreter-litellm-fork\interpreter\cli.py", line 210, in cli
    interpreter.chat()
  File "D:\open-interpreter-litellm-fork\interpreter\interpreter.py", line 297, in chat
    self.respond()
  File "D:\open-interpreter-litellm-fork\interpreter\interpreter.py", line 530, in respond
    raise Exception(error)
Exception: Traceback (most recent call last):
  File "D:\open-interpreter-litellm-fork\venv\lib\site-packages\openai\api_requestor.py", line 403, in handle_error_response
    error_data = resp["error"]
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\open-interpreter-litellm-fork\interpreter\interpreter.py", line 516, in respond
    response = litellm.completion(
  File "D:\open-interpreter-litellm-fork\venv\lib\site-packages\litellm\utils.py", line 638, in wrapper
    raise e
  File "D:\open-interpreter-litellm-fork\venv\lib\site-packages\litellm\utils.py", line 598, in wrapper
    result = original_function(*args, **kwargs)
  File "D:\open-interpreter-litellm-fork\venv\lib\site-packages\litellm\timeout.py", line 44, in wrapper
    result = future.result(timeout=local_timeout_duration)
  File "J:\Python310-11\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "J:\Python310-11\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "D:\open-interpreter-litellm-fork\venv\lib\site-packages\litellm\timeout.py", line 33, in async_func
    return func(*args, **kwargs)
  File "D:\open-interpreter-litellm-fork\venv\lib\site-packages\litellm\main.py", line 948, in completion
    raise exception_type(
  File "D:\open-interpreter-litellm-fork\venv\lib\site-packages\litellm\utils.py", line 2284, in exception_type
    raise e
  File "D:\open-interpreter-litellm-fork\venv\lib\site-packages\litellm\utils.py", line 1787, in exception_type
    raise original_exception
  File "D:\open-interpreter-litellm-fork\venv\lib\site-packages\litellm\main.py", line 310, in completion
    raise e
  File "D:\open-interpreter-litellm-fork\venv\lib\site-packages\litellm\main.py", line 292, in completion
    response = openai.ChatCompletion.create(
  File "D:\open-interpreter-litellm-fork\venv\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "D:\open-interpreter-litellm-fork\venv\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "D:\open-interpreter-litellm-fork\venv\lib\site-packages\openai\api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "D:\open-interpreter-litellm-fork\venv\lib\site-packages\openai\api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "D:\open-interpreter-litellm-fork\venv\lib\site-packages\openai\api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
  File "D:\open-interpreter-litellm-fork\venv\lib\site-packages\openai\api_requestor.py", line 405, in handle_error_response
    raise error.APIError(
openai.error.APIError: Invalid response object from API: 'Internal Server Error' (HTTP response code was 500)

(venv) PS D:\open-interpreter-litellm-fork>

**Comment by ericrallen** [comment]
@krrishdholakia Do we still need to keep this issue open now that LiteLLM is fully integrated and usage is fairly well-documented?
