### ISSUE TITLE
interpreter aborts: bug or unexpected prompt?

### ISSUE THREAD

**Issue by jonny7737** [KillianLucas/open-interpreter#389]
### Describe the bug

`> start 2 python interpreters and run a 15 second count down timer in each with the remaining time printed every second. run them concurrently.

  To start two Python interpreters and run a 15-second countdown timer in each with the remaining
  time printed every second, we can use the multiprocessing module in Python. This module allows
  us to run multiple processes concurrently.

  Here's the plan:

   1 Import the necessary modules.
   2 Define a function countdown that takes a duration as input and prints the remaining time
     every second.
   3 Create two processes using the Process class from the multiprocessing module, passing the
     countdown function and the duration (15 seconds) as arguments.
   4 Start both processes.
   5 Wait for both processes to finish using the join method.

  Let's execute this plan step by step.

> proceed
Traceback (most recent call last):
  File "/usr/local/bin/interpreter", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/site-packages/interpreter/interpreter.py", line 131, in cli
    cli(self)
  File "/usr/local/lib/python3.10/site-packages/interpreter/cli.py", line 207, in cli
    interpreter.chat()
  File "/usr/local/lib/python3.10/site-packages/interpreter/interpreter.py", line 412, in chat
    self.respond()
  File "/usr/local/lib/python3.10/site-packages/interpreter/interpreter.py", line 636, in respond
    raise Exception(error)
Exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/interpreter/interpreter.py", line 621, in respond
    response = litellm.completion(
  File "/usr/local/lib/python3.10/site-packages/litellm/utils.py", line 620, in wrapper
    raise e
  File "/usr/local/lib/python3.10/site-packages/litellm/utils.py", line 580, in wrapper
    result = original_function(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/litellm/timeout.py", line 44, in wrapper
    result = future.result(timeout=local_timeout_duration)
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/litellm/timeout.py", line 33, in async_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/litellm/main.py", line 925, in completion
    raise exception_type(
  File "/usr/local/lib/python3.10/site-packages/litellm/utils.py", line 2232, in exception_type
    raise e
  File "/usr/local/lib/python3.10/site-packages/litellm/utils.py", line 1735, in exception_type
    raise original_exception
  File "/usr/local/lib/python3.10/site-packages/litellm/main.py", line 310, in completion
    raise e
  File "/usr/local/lib/python3.10/site-packages/litellm/main.py", line 292, in completion
    response = openai.ChatCompletion.create(
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Additional properties are not allowed ('logprobs' was unexpected) - 'messages.2'

(oi) [OI] %`

### Reproduce

1. start interpreter interactive mode
2. use prompt: start 2 python interpreters and run a 15 second count down timer in each with the remaining time printed every second. run them concurrently.

### Expected behavior

Execute the plan or explain why it can't

### Open Interpreter version

0.1.4

### Python version

3.10.11

### Operating System name and version

macOS 13

### Additional context

oi running in a docker container.

**Comment by lmonson** [comment]
I believe this is the same as #386

**Comment by jonny7737** [comment]
> I believe this is the same as #386

Followed the #386 steps to reproduce and I do not see the problem reported in #386. 

Perhaps the same but I don't see it.

**Comment by jonny7737** [comment]
> > I believe this is the same as #386
> 
> Followed the #386 steps to reproduce and I do not see the problem reported in #386.
> 
> Perhaps the same but I don't see it.

I stand corrected. closing a duplicate.
