### ISSUE TITLE
Colab setup from the README error happens

### ISSUE THREAD

**Issue by ivanberry** [KillianLucas/open-interpreter#395]
### Describe the bug

After interactive input of Azure openai stuff, like key, base_uri, the error message show below:

Exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/interpreter/interpreter.py", line 601, in respond
    response = litellm.completion(
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 621, in wrapper
    raise e
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 581, in wrapper
    result = original_function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/litellm/timeout.py", line 44, in wrapper
    result = future.result(timeout=local_timeout_duration)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/dist-packages/litellm/timeout.py", line 33, in async_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/litellm/main.py", line 946, in completion
    raise exception_type(
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 2239, in exception_type
    raise e
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 1742, in exception_type
    raise original_exception
  File "/usr/local/lib/python3.10/dist-packages/litellm/main.py", line 236, in completion
    response = openai.ChatCompletion.create(
  File "/usr/local/lib/python3.10/dist-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Unrecognized request argument supplied: functions

### Reproduce

Just flow the colab step, import and input the key and then error happens

### Expected behavior

with expect behavior 

### Screenshots

<img width="903" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/13112910/b84654eb-75b8-421a-abbf-f79547d8827b">

### Open Interpreter version

Name: open-interpreter Version: 0.1.4 Summary: Let language models run code locally. Home-page:  Author: Killian Lucas Author-email: killian@drinkwater.ai License:  Location: /usr/local/lib/python3.10/dist-packages Requires: appdirs, astor, git-python, huggingface-hub, inquirer, litellm, openai, python-dotenv, rich, six, tiktoken, tokentrim, wget Required-by: 

### Python version

Python 3.10.12

### Operating System name and version

colab

**Comment by ishaan-jaff** [comment]
@ivanberry are you using an llm that can do function calling

**Comment by ivanberry** [comment]
@ishaan-jaff 

Sorry, I am pretty new of this project. I just follow the colab link and create a copy in my colab. after input the Azure openAI stuff, I run the basic cell which run .chat('Hello word'). then error happens.

**Comment by zhechenghu** [comment]
Maybe you can refer to #331

**Comment by ivanberry** [comment]
Thanks. it workds
