### ISSUE TITLE
Rate Limit Errors

### ISSUE THREAD

**Issue by Blazzycrafter** [KillianLucas/open-interpreter#408]
### Describe the bug

Crash on ratelimit
1000 tokens per minute

### Reproduce

-_-

### Expected behavior

retry after 1 minute

### Open Interpreter version

0.1.4

### Python version

3.10.12

### Operating System name and version

win 11

**Comment by ericrallen** [comment]
I'm going to close this one as stale for now as we haven't had rate limit complaints in a little bit.

Please feel encouraged to reopen this issue or ping me here and I can reopen it.

**Comment by JustAnotherIdea** [comment]
I'm having this issue now. Latest version of Open Interpreter, gpt4. This is the error is spits out:


```
Traceback (most recent call last):
  File "C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\litellm\llms\OpenAI\openai.py", line 1025, in
completion
    raise e
  File "C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\litellm\llms\OpenAI\openai.py", line 902, in
completion
    return self.streaming(
           ^^^^^^^^^^^^^^^
  File "C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\litellm\llms\OpenAI\openai.py", line 1163, in
streaming
    headers, response = self.make_sync_openai_chat_completion_request(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\litellm\llms\OpenAI\openai.py", line 808, in
make_sync_openai_chat_completion_request
    raise e
  File "C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\litellm\llms\OpenAI\openai.py", line 797, in
make_sync_openai_chat_completion_request
    raw_response = openai_client.chat.completions.with_raw_response.create(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\openai\_legacy_response.py", line 350, in wrapped
    return cast(LegacyAPIResponse[R], func(*args, **kwargs))
                                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\openai\_utils\_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\openai\resources\chat\completions.py", line 668, in
create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\openai\_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\openai\_base_client.py", line 937, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\openai\_base_client.py", line 1041, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization
org-iYj8yQD2LKDafVDRfv9P1oEY on tokens per min (TPM): Limit 30000, Used 27022, Requested 8594. Please try again in
11.232s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None,
'code': 'rate_limit_exceeded'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\litellm\main.py", line 1372, in completion
    raise e
  File "C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\litellm\main.py", line 1345, in completion
    response = openai_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\litellm\llms\OpenAI\openai.py", line 1032, in
completion
    raise OpenAIError(
litellm.llms.OpenAI.openai.OpenAIError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in
organization org-iYj8yQD2LKDafVDRfv9P1oEY on tokens per min (TPM): Limit 30000, Used 27022, Requested 8594. Please
try again in 11.232s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens',
'param': None, 'code': 'rate_limit_exceeded'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Noah\miniconda3\envs\interp\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File
"C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\interpreter\terminal_interface\start_terminal_interface.py",
line 610, in main
    start_terminal_interface(interpreter)
  File
"C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\interpreter\terminal_interface\start_terminal_interface.py",
line 576, in start_terminal_interface
    interpreter.chat()
  File "C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\interpreter\core\core.py", line 191, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\interpreter\core\core.py", line 223, in
_streaming_chat
    yield from terminal_interface(self, message)
  File
"C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\interpreter\terminal_interface\terminal_interface.py", line
157, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\interpreter\core\core.py", line 259, in
_streaming_chat
    yield from self._respond_and_store()
  File "C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\interpreter\core\core.py", line 318, in
_respond_and_store
    for chunk in respond(self):
  File "C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\interpreter\core\respond.py", line 86, in respond
    for chunk in interpreter.llm.run(messages_for_llm):
  File "C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\interpreter\core\llm\llm.py", line 322, in run
    yield from run_tool_calling_llm(self, params)
  File "C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\interpreter\core\llm\run_tool_calling_llm.py", line
178, in run_tool_calling_llm
    for chunk in llm.completions(**request_params):
  File "C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\interpreter\core\llm\llm.py", line 466, in
fixed_litellm_completions
    raise first_error  # If all attempts fail, raise the first error
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\interpreter\core\llm\llm.py", line 443, in
fixed_litellm_completions
    yield from litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\litellm\utils.py", line 1092, in wrapper
    raise e
  File "C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\litellm\utils.py", line 980, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\litellm\main.py", line 2796, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\litellm\utils.py", line 8189, in exception_type
    raise e
  File "C:\Users\Noah\miniconda3\envs\interp\Lib\site-packages\litellm\utils.py", line 6557, in exception_type
    raise RateLimitError(
litellm.exceptions.RateLimitError: litellm.RateLimitError: RateLimitError: OpenAIException - Error code: 429 -
{'error': {'message': 'Rate limit reached for gpt-4o in organization org-iYj8yQD2LKDafVDRfv9P1oEY on tokens per min
(TPM): Limit 30000, Used 27022, Requested 8594. Please try again in 11.232s. Visit
https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code':
'rate_limit_exceeded'}}
```

**Comment by aborruso** [comment]
Hi @ericrallen, I'm using groq in this way

```
interpreter -ab "https://api.groq.com/openai/v1" -ak "xxxxxxx" --model "llama-3.3-70b-versatile" --context_window 128000 --groq
```

When I use it, as soon as the interaction gets richer and more complex I get RateLimitError errors:

```
litellm.exceptions.RateLimitError: litellm.RateLimitError: RateLimitError: OpenAIException - Error code: 429 - {'error': {'message': 'Rate
limit reached for model `llama-3.3-70b-versatile` in organization `org_01hs26sgxde6dva0eke39336sv` on tokens per minute (TPM): Limit 6000,
Used 3513, Requested 3166. Please try again in 6.780999999s. Visit https://console.groq.com/docs/rate-limits for more information.',
'type': 'tokens', 'code': 'rate_limit_exceeded'}}
```

Can I use some parameter and set the limit and not have the error?

Thank you
