### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by lez-doit** [KillianLucas/open-interpreter#440]
### Describe the bug

Traceback (most recent call last):
  File "C:\Users\Artem\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Artem\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Artem\AppData\Local\Programs\Python\Python310\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\Artem\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\interpreter.py", line 131, in cli
    cli(self)
  File "C:\Users\Artem\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\cli.py", line 207, in cli
    interpreter.chat()
  File "C:\Users\Artem\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\interpreter.py", line 313, in chat
    self.verify_api_key()
  File "C:\Users\Artem\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\interpreter.py", line 507, in verify_api_key
    self._print_welcome_message()
  File "C:\Users\Artem\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\interpreter.py", line 953, in _print_welcome_message
    print("", Markdown("\u25cf"), "", Markdown(f"\nWelcome to **Open Interpreter**.\n"), "")
  File "C:\Users\Artem\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\__init__.py", line 74, in print
    return write_console.print(*objects, sep=sep, end=end)
  File "C:\Users\Artem\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 1673, in print
    with self:
  File "C:\Users\Artem\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 865, in __exit__
    self._exit_buffer()
  File "C:\Users\Artem\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 823, in _exit_buffer
    self._check_buffer()
  File "C:\Users\Artem\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 2027, in _check_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
  File "C:\Users\Artem\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\_windows_renderer.py", line 19, in legacy_windows_render
    term.write_text(text)
  File "C:\Users\Artem\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\_win32_console.py", line 403, in write_text
    self.write(text)
  File "C:\Users\Artem\AppData\Local\Programs\Python\Python310\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u25cf' in position 0: character maps to <undefined>

### Reproduce

1.  $ pip install open-interpreter
2. $ interpreter

### Expected behavior

I expected to start open interpreter

### Open Interpreter version

0.1.4

### Python version

3.10.4

### Operating System name and version

Windows 10

**Comment by Maximophone** [comment]
Getting the same error.

**Comment by xinranli0809** [comment]
same issue

**Comment by ericrallen** [comment]
Hey there, folks!

Going to try to consolidate the conversation around UnicodeDecodeError and UnicodeEncodeError into #93

Please feel encouraged to continue the discussion in that thread so we’ve got everything in one spot.
