### ISSUE TITLE
Error while using with Code LLama 

### ISSUE THREAD

**Issue by ElCuboNegro** [KillianLucas/open-interpreter#444]
### Describe the bug

Once CodeLLama is installed, the project runs but with bugs related with pyreadline3

### Reproduce

- pip install open-interpreter
- Select code llama 34B
- Select 18.8GB
- Select y for GPU usage
- Model found at C:\Users\jalba\AppData\Local\Open Interpreter\Open Interpreter\models\codellama-34b-instruct.Q4_K_M.gguf
- ▌ Model set to TheBloke/CodeLlama-34B-Instruct-GGUF

### Expected behavior

Its expected to allow me to interact with the open interpreter. however the following trace is given:

Open Interpreter will require approval before running code. Use interpreter -y to bypass this.

Press CTRL-C to exit.

Readline internal error
Traceback (most recent call last):
  File "C:\Users\jalba\anaconda3\Lib\site-packages\pyreadline3\console\console.py", line 804, in hook_wrapper_23
    res = ensure_str(readline_hook(prompt))
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jalba\anaconda3\Lib\site-packages\pyreadline3\rlmain.py", line 587, in readline
    self.readline_setup(prompt)
  File "C:\Users\jalba\anaconda3\Lib\site-packages\pyreadline3\rlmain.py", line 583, in readline_setup
    self._print_prompt()
  File "C:\Users\jalba\anaconda3\Lib\site-packages\pyreadline3\rlmain.py", line 487, in _print_prompt
    n = c.write_scrolling(self.prompt, self.prompt_color)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jalba\anaconda3\Lib\site-packages\pyreadline3\console\console.py", line 332, in write_scrolling
    w, h = self.size()
    ^^^^
TypeError: cannot unpack non-iterable NoneType object

### Open Interpreter version

0.14

### Python version

3.11

### Operating System name and version

Windows 11

**Comment by Dix01** [comment]
lots of people getting the same issue

> ### Describe the bug
> Once CodeLLama is installed, the project runs but with bugs related with pyreadline3
> 
> ### Reproduce
> * pip install open-interpreter
> * Select code llama 34B
> * Select 18.8GB
> * Select y for GPU usage
> * Model found at C:\Users\jalba\AppData\Local\Open Interpreter\Open Interpreter\models\codellama-34b-instruct.Q4_K_M.gguf
> * ▌ Model set to TheBloke/CodeLlama-34B-Instruct-GGUF
> 
> ### Expected behavior
> Its expected to allow me to interact with the open interpreter. however the following trace is given:
> 
> Open Interpreter will require approval before running code. Use interpreter -y to bypass this.
> 
> Press CTRL-C to exit.
> 
> Readline internal error Traceback (most recent call last): File "C:\Users\jalba\anaconda3\Lib\site-packages\pyreadline3\console\console.py", line 804, in hook_wrapper_23 res = ensure_str(readline_hook(prompt)) ^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\jalba\anaconda3\Lib\site-packages\pyreadline3\rlmain.py", line 587, in readline self.readline_setup(prompt) File "C:\Users\jalba\anaconda3\Lib\site-packages\pyreadline3\rlmain.py", line 583, in readline_setup self._print_prompt() File "C:\Users\jalba\anaconda3\Lib\site-packages\pyreadline3\rlmain.py", line 487, in _print_prompt n = c.write_scrolling(self.prompt, self.prompt_color) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\jalba\anaconda3\Lib\site-packages\pyreadline3\console\console.py", line 332, in write_scrolling w, h = self.size() ^^^^ TypeError: cannot unpack non-iterable NoneType object
> 
> ### Screenshots
> _No response_
> 
> ### Open Interpreter version
> 0.14
> 
> ### Python version
> 3.11
> 
> ### Operating System name and version
> Windows 11
> 
> ### Additional context
> _No response_
lots of people getting the same issue

**Comment by furier** [comment]
For me it seems like it is just running continously trying to run code without me consenting to it 🤷‍♂️

```
interpreter --local

Open Interpreter will use Code Llama for local execution. Use your arrow keys to set up the model.

[?] Parameter count (smaller is faster, larger is more capable): 13B
   7B
 > 13B
   34B

[?] Quality (smaller is faster, larger is more capable): Medium | Size: 7.3 GB, Estimated RAM usage: 9.8 GB
   Small | Size: 5.1 GB, Estimated RAM usage: 7.6 GB
 > Medium | Size: 7.3 GB, Estimated RAM usage: 9.8 GB
   Large | Size: 12.9 GB, Estimated RAM usage: 15.4 GB
   See More

[?] Use GPU? (Large models might crash on GPU, but will run more quickly) (Y/n):
This language model was not found on your system.

Download to `C:\Users\furie\AppData\Local\Open Interpreter\Open Interpreter\models`?
[?]  (Y/n):
Downloading (…)instruct.Q4_K_M.gguf: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7.87G/7.87G [02:11<00:00, 60.0MB/s]
Model found at C:\Users\furie\AppData\Local\Open Interpreter\Open Interpreter\models\codellama-13b-instruct.Q4_K_M.gguf

▌ Model set to TheBloke/CodeLlama-13B-Instruct-GGUF

Open Interpreter will require approval before running code. Use interpreter -y to bypass this.

Press CTRL-C to exit.

Readline internal error
Traceback (most recent call last):
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\console\console.py", line 804, in hook_wrapper_23
    res = ensure_str(readline_hook(prompt))
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\rlmain.py", line 587, in readline
    self.readline_setup(prompt)
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\rlmain.py", line 583, in readline_setup
    self._print_prompt()
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\rlmain.py", line 487, in _print_prompt
    n = c.write_scrolling(self.prompt, self.prompt_color)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\console\console.py", line 332, in write_scrolling
    w, h = self.size()
    ^^^^
TypeError: cannot unpack non-iterable NoneType object




  cd C:\dev
  mkdir furie
  cd furie
  touch README.md
  echo


Readline internal error
Traceback (most recent call last):
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\console\console.py", line 804, in hook_wrapper_23
    res = ensure_str(readline_hook(prompt))
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\rlmain.py", line 587, in readline
    self.readline_setup(prompt)
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\rlmain.py", line 583, in readline_setup
    self._print_prompt()
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\rlmain.py", line 487, in _print_prompt
    n = c.write_scrolling(self.prompt, self.prompt_color)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\console\console.py", line 332, in write_scrolling
    w, h = self.size()
    ^^^^
TypeError: cannot unpack non-iterable NoneType object




Readline internal error
Traceback (most recent call last):
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\console\console.py", line 804, in hook_wrapper_23
    res = ensure_str(readline_hook(prompt))
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\rlmain.py", line 587, in readline
    self.readline_setup(prompt)
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\rlmain.py", line 583, in readline_setup
    self._print_prompt()
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\rlmain.py", line 487, in _print_prompt
    n = c.write_scrolling(self.prompt, self.prompt_color)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\console\console.py", line 332, in write_scrolling
    w, h = self.size()
    ^^^^
TypeError: cannot unpack non-iterable NoneType object

Readline internal error
Traceback (most recent call last):
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\console\console.py", line 804, in hook_wrapper_23
    res = ensure_str(readline_hook(prompt))
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\rlmain.py", line 587, in readline
    self.readline_setup(prompt)
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\rlmain.py", line 583, in readline_setup
    self._print_prompt()
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\rlmain.py", line 487, in _print_prompt
    n = c.write_scrolling(self.prompt, self.prompt_color)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\console\console.py", line 332, in write_scrolling
    w, h = self.size()
    ^^^^
TypeError: cannot unpack non-iterable NoneType object




Readline internal error
Traceback (most recent call last):
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\console\console.py", line 804, in hook_wrapper_23
    res = ensure_str(readline_hook(prompt))
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\rlmain.py", line 587, in readline
    self.readline_setup(prompt)
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\rlmain.py", line 583, in readline_setup
    self._print_prompt()
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\rlmain.py", line 487, in _print_prompt
    n = c.write_scrolling(self.prompt, self.prompt_color)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\console\console.py", line 332, in write_scrolling
    w, h = self.size()
    ^^^^
TypeError: cannot unpack non-iterable NoneType object
Readline internal error
Traceback (most recent call last):
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\console\console.py", line 804, in hook_wrapper_23
    res = ensure_str(readline_hook(prompt))
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\rlmain.py", line 587, in readline
    self.readline_setup(prompt)
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\rlmain.py", line 583, in readline_setup
    self._print_prompt()
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\rlmain.py", line 487, in _print_prompt
    n = c.write_scrolling(self.prompt, self.prompt_color)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\furie\miniconda3\Lib\site-packages\pyreadline3\console\console.py", line 332, in write_scrolling
    w, h = self.size()
    ^^^^
TypeError: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\furie\miniconda3\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\furie\miniconda3\Lib\site-packages\interpreter\interpreter.py", line 131, in cli
    cli(self)
  File "C:\Users\furie\miniconda3\Lib\site-packages\interpreter\cli.py", line 207, in cli
    interpreter.chat()
  File "C:\Users\furie\miniconda3\Lib\site-packages\interpreter\interpreter.py", line 412, in chat
    self.respond()
  File "C:\Users\furie\miniconda3\Lib\site-packages\interpreter\interpreter.py", line 688, in respond
    prompt = messages_to_prompt(messages)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\furie\miniconda3\Lib\site-packages\interpreter\interpreter.py", line 673, in messages_to_prompt
    content = item['content']
              ~~~~^^^^^^^^^^^
KeyError: 'content'
^C
C:\dev
```

**Comment by ray2021** [comment]
Same here

**Comment by ganpare** [comment]
me too.
But I installed the latest version and it did improve.
pip install git+https://github.com/KillianLucas/open-interpreter.git
Try it.

**Comment by ericrallen** [comment]
Closing this one as deadline has been temporarily removed from the project.
