### ISSUE TITLE
Receiving "SyntaxError" running Python scripts after Updating to version 0.1.4 on all queries. 

### ISSUE THREAD

**Issue by Ahmedfq** [KillianLucas/open-interpreter#464]
### Describe the bug

After updating to current version of Open-Interpreter, every tasks terminates with the following error "SyntaxError: invalid syntax" using OpenAI GPT4 . It seems like its a pip error or perhaps python issue, not sure as it come up every time "pip install" is used in the python code. Didn't have this issue 30mins ago while running the previous version (not sure what that verison was probably installed it in late Aug) 

### Reproduce

1. load interpreter "interpreter -y"
2. Run any task (i.e. Load CNN News and summarize the main story from here "https://www.cnn.com/2023/09/20/politics/takeaways-merrick-garland-hunter-biden-hearing-impeachment/index.html"
3. Open Interpreter starts to define python code 
4.   import sys
  !{sys.executable} -m pip install requests beautifulsoup4

### Expected behavior

The following error is generated 

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\zmoun\anaconda3\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\zmoun\anaconda3\Lib\site-packages\interpreter\interpreter.py", line 131, in cli
    cli(self)
  File "C:\Users\zmoun\anaconda3\Lib\site-packages\interpreter\cli.py", line 207, in cli
    interpreter.chat()
  File "C:\Users\zmoun\anaconda3\Lib\site-packages\interpreter\interpreter.py", line 412, in chat
    self.respond()
  File "C:\Users\zmoun\anaconda3\Lib\site-packages\interpreter\interpreter.py", line 924, in respond
    code_interpreter.run()
  File "C:\Users\zmoun\anaconda3\Lib\site-packages\interpreter\code_interpreter.py", line 201, in run
    code = wrap_in_try_except(code)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zmoun\anaconda3\Lib\site-packages\interpreter\code_interpreter.py", line 464, in wrap_in_try_except
    parsed_code = ast.parse(code)
                  ^^^^^^^^^^^^^^^
  File "C:\Users\zmoun\anaconda3\Lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 4
    !{sys.executable} -m pip install requests beautifulsoup4
    ^
SyntaxError: invalid syntax

### Screenshots

Same are the error copied above

### Open Interpreter version

0.1.4

### Python version

3.11.4

### Operating System name and version

Windows 11

### Additional context

Checked on a few machine, one with Python 3.10.1 same issue.

**Comment by ericrallen** [comment]
Hey there, @Ahmedfq!

I’m going to close this one for now as it’s referring to an older version of Open Interpreter.

Please feel free to reopen the Issue if you still experience it with the latest version.
