### ISSUE TITLE
Using Azure gives   TypeError: InvalidRequestError.__init__() missing 1 required positional argument: 'param'

### ISSUE THREAD

**Issue by stevenbaert** [KillianLucas/open-interpreter#485]
### Describe the bug

If I run interpreter --use-azure
interpreter starts and says "▌ Model set to  (Azure) "
But when I type in a query, I get error message "TypeError: InvalidRequestError.__init__() missing 1 required positional argument: 'param'"

Please advise how to continue

--- full error:
test
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/bin/interpreter", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/interpreter/interpreter.py", line 131, in cli
    cli(self)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/interpreter/cli.py", line 207, in cli
    interpreter.chat()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/interpreter/interpreter.py", line 412, in chat
    self.respond()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/interpreter/interpreter.py", line 636, in respond
    raise Exception(error)
Exception: Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/interpreter/interpreter.py", line 601, in respond
    response = litellm.completion(
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/litellm/utils.py", line 651, in wrapper
    raise e
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/litellm/utils.py", line 610, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/litellm/timeout.py", line 44, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/litellm/timeout.py", line 33, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/litellm/main.py", line 1071, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/litellm/utils.py", line 2442, in exception_type
    raise original_exception
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/litellm/utils.py", line 2422, in exception_type
    raise original_exception
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/litellm/main.py", line 315, in completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 113, in __prepare_create_request
    url = cls.class_url(engine, api_type, api_version)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 37, in class_url
    raise error.InvalidRequestError(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: InvalidRequestError.__init__() missing 1 required positional argument: 'param'

### Reproduce

Used the config mentioned on your Github:

interpreter.use_azure = True
interpreter.api_key = "your_openai_api_key"
interpreter.azure_api_base = "your_azure_api_base"
interpreter.azure_api_version = "your_azure_api_version"
interpreter.azure_deployment_name = "your_azure_deployment_name"
interpreter.azure_api_type = "azure"

Tried API version "2023-03-15-preview" as well as "2023-07-01-preview"

interpreter starts, but throws error

### Expected behavior

Interpreter running to Azure OpenAI which I know works fine.

### Open Interpreter version

 0.1.4

### Python version

3.11.5

### Operating System name and version

Mac OS

**Comment by stevenbaert** [comment]
Update: last attempt was in vscode, when I run it in a Mac terminal, I get
Model set to gpt-4-32k (Azure)  when running "interpreter --use-azure"

When I then ask a question, I get the error: "openai.error.InvalidRequestError: Unrecognized request argument supplied: functions"
