### ISSUE TITLE
interpreter --config Error

### ISSUE THREAD

**Issue by Boguslaw-D** [KillianLucas/open-interpreter#498]
### Describe the bug

Opening `C:\Users\No2\AppData\Local\Open Interpreter\config.yaml`...
Traceback (most recent call last):
  File "C:\Users\No2\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\No2\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\No2\AppData\Local\Programs\Python\Python310\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\No2\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\core\core.py", line 21, in cli
    cli(self)
  File "C:\Users\No2\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\cli\cli.py", line 106, in cli    os.startfile(config_path)  # This will open the file with the default application, e.g., Notepad
FileNotFoundError: [WinError 2] The specified file cannot be found: 'C:\\Users\\No2\\AppData\\Local\\Open Interpreter\\config.yaml'

-------------------------------
The cause of the error:
File not found because the config.yaml file is located in path: "C:\Users\No2\AppData\Local\Open Interpreter\Open Interpreter"

### Reproduce

interpreter --config

### Expected behavior

Open config file.

### Open Interpreter version

0.1.5

### Python version

3.10.4

### Operating System name and version

Windows 10

**Comment by osjimene** [comment]
Can you just move the Yaml file to 'C:\Users\No2\AppData\Local\Open Interpreter\' ?

run this in the terminal: 
>mv "C:\Users\No2\AppData\Local\Open Interpreter\Open Interpreter\Config.yaml" "C:\Users\No2\AppData\Local\Open Interpreter\Config.yaml"


Assuming that you have the config file in that additionally nested Open Interpreter folder.

**Comment by ericrallen** [comment]
Hey there, @Boguslaw-D!

Can you confirm if this still happens with the latest version?

**Comment by ericrallen** [comment]
Going to close this one as stale.

Feel free to reopen if you want to test with a new version and still see the issue.

**Comment by Domino9752** [comment]
Installed 3/29;   C:\Users\userid\AppData\Local\open-interpreter\open-interpreter\profiles\default.yaml  (win 10)
