### ISSUE TITLE
raise Exception("`interpreter.chat()` requires a display. Set `display=True` or pass a message into `interpreter.chat(message)`.")

### ISSUE THREAD

**Issue by danass** [KillianLucas/open-interpreter#499]
### Describe the bug

Fresh install on ubuntu 22,
I'm using interpreter in terminal.

After sending a prompt, at some point on the answer the program crashes
```

> Traceback (most recent call last):
  File "/home/fauxprophet/Documents/Ops/openai/bin/interpreter", line 8, in <module>
    sys.exit(cli())
  File "/home/fauxprophet/Documents/Ops/openai/lib/python3.10/site-packages/interpreter/core/core.py", line 21, in cli
    cli(self)
  File "/home/fauxprophet/Documents/Ops/openai/lib/python3.10/site-packages/interpreter/cli/cli.py", line 145, in cli
    interpreter.chat()
  File "/home/fauxprophet/Documents/Ops/openai/lib/python3.10/site-packages/interpreter/core/core.py", line 65, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "/home/fauxprophet/Documents/Ops/openai/lib/python3.10/site-packages/interpreter/core/core.py", line 86, in _streaming_chat
    yield from terminal_interface(self, message)
  File "/home/fauxprophet/Documents/Ops/openai/lib/python3.10/site-packages/interpreter/terminal_interface/terminal_interface.py", line 50, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "/home/fauxprophet/Documents/Ops/openai/lib/python3.10/site-packages/interpreter/core/core.py", line 106, in _streaming_chat
    raise Exception("`interpreter.chat()` requires a display. Set `display=True` or pass a message into `interpreter.chat(message)`.")
Exception: `interpreter.chat()` requires a display. Set `display=True` or pass a message into `interpreter.chat(message)`.

```

### Reproduce

1. open terminal
2. run cmd : "interpreter"
3. ask something like "can you change the color of my termninal? provide me with a few different options, and let me choose using a keystroke (1,2,3)?"
4. Wait for answers
5. While answering the program crashes

### Expected behavior

Not crash

### Open Interpreter version

0.1.5

### Python version

3.10.12

### Operating System name and version

Ubuntu 22

**Comment by quietrags** [comment]
yeah - seeing this on my mac after a "pip install --upgrade open-interpreter". It gives the prompt 
> 
after which an 'Enter' command sends it crashing.

**Comment by nufeng1999** [comment]
I'm going to have the same problem

**Comment by firofame** [comment]
same error

**Comment by borjonx** [comment]
Same.  M1 Mac

**Comment by danass** [comment]
I think modifying core.py in site-package/interpreter
And adding
self.display = True
May solve the issue

Le mar. 26 sept. 2023 à 6:48 AM, borjonx ***@***.***> a
écrit :

**Comment by borjonx** [comment]
That worked!  For me it was site-package/interpreter/core/core.py

tysm!

**Comment by ericrallen** [comment]
Closing as this is for an older version of interpreter.

Please reopen if you experience the same issue on the latest version.
