### ISSUE TITLE
Filed to set Azure OpenAI variables when using Python

### ISSUE THREAD

**Issue by chindaku9531** [KillianLucas/open-interpreter#512]
### Describe the bug

I set the Azure OpenAI variables with the code below, but the Open Interprete prompt asked for api_key,azure_api_base,azure_api_version,azure_deployment_name again after running the code.

### Reproduce

1.Start command prompt
2.run "python"
3.run
`import interpreter

interpreter.use_azure = True
interpreter.api_key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
interpreter.azure_api_base = "https://xxxxxxxxxxxxxxxxxxxxxxxxxxxx.openai.azure.com"
interpreter.azure_api_version = "2023-07-01-preview"
interpreter.azure_deployment_name = "gpt-4"
interpreter.azure_api_type = "azure"

messages = interpreter.chat("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
print(messages)`

4.See the following message.
`Welcome to Open Interpreter.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

▌ Azure OpenAI Service API info not found

To use GPT-4 (recommended) please provide an Azure OpenAI API key, a API base, a deployment name and a API version.

To use Code-Llama (free but less capable) press enter.

Azure OpenAI API key:`

### Expected behavior

The variable should be recognized and the answer should be printed.

### Open Interpreter version

0.1.4

### Python version

3.11.3

### Operating System name and version

Windows Server2019 Standard

### Additional context

The variable values should be fine since that after setting the values at the prompt, I can use Open Interpreter without any problems.

**Comment by pikaqqqqqq** [comment]
I can run it with version 0.1.3

**Comment by yunyanliluo** [comment]
I encountered this issue, too. It seems that the python code did not set the variables in an effective way. The interactive mode asked me about the parameters. Furthermore, after I provided the variables in interactive mode and I started to chat, it raised openai.error.InvalidRequestError: Unrecognized request argument supplied: functions. The error usually happens when there are missing parameters. I don't think the Azure variables are passed to openai appropriately even in interactive mode.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\yuanjieba\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\interpreter\interpreter.py", line 258, in chat
    self.respond()
  File "C:\Users\yuanjieba\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\interpreter\interpreter.py", line 510, in respond
    raise Exception(error)
Exception: Traceback (most recent call last):
  File "C:\Users\yuanjieba\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\interpreter\interpreter.py", line 475, in respond
    response = litellm.completion(
  File "C:\Users\yuanjieba\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\litellm\utils.py", line 584, in wrapper
    raise e
  File "C:\Users\yuanjieba\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\litellm\utils.py", line 544, in wrapper
    result = original_function(*args, **kwargs)
  File "C:\Users\yuanjieba\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\litellm\timeout.py", line 44, in wrapper
    result = future.result(timeout=local_timeout_duration)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\yuanjieba\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\litellm\timeout.py", line 33, in async_func
    return func(*args, **kwargs)
  File "C:\Users\yuanjieba\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-pack    raise exception_type(
  File "C:\Users\yuanjieba\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\litellm\utils.py", line 2074, in exception_type
    raise e
  File "C:\Users\yuanjieba\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\litellm\utils.py", line 1667, in exception_type
    raise original_exception
  File "C:\Users\yuanjieba\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\litellm\main.py", line 207, in completion
    response = openai.ChatCompletion.create(
  File "C:\Users\yuanjieba\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\yuanjieba\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\yuanjieba\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\yuanjieba\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\yuanjieba\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Unrecognized request argument supplied: functions


Python version: 3.10.11
Open interpreter version: 0.1.3
Azure api version: 2023-03-15-preview

**Comment by PhucNguyen-KMS** [comment]
@chindaku9531 The underlying model is created with `litellm`, try setting `model` to  `azure/<azure_deployment_name>` as follows:
```python
interpreter.model = "azure/gpt-4"
```
Note: The value `gpt-4` is the Azure deployment name, not necessarily the model name.

**Comment by phucnguyen81** [comment]
@chindaku9531 The underlying model is created with `litellm`, try setting `model` to  `azure/<azure_deployment_name>` as follows:
```python
interpreter.model = "azure/gpt-4"
```
Note: The value `gpt-4` is the Azure deployment name, not necessarily the model name.

**Comment by chindaku9531** [comment]
@yunyanliluo Did you tried the latest version (v1.0.6)? It seems that the variables are passed to openai  sucessfully since this showed up.

> openai.error.AuthenticationError:` Incorrect API key provided: 98a************************9339. You can find your API key at https://platform.openai.com/account/api-keys.

but for some reason this error keeps coming up even though the API key is corecct.

**Comment by chindaku9531** [comment]
@pikaqqqqqq 
I tried to run it with v1.0.3 and the same thing happened.
Did you defined the variables in the same way as described in the Readme?

**Comment by ericrallen** [comment]
Hey there, folks!

I’m going to close this one as stale, but feel encouraged to reopen it if you follow the docs and still run into this issue with the latest version of Open Interpreter.
