### ISSUE TITLE
fail to run

### ISSUE THREAD

**Issue by ffhhaa** [KillianLucas/open-interpreter#516]
### Describe the bug

tip-off error："There might be an issue with your API key(s)."
But I made sure my API was fine. And also tested in other apps with no problem

### Reproduce

1.(base) C:\Users\ffhhaa>conda activate openinterpreter

2.(openinterpreter) C:\Users\ffhhaa>cd /d  D:\坚果云\open-interpreter-main

3.(openinterpreter) D:\坚果云\open-interpreter-main>interpreter --model gpt-3.5-turbo
4. OpenAI API key: sk-.........................
5. Model set to GPT-3.5-TURBO
6.> hello  
7。Traceback (most recent call last):
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\interpreter\core\respond.py", line 56, in respond
    for chunk in interpreter._llm(messages_for_llm):
    .......

### Expected behavior

(base) C:\Users\ffhhaa>conda activate openinterpreter

(openinterpreter) C:\Users\ffhhaa>cd /d  D:\坚果云\open-interpreter-main

(openinterpreter) D:\坚果云\open-interpreter-main>interpreter --model gpt-3.5-turbo

●                                                                                                                      

Welcome to Open Interpreter.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

▌ OpenAI API key not found

To use GPT-4 (recommended) please provide an OpenAI API key.

To use Code-Llama (free but less capable) press enter.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

OpenAI API key: sk-.........................

Tip: To save this key for later, run export OPENAI_API_KEY=your_api_key on Mac/Linux or setx OPENAI_API_KEY your_api_key
on Windows.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

▌ Model set to GPT-3.5-TURBO

Open Interpreter will require approval before running code. Use interpreter -y to bypass this.

Press CTRL-C to exit.

> test
Traceback (most recent call last):
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\interpreter\core\respond.py", line 56, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\interpreter\llm\setup_openai_coding_llm.py", line 79, in coding_llm
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\litellm\utils.py", line 662, in wrapper
    raise e
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\litellm\utils.py", line 621, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\litellm\timeout.py", line 44, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\litellm\timeout.py", line 33, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\litellm\main.py", line 1112, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\litellm\utils.py", line 2661, in exception_type
    raise e
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\litellm\utils.py", line 2098, in exception_type
    raise original_exception
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\litellm\main.py", line 392, in completion
    raise e
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\litellm\main.py", line 374, in completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 106, in __prepare_create_request
    requestor = api_requestor.APIRequestor(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\openai\api_requestor.py", line 138, in __init__
    self.api_key = key or util.default_api_key()
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\openai\util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\interpreter\core\core.py", line 21, in cli
    cli(self)
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\interpreter\cli\cli.py", line 145, in cli
    interpreter.chat()
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\interpreter\core\core.py", line 65, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\interpreter\core\core.py", line 86, in _streaming_chat
    yield from terminal_interface(self, message)
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\interpreter\terminal_interface\terminal_interface.py", line 50, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\interpreter\core\core.py", line 93, in _streaming_chat
    yield from self._respond()
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\interpreter\core\core.py", line 109, in _respond
    yield from respond(self)
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\interpreter\core\respond.py", line 78, in respond
    raise Exception(f"{output}\n\nThere might be an issue with your API key(s).\n\nTo reset your OPENAI_API_KEY (for example):\n        Mac/Linux: 'export OPENAI_API_KEY=your-key-here',\n        Windows: 'setx OPENAI_API_KEY your-key-here' then restart terminal.\n\n")
Exception: Traceback (most recent call last):
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\interpreter\core\respond.py", line 56, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\interpreter\llm\setup_openai_coding_llm.py", line 79, in coding_llm
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\litellm\utils.py", line 662, in wrapper
    raise e
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\litellm\utils.py", line 621, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\litellm\timeout.py", line 44, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\litellm\timeout.py", line 33, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\litellm\main.py", line 1112, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\litellm\utils.py", line 2661, in exception_type
    raise e
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\litellm\utils.py", line 2098, in exception_type
    raise original_exception
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\litellm\main.py", line 392, in completion
    raise e
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\litellm\main.py", line 374, in completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 106, in __prepare_create_request
    requestor = api_requestor.APIRequestor(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\openai\api_requestor.py", line 138, in __init__
    self.api_key = key or util.default_api_key()
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ffhhaa\anaconda3\envs\openinterpreter\Lib\site-packages\openai\util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.

There might be an issue with your API key(s).

To reset your OPENAI_API_KEY (for example):
        Mac/Linux: 'export OPENAI_API_KEY=your-key-here',
        Windows: 'setx OPENAI_API_KEY your-key-here' then restart terminal.

### Open Interpreter version

Version: 0.1.5

### Python version

Python 3.11.5

### Operating System name and version

win10

**Comment by Batozai** [comment]
I have a similar Problem here. win 10

`> interpreter -y
Traceback (most recent call last):
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\respond.py", line 56, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\llm\setup_openai_coding_llm.py", line 79, in coding_llm
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 662, in wrapper
    raise e
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 621, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\timeout.py", line 44, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\timeout.py", line 33, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\main.py", line 1112, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 2661, in exception_type
    raise e
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 2098, in exception_type
    raise original_exception
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\main.py", line 392, in completion
    raise e
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\main.py", line 374, in completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 106, in __prepare_create_request
    requestor = api_requestor.APIRequestor(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 138, in __init__
    self.api_key = key or util.default_api_key()
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 21, in cli
    cli(self)
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\cli\cli.py", line 145, in cli
    interpreter.chat()
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 65, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 86, in _streaming_chat
    yield from terminal_interface(self, message)
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\terminal_interface\terminal_interface.py", line 50, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 93, in _streaming_chat
    yield from self._respond()
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 109, in _respond
    yield from respond(self)
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\respond.py", line 78, in respond
    raise Exception(f"{output}\n\nThere might be an issue with your API key(s).\n\nTo reset your OPENAI_API_KEY (for example):\n        Mac/Linux: 'export OPENAI_API_KEY=your-key-here',\n        Windows: 'setx OPENAI_API_KEY your-key-here' then restart terminal.\n\n")
Exception: Traceback (most recent call last):
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\respond.py", line 56, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\llm\setup_openai_coding_llm.py", line 79, in coding_llm
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 662, in wrapper
    raise e
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 621, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\timeout.py", line 44, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\timeout.py", line 33, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\main.py", line 1112, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 2661, in exception_type
    raise e
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 2098, in exception_type
    raise original_exception
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\main.py", line 392, in completion
    raise e
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\main.py", line 374, in completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 106, in __prepare_create_request
    requestor = api_requestor.APIRequestor(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 138, in __init__
    self.api_key = key or util.default_api_key()
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fab\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.


There might be an issue with your API key(s).

To reset your OPENAI_API_KEY (for example):
        Mac/Linux: 'export OPENAI_API_KEY=your-key-here',
        Windows: 'setx OPENAI_API_KEY your-key-here' then restart terminal.`

**Comment by asadsid95** [comment]
I had this issue persist after adding the key. I restarted terminal and it seems to work fine now

**Comment by ericrallen** [comment]
Hey there, @ffhhaa!

Did you get your API key set? It sounds like it might not have been available in your Environment Variables.

**Comment by ericrallen** [comment]
Going to close this one as a Stale Issue.

Feel free to reopen it if you want to dig into this more.
