### ISSUE TITLE
Azure OpenAI support gone

### ISSUE THREAD

**Issue by stevenbaert** [KillianLucas/open-interpreter#519]
### Describe the bug

Azure OpenAI does not work anymore, also documentation is gone. Is this a voluntary change? Please then inform us why and if it will come back.

### Reproduce

Azure OpenAI does not work anymore, also documentation is gone. Is this a voluntary change? Please then inform us why and if it will come back.

### Expected behavior

Azure OpenAI does not work anymore, also documentation is gone. Is this a voluntary change? Please then inform us why and if it will come back.

### Open Interpreter version

 0.1.5

### Python version

3.11.5

### Operating System name and version

Mac OS

**Comment by goalkeepr** [comment]
Confirmed here too.

**Comment by julianobarbosa** [comment]
+1

**Comment by Vybo** [comment]
Same here.

**Comment by jmottishaw** [comment]
They've moved to using LiteLLM which required the use of the --model parameter to access Azure now. It appears the documentation hasn't been updated yet.

After some digging I've discovered that you need to run it like this:

interpreter --model azure/{your deployment name}

For example:

interpreter --model azure/gpt-4

Note: it is **case sensitive** and azure must be lower case.

**Comment by zmottie** [comment]
They've switched to using LiteLLM which means you have to run using --model now. It appears the documentation hasn't been updated yet.

Provided your environment variables are configured correctly you can run it using:

interpreter --model azure/{your deployment name}

Note: this is case sensitive and azure must be lower case or it's not seen as a provider. 

Example:

interpreter --model azure/gpt-4

**Comment by goalkeepr** [comment]
You are a true hero!

**Comment by Vybo** [comment]
Still doesn't work for me unfortunately. I have the credentials stored in .zprofile and I run the command as suggested:
> export interpreter --model azure/{my-deployment-name}

{my-deployment-name} is the same value as in AZURE_DEPLOYMENT_NAME environment variable and I get this output when sending first message to interpreter:

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/interpreter", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/core/core.py", line 21, in cli
    cli(self)
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/cli/cli.py", line 145, in cli
    interpreter.chat()
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/core/core.py", line 65, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/core/core.py", line 86, in _streaming_chat
    yield from terminal_interface(self, message)
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/terminal_interface/terminal_interface.py", line 50, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/core/core.py", line 93, in _streaming_chat
    yield from self._respond()
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/core/core.py", line 109, in _respond
    yield from respond(self)
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/core/respond.py", line 56, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/llm/convert_to_coding_llm.py", line 24, in coding_llm
    content = chunk['choices'][0]['delta'].get('content', "")
              ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by zmottie** [comment]
When I use our GPT4 32K deployment name I get the same error as you. When using GPT4 it works fine. 

In my digging I also came across the error "Invalid model: azure/gpt-35-turbo-16k. Specify max_tokens instead" so if you're trying to use GPT4 32K you may need to combine --model and --max_tokens

Hopefully the docs are updated soon.

> Still doesn't work for me unfortunately. I have the credentials stored in .zprofile and I run the command as suggested:

**Comment by KillianLucas** [comment]
Hey @stevenbaert, @julianobarbosa, @Vybo and @zmottie. Looking into this now. Thank you so much for reporting.

Would any of you be open to coming onto the #general channel on Discord (https://discord.gg/YG7APUyJ5) and debugging this with me, to make sure it works with your deployments?

**Comment by zmottie** [comment]
> Hey @stevenbaert, @julianobarbosa, @Vybo and @zmottie. Looking into this now. Thank you so much for reporting.
> 
> Would any of you be open to coming onto the #general channel on Discord (https://discord.gg/YG7APUyJ5) and debugging this with me, to make sure it works with your deployments?

Joined and pinged you @KillianLucas. Ping me when you're ready.

**Comment by KillianLucas** [comment]
This has been fixed. Pushing to pip in the next hour, get the fix now via:

```shell
pip install --upgrade --force-reinstall git+https://github.com/KillianLucas/open-interpreter.git
```

**Comment by stevenbaert** [comment]
Awesome, thanks! Could you also bring back the Azure Open AI documentation?  It was there on the main page, but didnt see it reappear yet(?)

**Comment by stevenbaert** [comment]
Note: installed the version with your command, it starts but a simple query makes it crash again.

> what is my version of interpreter

                                                                                                                                                         
  import platform                                                                                                                                        
  platform.python_version()                                                                                                                              
                                                                                                                                                         
                                                                                                                                                         
  '3.11.5'                                                                                                                                               
                                                                                                                                                         
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/bin/interpreter", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/interpreter/interpreter.py", line 131, in cli
    cli(self)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/interpreter/cli.py", line 207, in cli
    interpreter.chat()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/interpreter/interpreter.py", line 412, in chat
    self.respond()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/interpreter/interpreter.py", line 938, in respond
    self.respond()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/interpreter/interpreter.py", line 636, in respond
    raise Exception(error)
Exception: Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/interpreter/interpreter.py", line 601, in respond
    response = litellm.completion(
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/litellm/utils.py", line 651, in wrapper
    raise e
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/litellm/utils.py", line 610, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/litellm/timeout.py", line 44, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/litellm/timeout.py", line 33, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/litellm/main.py", line 1071, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/litellm/utils.py", line 2440, in exception_type
    raise e
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/litellm/utils.py", line 1943, in exception_type
    raise original_exception
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/litellm/main.py", line 315, in completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/openai/api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: 'content' is a required property - 'messages.4'

**Comment by lz82** [comment]
> +1

**Comment by lz82** [comment]
> Note: installed the version with your command, it starts but a simple query makes it crash again.
> 
> > what is my version of interpreter
> 
> import platform platform.python_version()
> 
> '3.11.5'
> 
> Traceback (most recent call last): File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/bin/interpreter", line 8, in sys.exit(cli()) ^^^^^ File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/interpreter/interpreter.py", line 131, in cli cli(self) File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/interpreter/cli.py", line 207, in cli interpreter.chat() File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/interpreter/interpreter.py", line 412, in chat self.respond() File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/interpreter/interpreter.py", line 938, in respond self.respond() File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/interpreter/interpreter.py", line 636, in respond raise Exception(error) Exception: Traceback (most recent call last): File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/interpreter/interpreter.py", line 601, in respond response = litellm.completion( ^^^^^^^^^^^^^^^^^^^ File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/litellm/utils.py", line 651, in wrapper raise e File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/litellm/utils.py", line 610, in wrapper result = original_function(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/litellm/timeout.py", line 44, in wrapper result = future.result(timeout=local_timeout_duration) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/concurrent/futures/_base.py", line 456, in result return self.__get_result() ^^^^^^^^^^^^^^^^^^^ File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result raise self._exception File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/litellm/timeout.py", line 33, in async_func return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/litellm/main.py", line 1071, in completion raise exception_type( ^^^^^^^^^^^^^^^ File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/litellm/utils.py", line 2440, in exception_type raise e File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/litellm/utils.py", line 1943, in exception_type raise original_exception File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/litellm/main.py", line 315, in completion response = openai.ChatCompletion.create( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create return super().create(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create response, _, api_key = requestor.request( ^^^^^^^^^^^^^^^^^^ File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/openai/api_requestor.py", line 298, in request resp, got_stream = self._interpret_response(result, stream) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/openai/api_requestor.py", line 700, in _interpret_response self._interpret_response_line( File "/opt/homebrew/Caskroom/miniforge/base/envs/newsaggregator/lib/python3.11/site-packages/openai/api_requestor.py", line 765, in _interpret_response_line raise self.handle_error_response( openai.error.InvalidRequestError: 'content' is a required property - 'messages.4'

+1
