### ISSUE TITLE
cannot run locally

### ISSUE THREAD

**Issue by lhchg** [KillianLucas/open-interpreter#525]
### Describe the bug

```
Traceback (most recent call last):
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/bin/interpreter", line 8, in <module>
    sys.exit(cli())
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/interpreter/core/core.py", line 21, in cli
    cli(self)
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/interpreter/cli/cli.py", line 145, in cli
    interpreter.chat()
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/interpreter/core/core.py", line 65, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/interpreter/core/core.py", line 79, in _streaming_chat
    self._llm = setup_llm(self)
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/interpreter/llm/setup_llm.py", line 18, in setup_llm
    text_llm = setup_text_llm(interpreter)
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/interpreter/llm/setup_text_llm.py", line 57, in setup_text_llm
    raise Exception("Architecture not yet supported for local LLM inference. Please run `interpreter` to connect to a cloud model, then try `--local` again in a few days.")
Exception: Architecture not yet supported for local LLM inference. Please run `interpreter` to connect to a cloud model, then try `--local` again in a few days.

```
### Reproduce

like doc GPU.md
I have done step 1-7,
and step 7's output is as following
` python -c "from llama_cpp import GGML_USE_CUBLAS; print(GGML_USE_CUBLAS)"
True`

and when I run interpreter --local

it has error like the following

```
`If you've tried that and you're still getting an error, we have likely not built the proper huggingface/TheBloke/CodeLlama-7B-Instruct-GGUF support for your system.


( Running language models locally is a difficult task! If you have insight into the best way to implement this across platforms/architectures, please join the Open Interpreter community Discord and consider contributing the project's development.

Traceback (most recent call last):
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/urllib3/connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/urllib3/connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/urllib3/connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/urllib3/connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/interpreter/llm/setup_text_llm.py", line 45, in setup_text_llm
    return setup_local_text_llm(interpreter)
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/interpreter/llm/setup_local_text_llm.py", line 33, in setup_local_text_llm
    raw_models = list_gguf_files(repo_id)
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/interpreter/llm/setup_local_text_llm.py", line 415, in list_gguf_files
    gguf_files = [file for file in files_info if "gguf" in file.rfilename]
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/interpreter/llm/setup_local_text_llm.py", line 415, in <listcomp>
    gguf_files = [file for file in files_info if "gguf" in file.rfilename]
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 2055, in list_files_info
    for subpath_info in paginate(path=tree_url, headers=headers, params={"recursive": True, "expand": expand}):
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/huggingface_hub/utils/_pagination.py", line 35, in paginate
    r = session.get(path, params=params, headers=headers)
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: (ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')), '(Request ID: a389279b-25ef-426b-b947-64c914269be1)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/bin/interpreter", line 8, in <module>
    sys.exit(cli())
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/interpreter/core/core.py", line 21, in cli
    cli(self)
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/interpreter/cli/cli.py", line 145, in cli
    interpreter.chat()
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/interpreter/core/core.py", line 65, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/interpreter/core/core.py", line 79, in _streaming_chat
    self._llm = setup_llm(self)
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/interpreter/llm/setup_llm.py", line 18, in setup_llm
    text_llm = setup_text_llm(interpreter)
  File "/media/lihaocheng/0a19954d-e7e8-418c-933f-a81eb64d44ff/home/lihaocheng/env/python3.10/lib/python3.10/site-packages/interpreter/llm/setup_text_llm.py", line 57, in setup_text_llm
    raise Exception("Architecture not yet supported for local LLM inference. Please run `interpreter` to connect to a cloud model, then try `--local` again in a few days.")
Exception: Architecture not yet supported for local LLM inference. Please run `interpreter` to connect to a cloud model, then try `--local` again in a few days.`
```

### Expected behavior

I want to use locally

### Open Interpreter version

0.1.5

### Python version

3.10.13

### Operating System name and version

ubuntu 20.04

**Comment by Fuxy-pg** [comment]
I encountered the same problem as you, how did you solve it?
