### ISSUE TITLE
can not import openai key

### ISSUE THREAD

**Issue by mingminglulu** [KillianLucas/open-interpreter#539]
### Describe the bug

Traceback (most recent call last):
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\interpreter\core\respond.py", line 56, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\interpreter\llm\setup_openai_coding_llm.py", line 94, in coding_llm
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\utils.py", line 671, in wrapper
    raise e
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\utils.py", line 630, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\timeout.py", line 42, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\main.py", line 1192, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\utils.py", line 2700, in exception_type
    raise e
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\utils.py", line 2119, in exception_type
    raise original_exception
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\main.py", line 401, in completion
    raise e
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\main.py", line 383, in completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 151, in create
    ) = cls.__prepare_create_request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 108, in __prepare_create_request
    requestor = api_requestor.APIRequestor(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\openai\api_requestor.py", line 139, in __init__
    self.api_key = key or util.default_api_key()
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\openai\util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\interpreter\core\core.py", line 21, in cli
    cli(self)
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\interpreter\cli\cli.py", line 146, in cli
    interpreter.chat()
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\interpreter\core\core.py", line 65, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\interpreter\core\core.py", line 86, in _streaming_chat
    yield from terminal_interface(self, message)
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\interpreter\terminal_interface\terminal_interface.py", line 50, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\interpreter\core\core.py", line 94, in _streaming_chat
    yield from self._respond()
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\interpreter\core\core.py", line 120, in _respond
    yield from respond(self)
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\interpreter\core\respond.py", line 78, in respond
    raise Exception(f"{output}\n\nThere might be an issue with your API key(s).\n\nTo reset your OPENAI_API_KEY (for example):\n        Mac/Linux: 'export OPENAI_API_KEY=your-key-here',\n        Windows: 'setx OPENAI_API_KEY your-key-here' then restart terminal.\n\n")
Exception: Traceback (most recent call last):
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\interpreter\core\respond.py", line 56, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\interpreter\llm\setup_openai_coding_llm.py", line 94, in coding_llm
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\utils.py", line 671, in wrapper
    raise e
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\utils.py", line 630, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\timeout.py", line 42, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\main.py", line 1192, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\utils.py", line 2700, in exception_type
    raise e
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\utils.py", line 2119, in exception_type
    raise original_exception
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\main.py", line 401, in completion
    raise e
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\main.py", line 383, in completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 151, in create
    ) = cls.__prepare_create_request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 108, in __prepare_create_request
    requestor = api_requestor.APIRequestor(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\openai\api_requestor.py", line 139, in __init__
    self.api_key = key or util.default_api_key()
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\openai\util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.

### Reproduce

none

### Expected behavior

Traceback (most recent call last):
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\interpreter\core\respond.py", line 56, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\interpreter\llm\setup_openai_coding_llm.py", line 94, in coding_llm
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\utils.py", line 671, in wrapper
    raise e
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\utils.py", line 630, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\timeout.py", line 42, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\main.py", line 1192, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\utils.py", line 2700, in exception_type
    raise e
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\utils.py", line 2119, in exception_type
    raise original_exception
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\main.py", line 401, in completion
    raise e
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\main.py", line 383, in completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 151, in create
    ) = cls.__prepare_create_request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 108, in __prepare_create_request
    requestor = api_requestor.APIRequestor(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\openai\api_requestor.py", line 139, in __init__
    self.api_key = key or util.default_api_key()
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\openai\util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\interpreter\core\core.py", line 21, in cli
    cli(self)
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\interpreter\cli\cli.py", line 146, in cli
    interpreter.chat()
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\interpreter\core\core.py", line 65, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\interpreter\core\core.py", line 86, in _streaming_chat
    yield from terminal_interface(self, message)
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\interpreter\terminal_interface\terminal_interface.py", line 50, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\interpreter\core\core.py", line 94, in _streaming_chat
    yield from self._respond()
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\interpreter\core\core.py", line 120, in _respond
    yield from respond(self)
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\interpreter\core\respond.py", line 78, in respond
    raise Exception(f"{output}\n\nThere might be an issue with your API key(s).\n\nTo reset your OPENAI_API_KEY (for example):\n        Mac/Linux: 'export OPENAI_API_KEY=your-key-here',\n        Windows: 'setx OPENAI_API_KEY your-key-here' then restart terminal.\n\n")
Exception: Traceback (most recent call last):
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\interpreter\core\respond.py", line 56, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\interpreter\llm\setup_openai_coding_llm.py", line 94, in coding_llm
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\utils.py", line 671, in wrapper
    raise e
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\utils.py", line 630, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\timeout.py", line 42, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\main.py", line 1192, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\utils.py", line 2700, in exception_type
    raise e
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\utils.py", line 2119, in exception_type
    raise original_exception
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\main.py", line 401, in completion
    raise e
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\litellm\main.py", line 383, in completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 151, in create
    ) = cls.__prepare_create_request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 108, in __prepare_create_request
    requestor = api_requestor.APIRequestor(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\openai\api_requestor.py", line 139, in __init__
    self.api_key = key or util.default_api_key()
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicourse\AppData\Roaming\Python\Python311\site-packages\openai\util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.

### Screenshots

none

### Open Interpreter version

new

### Python version

3.11

### Operating System name and version

windows11

### Additional context

please help me fix this error

**Comment by ericrallen** [comment]
Does the `$OPENAI_API_KEY` environment variable exist?

Can you echo it to your terminal?

**Comment by AndreaIlBischero** [comment]
@ericrallen i have the same problem, i have the OPENAI_API_KEY as environment variable. And i set this: 
set OPENAI_API_KEY=(my key). When i echo it, i can see my api key. but when i try the error still persist. can u help me?

**Comment by dagelf** [comment]
The error means your key doesn't work - are you sure you pasted it correctly? (Including the sk- part)? (Maybe we can make Python spit out a better error message?)

You can also run it like this:

$ export OPENAI_API_KEY=your-key-here
$ interpreter

**Comment by ericrallen** [comment]
Going to close this for now.

Feel free to reopen if you’re still having an Issue and the provided suggestions didn’t help.
