### ISSUE TITLE
Mac M1 Air APIKey Setting

### ISSUE THREAD

**Issue by mamingsuper** [KillianLucas/open-interpreter#544]
### Describe the bug

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new

Traceback (most recent call last):
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/interpreter/core/respond.py", line 56, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/interpreter/llm/setup_openai_coding_llm.py", line 94, in coding_llm
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/litellm/utils.py", line 691, in wrapper
    raise e
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/litellm/utils.py", line 650, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/litellm/timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/litellm/timeout.py", line 42, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/litellm/main.py", line 1192, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/litellm/utils.py", line 2722, in exception_type
    raise e
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/litellm/utils.py", line 2141, in exception_type
    raise original_exception
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/litellm/main.py", line 401, in completion
    raise e
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/litellm/main.py", line 383, in completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 151, in create
    ) = cls.__prepare_create_request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 108, in __prepare_create_request
    requestor = api_requestor.APIRequestor(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/openai/api_requestor.py", line 139, in __init__
    self.api_key = key or util.default_api_key()
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/openai/util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mam94/anaconda3/envs/interpret/bin/interpreter", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/interpreter/core/core.py", line 21, in cli
    cli(self)
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/interpreter/cli/cli.py", line 146, in cli
    interpreter.chat()
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/interpreter/core/core.py", line 65, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/interpreter/core/core.py", line 86, in _streaming_chat
    yield from terminal_interface(self, message)
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/interpreter/terminal_interface/terminal_interface.py", line 50, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/interpreter/core/core.py", line 94, in _streaming_chat
    yield from self._respond()
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/interpreter/core/core.py", line 120, in _respond
    yield from respond(self)
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/interpreter/core/respond.py", line 78, in respond
    raise Exception(f"{output}\n\nThere might be an issue with your API key(s).\n\nTo reset your OPENAI_API_KEY (for example):\n        Mac/Linux: 'export OPENAI_API_KEY=your-key-here',\n        Windows: 'setx OPENAI_API_KEY your-key-here' then restart terminal.\n\n")
Exception: Traceback (most recent call last):
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/interpreter/core/respond.py", line 56, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/interpreter/llm/setup_openai_coding_llm.py", line 94, in coding_llm
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/litellm/utils.py", line 691, in wrapper
    raise e
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/litellm/utils.py", line 650, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/litellm/timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/litellm/timeout.py", line 42, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/litellm/main.py", line 1192, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/litellm/utils.py", line 2722, in exception_type
    raise e
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/litellm/utils.py", line 2141, in exception_type
    raise original_exception
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/litellm/main.py", line 401, in completion
    raise e
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/litellm/main.py", line 383, in completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 151, in create
    ) = cls.__prepare_create_request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 108, in __prepare_create_request
    requestor = api_requestor.APIRequestor(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/openai/api_requestor.py", line 139, in __init__
    self.api_key = key or util.default_api_key()
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mam94/anaconda3/envs/interpret/lib/python3.11/site-packages/openai/util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.

There might be an issue with your API key(s).

To reset your OPENAI_API_KEY (for example):
        Mac/Linux: 'export OPENAI_API_KEY=your-key-here',
        Windows: 'setx OPENAI_API_KEY your-key-here' then restart terminal.

(interpret) mam94@GK23896LAP ~ % 

### Reproduce

1.  interpreter -y
2. input openai apikey
3. run code

### Expected behavior

no bugs

### Open Interpreter version

0.1.6

### Python version

3.11

### Operating System name and version

macos

**Comment by lookforhisface** [comment]
Im getting the same error. Running MBP M2Pro inside a MacOS VM.

**Comment by dagelf** [comment]
The error means your key doesn't work - are you sure you pasted it correctly? (Including the sk- part)?

You can also run it like this:

$ export OPENAI_API_KEY=your-key-here
$ interpreter

**Comment by lookforhisface** [comment]
It must have been a time issue between generating the key and adding funds to the account to run. There was also an update to interpreter. At any rate its now working. Thank you!
