### ISSUE TITLE
pipx installation on Arch - can't find dependencies

### ISSUE THREAD

**Issue by V3XATI0N** [KillianLucas/open-interpreter#546]
### Describe the bug

After a recent release, I am no longer able to use open-interpreter on my Arch or Manjaro Linux computers. These distros enforce management of the python environment and so require using `pipx` to install unpackaged python programs. This was working perfectly well with open-interpreter until I updated a couple of days ago (but I'm not sure which release caused the problem, it was probably out of date for a few days before that).

### Reproduce

1. install open-interpreter with `pipx` on Arch or Manjaro - `pipx install open-interpreter`
2. try to run interpreter
3. receive error:
```
Traceback (most recent call last):
  File "/home/pango/.local/pipx/venvs/open-interpreter/lib/python3.11/site-packages/litellm/proxy.py", line 6, in <module>
    from fastapi import FastAPI, Request, status, HTTPException, Depends
ModuleNotFoundError: No module named 'fastapi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pango/.local/bin/interpreter", line 5, in <module>
    from interpreter import cli
  File "/home/pango/.local/pipx/venvs/open-interpreter/lib/python3.11/site-packages/interpreter/__init__.py", line 1, in <module>
    from .core.core import Interpreter
  File "/home/pango/.local/pipx/venvs/open-interpreter/lib/python3.11/site-packages/interpreter/core/core.py", line 8, in <module>
    from .respond import respond
  File "/home/pango/.local/pipx/venvs/open-interpreter/lib/python3.11/site-packages/interpreter/core/respond.py", line 8, in <module>
    import litellm
  File "/home/pango/.local/pipx/venvs/open-interpreter/lib/python3.11/site-packages/litellm/__init__.py", line 325, in <module>
    from .proxy import run_server
  File "/home/pango/.local/pipx/venvs/open-interpreter/lib/python3.11/site-packages/litellm/proxy.py", line 9, in <module>
    raise ImportError("FastAPI needs to be imported. Run - `pip install fastapi`")
ImportError: FastAPI needs to be imported. Run - `pip install fastapi`
```

### Expected behavior

it should work (in fact, it did work until the recent update)

### Open Interpreter version

0.1.6

### Python version

3.11.5

### Operating System name and version

Manjaro 23.0.2

### Additional context

pipx env:
```
pango@nuc ~                                                                                        [13:04:51]
> $ pipx list                                                                                                
venvs are in /home/pango/.local/pipx/venvs
apps are exposed on your $PATH at /home/pango/.local/bin
   package fastapi 0.103.1, installed using Python 3.11.5
   package install 1.3.5, installed using Python 3.11.5
   package open-interpreter 0.1.6, installed using Python 3.11.5
    - interpreter
   package pip 23.2.1, installed using Python 3.11.5
    - pip
    - pip3
    - pip3.11
```

**Comment by V3XATI0N** [comment]
eh. my mistake, failure to know how pipx works. solved with `pipx inject open-interpreter fastapi uvicorn`
