### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'create_chat_completion'

### ISSUE THREAD

**Issue by karamjotsinghmalik** [KillianLucas/open-interpreter#55]
`
▌ Model set to Code-Llama                                                                                                                                                             

Open Interpreter will require approval before running code. Use interpreter -y to bypass this.                                                                                          

Press CTRL-C to exit.                                                                                                                                                                   

> code a function for factorials
Traceback (most recent call last):
  File "/home/singh/miniconda3/envs/oi/bin/interpreter", line 8, in <module>
    sys.exit(cli())
  File "/home/singh/miniconda3/envs/oi/lib/python3.10/site-packages/interpreter/interpreter.py", line 91, in cli
    cli(self)
  File "/home/singh/miniconda3/envs/oi/lib/python3.10/site-packages/interpreter/cli.py", line 42, in cli
    interpreter.chat()
  File "/home/singh/miniconda3/envs/oi/lib/python3.10/site-packages/interpreter/interpreter.py", line 245, in chat
    self.respond()
  File "/home/singh/miniconda3/envs/oi/lib/python3.10/site-packages/interpreter/interpreter.py", line 328, in respond
    response = self.llama_instance.create_chat_completion(
AttributeError: 'NoneType' object has no attribute 'create_chat_completion'
(oi) ➜  ~ 
`

**Comment by Pawandeep-prog** [comment]
try upgrading your llama-cpp manually
```pip install --upgrade llama-cpp-python```
it should solve

**Comment by HyperUpscale** [comment]
> try upgrading your llama-cpp manually `**pip install --upgrade llama-cpp-python**` it should solve

YES, that fixed it for me :)
Thank you!
