### ISSUE TITLE
Cannot use local FastChat model

### ISSUE THREAD

**Issue by itlackey** [KillianLucas/open-interpreter#552]
### Describe the bug

I am trying to point interpreter to a local OpenAI API endpoint that is being hosted via FastChat. 

### Reproduce

python3 -m fastchat.serve.controller --host 0.0.0.0 

python3 -m fastchat.serve.model_worker --device xpu --host 0.0.0.0  --max-gpu-memory 14Gib --num-gpus 1 --gpus 0  --model-path lmsys/vicuna-7b-v1.3

python3 -m fastchat.serve.openai_api_server --host 0.0.0.0 --port 8000

I spin up FastChat and verify it is running by opening http://172.19.0.2:8000/v1/models

The model is displayed so I start interpreter and enter a message. This happens regardless of what I model I have used. If I remove the custom/ prefix I get the second error listed below.

interpreter -y -ab http://172.19.0.2:8000/v1 -m custom/lmsys/vicuna-7b-v1.3
> test

We were unable to determine the context window of this model. Defaulting to 3000.                                                                     
If your model can handle more, run interpreter --context_window {token limit} or interpreter.context_window = {token limit}.                          
Also, please set max_tokens: interpreter --max_tokens {max tokens per response} or interpreter.max_tokens = {max tokens per response}                 

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Out of range float values are not JSON compliant

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/litellm/main.py", line 1157, in completion
    resp = requests.post(url, json={
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 371, in prepare
    self.prepare_body(data, files, json)
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 513, in prepare_body
    raise InvalidJSONError(ve, request=self)
requests.exceptions.InvalidJSONError: Out of range float values are not JSON compliant

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/interpreter", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/interpreter/core/core.py", line 21, in cli
    cli(self)
  File "/usr/local/lib/python3.10/dist-packages/interpreter/cli/cli.py", line 146, in cli
    interpreter.chat()
  File "/usr/local/lib/python3.10/dist-packages/interpreter/core/core.py", line 65, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "/usr/local/lib/python3.10/dist-packages/interpreter/core/core.py", line 86, in _streaming_chat
    yield from terminal_interface(self, message)
  File "/usr/local/lib/python3.10/dist-packages/interpreter/terminal_interface/terminal_interface.py", line 50, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "/usr/local/lib/python3.10/dist-packages/interpreter/core/core.py", line 94, in _streaming_chat
    yield from self._respond()
  File "/usr/local/lib/python3.10/dist-packages/interpreter/core/core.py", line 120, in _respond
    yield from respond(self)
  File "/usr/local/lib/python3.10/dist-packages/interpreter/core/respond.py", line 56, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "/usr/local/lib/python3.10/dist-packages/interpreter/llm/convert_to_coding_llm.py", line 19, in coding_llm
    for chunk in text_llm(messages):
  File "/usr/local/lib/python3.10/dist-packages/interpreter/llm/setup_text_llm.py", line 119, in base_llm
    return litellm.completion(**params)
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 671, in wrapper
    raise e
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 630, in wrapper
    result = original_function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/litellm/timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/dist-packages/litellm/timeout.py", line 42, in async_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/litellm/main.py", line 1194, in completion
    raise exception_type(
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 2702, in exception_type
    raise e
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 2684, in exception_type
    raise APIError(status_code=500, message=str(original_exception), llm_provider=custom_llm_provider, model=model)
litellm.exceptions.APIError: Out of range float values are not JSON compliant

---------------

interpreter -y -ab http://172.19.0.2:8000/v1 -m lmsys/vicuna-7b-v1.3
> test

We were unable to determine the context window of this model. Defaulting to 3000.                                                                     
If your model can handle more, run interpreter --context_window {token limit} or interpreter.context_window = {token limit}.                          
Also, please set max_tokens: interpreter --max_tokens {max tokens per response} or interpreter.max_tokens = {max tokens per response}                 

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/litellm/main.py", line 251, in completion
    model, custom_llm_provider = get_llm_provider(model=model, custom_llm_provider=custom_llm_provider)
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 1204, in get_llm_provider
    raise e
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 1201, in get_llm_provider
    raise ValueError(f"LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/{model}',..)` Learn more: https://docs.litellm.ai/docs/providers")
ValueError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/lmsys/vicuna-7b-v1.3',..)` Learn more: https://docs.litellm.ai/docs/providers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/interpreter", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/interpreter/core/core.py", line 21, in cli
    cli(self)
  File "/usr/local/lib/python3.10/dist-packages/interpreter/cli/cli.py", line 146, in cli
    interpreter.chat()
  File "/usr/local/lib/python3.10/dist-packages/interpreter/core/core.py", line 65, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "/usr/local/lib/python3.10/dist-packages/interpreter/core/core.py", line 86, in _streaming_chat
    yield from terminal_interface(self, message)
  File "/usr/local/lib/python3.10/dist-packages/interpreter/terminal_interface/terminal_interface.py", line 50, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "/usr/local/lib/python3.10/dist-packages/interpreter/core/core.py", line 94, in _streaming_chat
    yield from self._respond()
  File "/usr/local/lib/python3.10/dist-packages/interpreter/core/core.py", line 120, in _respond
    yield from respond(self)
  File "/usr/local/lib/python3.10/dist-packages/interpreter/core/respond.py", line 56, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "/usr/local/lib/python3.10/dist-packages/interpreter/llm/convert_to_coding_llm.py", line 19, in coding_llm
    for chunk in text_llm(messages):
  File "/usr/local/lib/python3.10/dist-packages/interpreter/llm/setup_text_llm.py", line 119, in base_llm
    return litellm.completion(**params)
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 671, in wrapper
    raise e
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 630, in wrapper
    result = original_function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/litellm/timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/dist-packages/litellm/timeout.py", line 42, in async_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/litellm/main.py", line 1194, in completion
    raise exception_type(
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 2702, in exception_type
    raise e
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 2684, in exception_type
    raise APIError(status_code=500, message=str(original_exception), llm_provider=custom_llm_provider, model=model)
litellm.exceptions.APIError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/lmsys/vicuna-7b-v1.3',..)` Learn more: https://docs.litellm.ai/docs/providers

### Expected behavior

I was expecting interpreter to respond as it does when pointed to OpenAI (or close)

### Open Interpreter version

0.1.6

### Python version

3.10.12

### Operating System name and version

Ubuntu 22.04.3 LTS

**Comment by itlackey** [comment]
I was able to find the solution to this issue, and it was to read the LiteLLM docs a little more closely. 

The correct command to connect Open Interpreter to a FastChat OpenAI API endpoint will use the **openai/** prefix on the model path argument.

interpreter -y -ab http://172.19.0.2:8000/v1 -m **openai**/vicuna-7b-v1.3

**Comment by ericrallen** [comment]
@itlackey Thanks so much for circling back and providing the solution for anyone who searches for this issue in the future.

If this issue is resolved, can we close it?
