### ISSUE TITLE
Local Llama model not understanding prompts / poor executions

### ISSUE THREAD

**Issue by robzsaunders** [KillianLucas/open-interpreter#574]
### Describe the bug

Local llama interpreter is doing its own thing?
Output from interpreter :

```
Model found at C:\Users\dulak\AppData\Local\Open Interpreter\Open Interpreter\models\codellama-7b-instruct.Q2_K.gguf
Open Interpreter will require approval before running code.

Use interpreter -y to bypass this.

Press CTRL-C to exit.
> interpreter -y

  Task: Convert a video from one format to another using FFmpeg.

  User Input:

   • Video file name: input.mp4
   • Output file name: output.avi
   • Format: AVI

  Plan:

   1 Install FFmpeg if not already installed.
   2 Check if the input and output files exist.
   3 Run FFmpeg to convert the video from MP4 to AVI format.

  Code Block 1: Install FFmpeg (if necessary)



  # Check if FFmpeg is installed
  ffmpeg -version

  # If not installed, install it
  if [ $? -ne 0 ]; then
      # Install FFmpeg
      sudo apt-get update
      sudo apt-get install ffmpeg
  fi


  Would you like to run this code? (y/n)
```

### Reproduce

Run interpreter

Type interpreter -y

### Expected behavior

Some sort of greeting or prompt to enter next command.

I don't know why it thought it needed to convert video from the -y command

### Open Interpreter version

0.1.7

### Python version

3.11.5

### Operating System name and version

Windows 10

### Additional context

I just installed this so maybe I installed it incorrectly?

First time using it with llama (Not interested in using chatgpt) and every command has just failed/died/not worked properly.

This has been the worst though

Any tips?

**Comment by ubuntuyeah** [comment]
This looks like an easy fix. I keep getting this with codellama for every other code snippet:

```
                                                                                                                                                                                                                                       
  Traceback (most recent call last):                                                                                                                                                                                                   
    File "/home/ubuntu/open-interpreter/interpreter/code_interpreters/subprocess_code_interpreter.py", line 63, in run                                                                                                               
      code = self.preprocess_code(code)                                                                                                                                                                                                
             ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                
    File "/home/ubuntu/open-interpreter/interpreter/code_interpreters/languages/python.py", line 15, in preprocess_code                                                                                                              
      return preprocess_python(code)                                                                                                                                                                                                   
             ^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                   
    File "/home/ubuntu/open-interpreter/interpreter/code_interpreters/languages/python.py", line 39, in preprocess_python                                                                                                            
      code = add_active_line_prints(code)                                                                                                                                                                                              
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                              
    File "/home/ubuntu/open-interpreter/interpreter/code_interpreters/languages/python.py", line 60, in add_active_line_prints                                                                                                       
      tree = ast.parse(code)                                                                                                                                                                                                           
             ^^^^^^^^^^^^^^^                                                                                                                                                                                                           
    File "/home/ubuntu/anaconda3/envs/python3115/lib/python3.11/ast.py", line 50, in parse                                                                                                                                           
      return compile(source, filename, mode, flags,                                                                                                                                                                                    
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                    
    File "<unknown>", line 11                                                                                                                                                                                                          
      ``                                                                                                                                                                                                                               
      ^                                                                                                                                                                                                                                
  SyntaxError: invalid syntax                                                                                                                                                                                                          
                                
```

**Comment by ericrallen** [comment]
Hey there, folks!

I’m going to close this one as stale for now. Local models are weird and we’ve made significant changes to how they work and how easy it is to find an run one that works for you and your hardware.
