### ISSUE TITLE
Crashes after upgrading to 1.7 when interpreter tries to write a code block

### ISSUE THREAD

**Issue by Bomx** [KillianLucas/open-interpreter#593]
### Describe the bug

OI crashes after upgrading to 1.7 when interpreter tries to write a code block, was working fine with the original version.

The error states:

Traceback (most recent call last):
  File "/home/ec2-user/.venv/bin/interpreter", line 8, in <module>
    sys.exit(cli())
  File "/home/ec2-user/.venv/lib/python3.10/site-packages/interpreter/core/core.py", line 21, in cli
    cli(self)
  File "/home/ec2-user/.venv/lib/python3.10/site-packages/interpreter/cli/cli.py", line 168, in cli
    interpreter.chat()
  File "/home/ec2-user/.venv/lib/python3.10/site-packages/interpreter/core/core.py", line 66, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "/home/ec2-user/.venv/lib/python3.10/site-packages/interpreter/core/core.py", line 87, in _streaming_chat
    yield from terminal_interface(self, message)
  File "/home/ec2-user/.venv/lib/python3.10/site-packages/interpreter/terminal_interface/terminal_interface.py", line 62, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "/home/ec2-user/.venv/lib/python3.10/site-packages/interpreter/core/core.py", line 95, in _streaming_chat
    yield from self._respond()
  File "/home/ec2-user/.venv/lib/python3.10/site-packages/interpreter/core/core.py", line 121, in _respond
    yield from respond(self)
  File "/home/ec2-user/.venv/lib/python3.10/site-packages/interpreter/core/respond.py", line 57, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "/home/ec2-user/.venv/lib/python3.10/site-packages/interpreter/llm/setup_openai_coding_llm.py", line 109, in coding_llm
    accumulated_deltas = merge_deltas(accumulated_deltas, delta)
  File "/home/ec2-user/.venv/lib/python3.10/site-packages/interpreter/utils/merge_deltas.py", line 18, in merge_deltas
    original[key] += value
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

### Reproduce

upgraded. Writes text and instructions but if you ask it to perform any code it crashes.

### Expected behavior

write code as it did originally

### Open Interpreter version

1.1

### Python version

3.10

### Operating System name and version

Amazon Linux

**Comment by OmiiiDev** [comment]
This happened to me as well

**Comment by ericrallen** [comment]
Hey there, @Bomx!

Your issue mentions the version of Open Interpeter as being `1.1`.

Could you reinstall the `open-interpeter` package, verify the issue still exists, run `interpeeter -—version`, and let us know what the version output is?

**Comment by TanmayDoesAI** [comment]
Updating should fix this, if this issue is still persistent kindly reopen the issue.
