### ISSUE TITLE
traceback for any input in conda environment on macos sonoma

### ISSUE THREAD

**Issue by rmanly** [KillianLucas/open-interpreter#621]
### Describe the bug

# Code-Llama Traceback

```
Finished downloading Code-Llama interface.                                                                             

Open Interpreter will require approval before running code.                                                            

Use interpreter -y to bypass this.                                                                                     

Press CTRL-C to exit.                                                                                                  
> set my computer to dark mode
Traceback (most recent call last):
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x111eb2710>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='open-procedures.replit.app', port=443): Max retries exceeded with url: /search/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111eb2710>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ryan/anaconda3/envs/oi/bin/interpreter", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/interpreter/core/core.py", line 21, in cli
    cli(self)
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/interpreter/cli/cli.py", line 168, in cli
    interpreter.chat()
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/interpreter/core/core.py", line 66, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/interpreter/core/core.py", line 87, in _streaming_chat
    yield from terminal_interface(self, message)
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/interpreter/terminal_interface/terminal_interface.py", line 62, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/interpreter/core/core.py", line 95, in _streaming_chat
    yield from self._respond()
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/interpreter/core/core.py", line 121, in _respond
    yield from respond(self)
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/interpreter/core/respond.py", line 24, in respond
    get_relevant_procedures(interpreter.messages[-2:])
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/interpreter/rag/get_relevant_procedures.py", line 12, in get_relevant_procedures
    relevant_procedures = requests.post(url, json=query).json()["procedures"]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='open-procedures.replit.app', port=443): Max retries exceeded with url: /search/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111eb2710>: Failed to establish a new connection: [Errno 61] Connection refused'))
ggml_metal_free: deallocating
```

# GPT-4 traceback

```
▌ Model set to GPT-4                                                                                                                                                         

Open Interpreter will require approval before running code.                                                                                                                    

Use interpreter -y to bypass this.                                                                                                                                             

Press CTRL-C to exit.                                                                                                                                                          
> what files are on my desktop

Traceback (most recent call last):
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x110f61990>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='open-procedures.replit.app', port=443): Max retries exceeded with url: /search/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x110f61990>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ryan/anaconda3/envs/oi/bin/interpreter", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/interpreter/core/core.py", line 21, in cli
    cli(self)
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/interpreter/cli/cli.py", line 168, in cli
    interpreter.chat()
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/interpreter/core/core.py", line 66, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/interpreter/core/core.py", line 87, in _streaming_chat
    yield from terminal_interface(self, message)
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/interpreter/terminal_interface/terminal_interface.py", line 62, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/interpreter/core/core.py", line 95, in _streaming_chat
    yield from self._respond()
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/interpreter/core/core.py", line 121, in _respond
    yield from respond(self)
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/interpreter/core/respond.py", line 24, in respond
    get_relevant_procedures(interpreter.messages[-2:])
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/interpreter/rag/get_relevant_procedures.py", line 12, in get_relevant_procedures
    relevant_procedures = requests.post(url, json=query).json()["procedures"]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/anaconda3/envs/oi/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='open-procedures.replit.app', port=443): Max retries exceeded with url: /search/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x110f61990>: Failed to establish a new connection: [Errno 61] Connection refused'))
```
(oi) 

### Reproduce

create conda environment on macos sonoma
install open-interpreter
attempt to use

### Expected behavior

output from program

### Open Interpreter version

0.1.7

### Python version

3.11.4

### Operating System name and version

macOS 14.0 (23A344)

**Comment by ericrallen** [comment]
Hey there, @rmanly!

Those error messages seem to point towards a failed connection to the Open Procedures app on Replit, but Open Interpreter no longer uses that.

Can you confirm if this is still an issue with the latest version of Open Interpreter?

**Comment by rmanly** [comment]
0.1.10 is working just fine.

Thanks!
