### ISSUE TITLE
Failed to install huggingface/TheBloke/CodeLlama-7B-Instruct-GGUF.  

### ISSUE THREAD

**Issue by enikqi** [KillianLucas/open-interpreter#626]
### Describe the bug

interpreter

●                                                                               

Welcome to Open Interpreter.                                                    

────────────────────────────────────────────────────────────────────────────────

▌ OpenAI API key not found                                                    

To use GPT-4 (recommended) please provide an OpenAI API key.                    

To use Code-Llama (free but less capable) press enter.                          

────────────────────────────────────────────────────────────────────────────────

OpenAI API key: 

▌ Switching to Code-Llama...                                                  

Tip: Run interpreter --local to automatically use Code-Llama.                   

────────────────────────────────────────────────────────────────────────────────

Open Interpreter will use Code Llama for local execution. Use your arrow keys to
set up the model.                                                               

[?] Parameter count (smaller is faster, larger is more capable): 7B
 > 7B
   13B
   34B

▌ Model set to HUGGINGFACE/THEBLOKE/CODELLAMA-7B-INSTRUCT-GGUF                

[?] Quality (smaller is faster, larger is more capable): Small | Size: 2.6 GB, Estimated RAM usage: 5.1 GB
 > Small | Size: 2.6 GB, Estimated RAM usage: 5.1 GB
   Medium | Size: 3.8 GB, Estimated RAM usage: 6.3 GB
   Large | Size: 6.7 GB, Estimated RAM usage: 9.2 GB
   See More

[?] Use GPU? (Large models might crash on GPU, but will run more quickly) (...: y

Model found at /Users/endritnikqi/Library/Application Support/Open              
Interpreter/models/codellama-7b-instruct.Q2_K.gguf                              
Traceback (most recent call last):
  File "/Users/endritnikqi/Library/Python/3.10/lib/python/site-packages/interpreter/llm/setup_text_llm.py", line 45, in setup_text_llm
    return setup_local_text_llm(interpreter)
  File "/Users/endritnikqi/Library/Python/3.10/lib/python/site-packages/interpreter/llm/setup_local_text_llm.py", line 248, in setup_local_text_llm
    llama_2 = Llama(**params)
  File "/Users/endritnikqi/Library/Python/3.10/lib/python/site-packages/llama_cpp/llama.py", line 377, in __init__
    assert self.ctx is not None
AssertionError

▌ Failed to install huggingface/TheBloke/CodeLlama-7B-Instruct-GGUF.          

Common Fixes: You can follow our simple setup docs at the link below to resolve 
common errors.                                                                  

▌ https://github.com/KillianLucas/open-interpreter/tree/main/docs             

If you've tried that and you're still getting an error, we have likely not built
the proper huggingface/TheBloke/CodeLlama-7B-Instruct-GGUF support for your     
system.                                                                         

( Running language models locally is a difficult task! If you have insight into 
the best way to implement this across platforms/architectures, please join the  
Open Interpreter community Discord and consider contributing the project's      
development.                                                                    

Traceback (most recent call last):
  File "/Users/endritnikqi/Library/Python/3.10/lib/python/site-packages/interpreter/llm/setup_text_llm.py", line 45, in setup_text_llm
    return setup_local_text_llm(interpreter)
  File "/Users/endritnikqi/Library/Python/3.10/lib/python/site-packages/interpreter/llm/setup_local_text_llm.py", line 248, in setup_local_text_llm
    llama_2 = Llama(**params)
  File "/Users/endritnikqi/Library/Python/3.10/lib/python/site-packages/llama_cpp/llama.py", line 377, in __init__
    assert self.ctx is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/endritnikqi/Library/Python/3.10/bin/interpreter", line 8, in <module>
    sys.exit(cli())
  File "/Users/endritnikqi/Library/Python/3.10/lib/python/site-packages/interpreter/core/core.py", line 21, in cli
    cli(self)
  File "/Users/endritnikqi/Library/Python/3.10/lib/python/site-packages/interpreter/cli/cli.py", line 168, in cli
    interpreter.chat()
  File "/Users/endritnikqi/Library/Python/3.10/lib/python/site-packages/interpreter/core/core.py", line 66, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "/Users/endritnikqi/Library/Python/3.10/lib/python/site-packages/interpreter/core/core.py", line 80, in _streaming_chat
    self._llm = setup_llm(self)
  File "/Users/endritnikqi/Library/Python/3.10/lib/python/site-packages/interpreter/llm/setup_llm.py", line 20, in setup_llm
    text_llm = setup_text_llm(interpreter)
  File "/Users/endritnikqi/Library/Python/3.10/lib/python/site-packages/interpreter/llm/setup_text_llm.py", line 57, in setup_text_llm
    raise Exception("Architecture not yet supported for local LLM inference. Please run `interpreter` to connect to a cloud model, then try `--local` again in a few days.")
Exception: Architecture not yet supported for local LLM inference. Please run `interpreter` to connect to a cloud model, then try `--local` again in a few 

### Reproduce

Python 3.10.4

### Expected behavior

i tried all different ways but still the same thing it's happening, need help from you

### Open Interpreter version

0.1.7

### Python version

Python 3.10.4

### Operating System name and version

macOS 13.2.1

### Additional context

i can not install and run interpreter --local

**Comment by ADELBYTES** [comment]
same issue here while using mistral-7b

**Comment by injcksn** [comment]
same here with minstral-7b too

**Comment by ericrallen** [comment]
Hey there, folks!

Local models are handled differently now, so I’m going to close this one as stale for now, but feel free to reopen it if you still experience the same issue in the latest version.

**Comment by KeysMENG** [comment]
same issue...
