### ISSUE TITLE
mistral does not support ?

### ISSUE THREAD

**Issue by hvacking** [KillianLucas/open-interpreter#640]
### Describe the bug

when i press 'enter' to run mistral locally , system give the error message '
Traceback (most recent call last):
  File "/Users/liulan/opt/anaconda3/envs/openinterpreter/lib/python3.11/site-packages/interpreter/llm/setup_text_llm.py", line 45, in setup_text_llm
    return setup_local_text_llm(interpreter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liulan/opt/anaconda3/envs/openinterpreter/lib/python3.11/site-packages/interpreter/llm/setup_local_text_llm.py", line 40, in setup_local_text_llm
    ooba_llm = ooba.llm(path, verbose=interpreter.debug_mode)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liulan/opt/anaconda3/envs/openinterpreter/lib/python3.11/site-packages/ooba/llm.py", line 105, in __init__
    raise Exception("Server took too long to start")
Exception: Server took too long to start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/liulan/opt/anaconda3/envs/openinterpreter/bin/interpreter", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/liulan/opt/anaconda3/envs/openinterpreter/lib/python3.11/site-packages/interpreter/core/core.py", line 26, in cli
    cli(self)
  File "/Users/liulan/opt/anaconda3/envs/openinterpreter/lib/python3.11/site-packages/interpreter/cli/cli.py", line 254, in cli
    interpreter.chat()
  File "/Users/liulan/opt/anaconda3/envs/openinterpreter/lib/python3.11/site-packages/interpreter/core/core.py", line 88, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "/Users/liulan/opt/anaconda3/envs/openinterpreter/lib/python3.11/site-packages/interpreter/core/core.py", line 102, in _streaming_chat
    self._llm = setup_llm(self)
                ^^^^^^^^^^^^^^^
  File "/Users/liulan/opt/anaconda3/envs/openinterpreter/lib/python3.11/site-packages/interpreter/llm/setup_llm.py", line 20, in setup_llm
    text_llm = setup_text_llm(interpreter)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liulan/opt/anaconda3/envs/openinterpreter/lib/python3.11/site-packages/interpreter/llm/setup_text_llm.py", line 56, in setup_text_llm
    raise Exception("Architecture not yet supported for local LLM inference via `Oobabooga`. Please run `interpreter` to connect to a cloud model.")
Exception: Architecture not yet supported for local LLM inference via `Oobabooga`. Please run `interpreter` to connect to a cloud model.

### Reproduce

1. interpreter -y
2. press 'enter' --To use GPT-4 (recommended) please provide an OpenAI API key.                                                                                                     To use Mistral-7B (free but less capable) press enter.    
3.OpenAI API key: ▌ Switching to Mistral-7B...                                                                                                                                   Tip: Run interpreter --local to automatically use Mistral-7B. 
4. (Running language models locally is a difficult task! If you have insight into the best way to implement this across platforms/architectures, please join the    
Open Interpreter community Discord, or the Oobabooga community Discord, and consider contributing the development of these projects.)                            

Traceback (most recent call last):
  File "/Users/liulan/opt/anaconda3/envs/openinterpreter/lib/python3.11/site-packages/interpreter/llm/setup_text_llm.py", line 45, in setup_text_llm
    return setup_local_text_llm(interpreter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liulan/opt/anaconda3/envs/openinterpreter/lib/python3.11/site-packages/interpreter/llm/setup_local_text_llm.py", line 40, in setup_local_text_llm
    ooba_llm = ooba.llm(path, verbose=interpreter.debug_mode)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liulan/opt/anaconda3/envs/openinterpreter/lib/python3.11/site-packages/ooba/llm.py", line 105, in __init__
    raise Exception("Server took too long to start")
Exception: Server took too long to start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/liulan/opt/anaconda3/envs/openinterpreter/bin/interpreter", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/liulan/opt/anaconda3/envs/openinterpreter/lib/python3.11/site-packages/interpreter/core/core.py", line 26, in cli
    cli(self)
  File "/Users/liulan/opt/anaconda3/envs/openinterpreter/lib/python3.11/site-packages/interpreter/cli/cli.py", line 254, in cli
    interpreter.chat()
  File "/Users/liulan/opt/anaconda3/envs/openinterpreter/lib/python3.11/site-packages/interpreter/core/core.py", line 88, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "/Users/liulan/opt/anaconda3/envs/openinterpreter/lib/python3.11/site-packages/interpreter/core/core.py", line 102, in _streaming_chat
    self._llm = setup_llm(self)
                ^^^^^^^^^^^^^^^
  File "/Users/liulan/opt/anaconda3/envs/openinterpreter/lib/python3.11/site-packages/interpreter/llm/setup_llm.py", line 20, in setup_llm
    text_llm = setup_text_llm(interpreter)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liulan/opt/anaconda3/envs/openinterpreter/lib/python3.11/site-packages/interpreter/llm/setup_text_llm.py", line 56, in setup_text_llm
    raise Exception("Architecture not yet supported for local LLM inference via `Oobabooga`. Please run `interpreter` to connect to a cloud model.")
Exception: Architecture not yet supported for local LLM inference via `Oobabooga`. Please run `interpreter` to connect to a cloud model.

### Expected behavior

give us suggestions how to run mistral

### Screenshots

<img width="995" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/28031945/815b4c4d-dc6d-4731-9b82-da013018baf3">

### Open Interpreter version

0.1.9

### Python version

3.11.4

### Operating System name and version

mac os m1

**Comment by pumbinha** [comment]
Same here with Mac OS Ventura with intel CPU

**Comment by ericrallen** [comment]
Hey there, folks!

I think this should be fixed with the new change to LM Studio for underlying local model support.

I'm going to close this one for now, but please reopen it if you're still experience the same issue with the latest version of Open Interpreter.
