### ISSUE TITLE
Cannot run interpreter in terminal

### ISSUE THREAD

**Issue by WangHaoranRobin** [KillianLucas/open-interpreter#641]
### Describe the bug

Cannot start interpreter in my terminal after installation. 
here is the error output:
```
❯ interpreter
thread '<unnamed>' panicked at 'Encoder and decoder must be of equal length; maybe you had duplicate token indices in your encoder?', src/lib.rs:458:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/opt/homebrew/bin/interpreter", line 5, in <module>
    from interpreter import cli
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/__init__.py", line 1, in <module>
    from .interpreter import Interpreter
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/interpreter.py", line 35, in <module>
    import litellm
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/__init__.py", line 224, in <module>
    from .utils import (
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/utils.py", line 11, in <module>
    encoding = tiktoken.get_encoding("cl100k_base")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/tiktoken/registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/tiktoken/core.py", line 50, in __init__
    self._core_bpe = _tiktoken.CoreBPE(mergeable_ranks, special_tokens, pat_str)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: Encoder and decoder must be of equal length; maybe you had duplicate token indices in your encoder?
```

### Reproduce

start interpreter in terminal

### Expected behavior

interpreter interactive mode starts

### Open Interpreter version

0.1.9

### Python version

3.10.13

### Operating System name and version

macOS 13.5

**Comment by leifktaylor** [comment]
This likely an issue caused by lack of version pinning for `litellm` module.
Can you rerun this command after exporting `RUST_BACKTRACE=1` and post the output for further diagnosis?

e.g. `export RUST_BACKTRACE=1`

**Comment by ericrallen** [comment]
I'm going to close this one as stale for now, but please feel encouraged to reopen it if you attempt the suggestion provided and want to continue the discussion of the issue or have more details to provide.
