### ISSUE TITLE
No access to Open AI key and Open Interpreter Don't give to change API

### ISSUE THREAD

**Issue by AgolarX** [KillianLucas/open-interpreter#650]
### Describe the bug

I am a new member for here, And I'm not a coding expert as like you guys, So, if possible please help me. 

when I first open open interpreter and after I enter my API key it says,

openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.

Then I thought it's something to with my Open API key and then I delete my old key and then I create new Open API key. 

Then I uninstall anaconda and python and then reinstall it, then I follow same steps as previous,
1. create a virtual environment and install python
2. Install open-interpreter

then I enter "interpreter" to start open-interpreter, but then they don't give me the option to change my key 

▌ Model set to GPT-4

Open Interpreter will require approval before running code.

Use interpreter -y to bypass this.

Press CTRL-C to exit.

>

It only shows this,

then when I try to use interpreter I got **same error as previous as**,

openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.

It's true that now my old Open API key is not working because I delete it, but I don't understand how I got same error, 

Not only that **now I want to change my API key and I tried everything But I can't solve this problem**, Please help me, to solve this,

### Reproduce

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Anaconda\envs\opengpt\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Anaconda\envs\opengpt\Lib\site-packages\interpreter\core\core.py", line 26, in cli
    cli(self)
  File "C:\Anaconda\envs\opengpt\Lib\site-packages\interpreter\cli\cli.py", line 254, in cli
    interpreter.chat()
  File "C:\Anaconda\envs\opengpt\Lib\site-packages\interpreter\core\core.py", line 88, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "C:\Anaconda\envs\opengpt\Lib\site-packages\interpreter\core\core.py", line 109, in _streaming_chat
    yield from terminal_interface(self, message)
  File "C:\Anaconda\envs\opengpt\Lib\site-packages\interpreter\terminal_interface\terminal_interface.py", line 62, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "C:\Anaconda\envs\opengpt\Lib\site-packages\interpreter\core\core.py", line 117, in _streaming_chat
    yield from self._respond()
  File "C:\Anaconda\envs\opengpt\Lib\site-packages\interpreter\core\core.py", line 143, in _respond
    yield from respond(self)
  File "C:\Anaconda\envs\opengpt\Lib\site-packages\interpreter\core\respond.py", line 44, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "C:\Anaconda\envs\opengpt\Lib\site-packages\interpreter\llm\setup_openai_coding_llm.py", line 94, in coding_llm
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\envs\opengpt\Lib\site-packages\litellm\utils.py", line 792, in wrapper
    raise e
  File "C:\Anaconda\envs\opengpt\Lib\site-packages\litellm\utils.py", line 751, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\envs\opengpt\Lib\site-packages\litellm\timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\envs\opengpt\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\envs\opengpt\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Anaconda\envs\opengpt\Lib\site-packages\litellm\timeout.py", line 42, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\envs\opengpt\Lib\site-packages\litellm\main.py", line 1183, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Anaconda\envs\opengpt\Lib\site-packages\litellm\utils.py", line 2959, in exception_type
    raise e
  File "C:\Anaconda\envs\opengpt\Lib\site-packages\litellm\utils.py", line 2355, in exception_type
    raise original_exception
  File "C:\Anaconda\envs\opengpt\Lib\site-packages\litellm\main.py", line 441, in completion
    raise e
  File "C:\Anaconda\envs\opengpt\Lib\site-packages\litellm\main.py", line 423, in completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\envs\opengpt\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\envs\opengpt\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\envs\opengpt\Lib\site-packages\openai\api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\envs\opengpt\Lib\site-packages\openai\api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "C:\Anaconda\envs\opengpt\Lib\site-packages\openai\api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.

### Expected behavior

Change new API key and Access GPT 4 model

### Open Interpreter version

0.1.9

### Python version

3.11.0

### Operating System name and version

Windows 10

**Comment by ericrallen** [comment]
You might want to look into [this comment about about the `gpt-4` notice](https://github.com/KillianLucas/open-interpreter/issues/164#issuecomment-1711992453) on #164.

Your `OPENAI_API_KEY` is an environment variable and you can [update it via `setx`](https://github.com/KillianLucas/open-interpreter/issues/349#issuecomment-1720368213).

**Comment by AgolarX** [comment]
hello ericrallen how are you doing, now I understand the issue tnx brother you are truly life savor
