### ISSUE TITLE
oi can not run mistral 

### ISSUE THREAD

**Issue by hvacking** [KillianLucas/open-interpreter#660]
### Describe the bug

 interpreter -y
Welcome to Open Interpreter.                                                                                  

──────────────────────────────────────────────────────────────────────────────────────────────────────────────

▌ OpenAI API key not found                                                                                  

To use GPT-4 (recommended) please provide an OpenAI API key.                                                  

To use Mistral-7B (free but less capable) press enter.                                                        

──────────────────────────────────────────────────────────────────────────────────────────────────────────────

OpenAI API key: 

▌ Switching to Mistral-7B...                                                                                

Tip: Run interpreter --local to automatically use Mistral-7B.                                                 

──────────────────────────────────────────────────────────────────────────────────────────────────────────────

Open Interpreter will use Mistral 7B for local execution.                                                     

▌ Warning: Local LLM usage is an experimental, unstable feature.                                            

Located '/Users/liulan/.ooba/models/mistral-7b-instruct-v0.1.Q4_0.gguf', which has already been downloaded.

Getting started...
Server took too long to start
Traceback (most recent call last):
  File "/Users/liulan/opt/anaconda3/envs/oi/lib/python3.10/site-packages/interpreter/llm/setup_text_llm.py", line 45, in setup_text_llm
    return setup_local_text_llm(interpreter)
  File "/Users/liulan/opt/anaconda3/envs/oi/lib/python3.10/site-packages/interpreter/llm/setup_local_text_llm.py", line 40, in setup_local_text_llm
    ooba_llm = ooba.llm(path, verbose=interpreter.debug_mode)
  File "/Users/liulan/opt/anaconda3/envs/oi/lib/python3.10/site-packages/ooba/llm.py", line 105, in __init__
    raise Exception("Server took too long to start")
Exception: Server took too long to start

▌ Failed to install huggingface/TheBloke/Mistral-7B-Instruct-v0.1-GGUF.                                     

We have likely not built the proper huggingface/TheBloke/Mistral-7B-Instruct-v0.1-GGUF support for your       
system.                                                                                                       

(Running language models locally is a difficult task! If you have insight into the best way to implement this 
across platforms/architectures, please join the Open Interpreter community Discord, or the Oobabooga community
Discord, and consider contributing the development of these projects.)                                        

Traceback (most recent call last):
  File "/Users/liulan/opt/anaconda3/envs/oi/lib/python3.10/site-packages/interpreter/llm/setup_text_llm.py", line 45, in setup_text_llm
    return setup_local_text_llm(interpreter)
  File "/Users/liulan/opt/anaconda3/envs/oi/lib/python3.10/site-packages/interpreter/llm/setup_local_text_llm.py", line 40, in setup_local_text_llm
    ooba_llm = ooba.llm(path, verbose=interpreter.debug_mode)
  File "/Users/liulan/opt/anaconda3/envs/oi/lib/python3.10/site-packages/ooba/llm.py", line 105, in __init__
    raise Exception("Server took too long to start")
Exception: Server took too long to start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/liulan/opt/anaconda3/envs/oi/bin/interpreter", line 8, in <module>
    sys.exit(cli())
  File "/Users/liulan/opt/anaconda3/envs/oi/lib/python3.10/site-packages/interpreter/core/core.py", line 26, in cli
    cli(self)
  File "/Users/liulan/opt/anaconda3/envs/oi/lib/python3.10/site-packages/interpreter/cli/cli.py", line 254, in cli
    interpreter.chat()
  File "/Users/liulan/opt/anaconda3/envs/oi/lib/python3.10/site-packages/interpreter/core/core.py", line 88, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "/Users/liulan/opt/anaconda3/envs/oi/lib/python3.10/site-packages/interpreter/core/core.py", line 102, in _streaming_chat
    self._llm = setup_llm(self)
  File "/Users/liulan/opt/anaconda3/envs/oi/lib/python3.10/site-packages/interpreter/llm/setup_llm.py", line 20, in setup_llm
    text_llm = setup_text_llm(interpreter)
  File "/Users/liulan/opt/anaconda3/envs/oi/lib/python3.10/site-packages/interpreter/llm/setup_text_llm.py", line 56, in setup_text_llm
    raise Exception("Architecture not yet supported for local LLM inference via `Oobabooga`. Please run `interpreter` to connect to a cloud model.")
Exception: Architecture not yet supported for local LLM inference via `Oobabooga`. Please run `interpreter` to connect to a cloud model

### Reproduce

1.  interpreter -y
2. error occurs

### Expected behavior

run OI with local llm-mistal

### Screenshots

<img width="903" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/28031945/756e54a1-3e6d-48c2-a965-283baac13891">

### Open Interpreter version

0.1.10

### Python version

3.10.10

### Operating System name and version

mac os m1

**Comment by ADELBYTES** [comment]
same issue here..

**Comment by mohcineelharras** [comment]
same here

**Comment by pursuitsky** [comment]
same here

**Comment by peisheng** [comment]
me too

**Comment by benjaminjackson** [comment]
Same

**Comment by sagar290** [comment]
Same here
Ryzen 5 7600x

**Comment by rastinder** [comment]
same

**Comment by bmwhite1611** [comment]
SAME...lame...

**Comment by ericrallen** [comment]
I understand the frustration, but please do not open duplicate issues.

You already opened #640 about this.

Duplicate issues are just noise, and it is much harder to triage and resolve issues when there is more noise.

Closing this as a duplicate.
