### ISSUE TITLE
MacOS 11.2.3 "not built the support for your system"

### ISSUE THREAD

**Issue by injcksn** [KillianLucas/open-interpreter#667]
### Describe the bug

I  can't get open interpreter to work on my mac book. I have Python 3.11 installed and I run the interpreter command in my terminal

### Reproduce

●                                                                               

Welcome to Open Interpreter.                                                    

────────────────────────────────────────────────────────────────────────────────

▌ OpenAI API key not found                                                    

To use GPT-4 (recommended) please provide an OpenAI API key.                    

To use Mistral-7B (free but less capable) press enter.                          

────────────────────────────────────────────────────────────────────────────────

OpenAI API key: 

▌ Switching to Mistral-7B...                                                  

Tip: Run interpreter --local to automatically use Mistral-7B.                   

────────────────────────────────────────────────────────────────────────────────

Open Interpreter will use Mistral 7B for local execution.                       

▌ Warning: Local LLM usage is an experimental, unstable feature.              

Located '/Users/bot/.ooba/models/mistral-7b-instruct-v0.1.Q4_0.gguf', which has already been downloaded.

Getting started...

Server took too long to start
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/llm/setup_text_llm.py", line 45, in setup_text_llm
    return setup_local_text_llm(interpreter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/llm/setup_local_text_llm.py", line 40, in setup_local_text_llm
    ooba_llm = ooba.llm(path, verbose=interpreter.debug_mode)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ooba/llm.py", line 105, in __init__
    raise Exception("Server took too long to start")
Exception: Server took too long to start

▌ Failed to install huggingface/TheBloke/Mistral-7B-Instruct-v0.1-GGUF.       

We have likely not built the proper                                             
huggingface/TheBloke/Mistral-7B-Instruct-v0.1-GGUF support for your system.     

(Running language models locally is a difficult task! If you have insight into  
the best way to implement this across platforms/architectures, please join the  
Open Interpreter community Discord, or the Oobabooga community Discord, and     
consider contributing the development of these projects.)                       

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/llm/setup_text_llm.py", line 45, in setup_text_llm
    return setup_local_text_llm(interpreter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/llm/setup_local_text_llm.py", line 40, in setup_local_text_llm
    ooba_llm = ooba.llm(path, verbose=interpreter.debug_mode)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ooba/llm.py", line 105, in __init__
    raise Exception("Server took too long to start")
Exception: Server took too long to start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/interpreter", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/core/core.py", line 26, in cli
    cli(self)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/cli/cli.py", line 254, in cli
    interpreter.chat()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/core/core.py", line 88, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/core/core.py", line 102, in _streaming_chat
    self._llm = setup_llm(self)
                ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/llm/setup_llm.py", line 20, in setup_llm
    text_llm = setup_text_llm(interpreter)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/llm/setup_text_llm.py", line 56, in setup_text_llm
    raise Exception("Architecture not yet supported for local LLM inference via `Oobabooga`. Please run `interpreter` to connect to a cloud model.")
Exception: Architecture not yet supported for local LLM inference via `Oobabooga`. Please run `interpreter` to connect to a cloud model.

### Expected behavior

I expected the LLM to link up

### Open Interpreter version

0.1.10

### Python version

3.11.5

### Operating System name and version

MacOS 11.2.3

**Comment by mrvic** [comment]
HERE IS SOLUTION: 
https://github.com/KillianLucas/open-interpreter/issues/636#issuecomment-1771001980

**Comment by Notnaton** [comment]
Ooba bug
@ericrallen I believe we can close this one, as Open-interpreter use LM Studio now.

**Comment by ericrallen** [comment]
Good catch.

Thanks, @Notnaton!
