### ISSUE TITLE
litellm.exceptions.APIError: argument of type 'bool' is not iterable

### ISSUE THREAD

**Issue by krrqiw356** [KillianLucas/open-interpreter#726]
### Describe the bug

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "/Users/kongbai/miniconda3/envs/sys/lib/python3.11/site-packages/litellm/main.py", line 447, in completion
    raise e
  File "/Users/kongbai/miniconda3/envs/sys/lib/python3.11/site-packages/litellm/main.py", line 429, in completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kongbai/miniconda3/envs/sys/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kongbai/miniconda3/envs/sys/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/Users/kongbai/miniconda3/envs/sys/lib/python3.11/site-packages/openai/api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kongbai/miniconda3/envs/sys/lib/python3.11/site-packages/openai/api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "/Users/kongbai/miniconda3/envs/sys/lib/python3.11/site-packages/openai/api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kongbai/miniconda3/envs/sys/lib/python3.11/site-packages/openai/api_requestor.py", line 423, in handle_error_response
    if "internal_message" in error_data:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'bool' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kongbai/miniconda3/envs/sys/bin/interpreter", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/kongbai/miniconda3/envs/sys/lib/python3.11/site-packages/interpreter/core/core.py", line 26, in cli
    cli(self)
  File "/Users/kongbai/miniconda3/envs/sys/lib/python3.11/site-packages/interpreter/cli/cli.py", line 254, in cli
    interpreter.chat()
  File "/Users/kongbai/miniconda3/envs/sys/lib/python3.11/site-packages/interpreter/core/core.py", line 88, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "/Users/kongbai/miniconda3/envs/sys/lib/python3.11/site-packages/interpreter/core/core.py", line 109, in _streaming_chat
    yield from terminal_interface(self, message)
  File "/Users/kongbai/miniconda3/envs/sys/lib/python3.11/site-packages/interpreter/terminal_interface/terminal_interface.py", line 62, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "/Users/kongbai/miniconda3/envs/sys/lib/python3.11/site-packages/interpreter/core/core.py", line 117, in _streaming_chat
    yield from self._respond()
  File "/Users/kongbai/miniconda3/envs/sys/lib/python3.11/site-packages/interpreter/core/core.py", line 143, in _respond
    yield from respond(self)
  File "/Users/kongbai/miniconda3/envs/sys/lib/python3.11/site-packages/interpreter/core/respond.py", line 44, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "/Users/kongbai/miniconda3/envs/sys/lib/python3.11/site-packages/interpreter/llm/setup_openai_coding_llm.py", line 94, in coding_llm
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kongbai/miniconda3/envs/sys/lib/python3.11/site-packages/litellm/utils.py", line 798, in wrapper
    raise e
  File "/Users/kongbai/miniconda3/envs/sys/lib/python3.11/site-packages/litellm/utils.py", line 757, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kongbai/miniconda3/envs/sys/lib/python3.11/site-packages/litellm/timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kongbai/miniconda3/envs/sys/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/kongbai/miniconda3/envs/sys/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/kongbai/miniconda3/envs/sys/lib/python3.11/site-packages/litellm/timeout.py", line 42, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kongbai/miniconda3/envs/sys/lib/python3.11/site-packages/litellm/main.py", line 1195, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/Users/kongbai/miniconda3/envs/sys/lib/python3.11/site-packages/litellm/utils.py", line 3173, in exception_type
    raise e
  File "/Users/kongbai/miniconda3/envs/sys/lib/python3.11/site-packages/litellm/utils.py", line 3155, in exception_type
    raise APIError(status_code=500, message=str(original_exception), llm_provider=custom_llm_provider, model=model)
litellm.exceptions.APIError: argument of type 'bool' is not iterable

### Reproduce

Upon installation, when entering the OpenAI API key and running the interpreter, everything proceeds smoothly. However, an exception occurs and the program terminates upon input.

### Expected behavior

Upon installation, when entering the OpenAI API key and running the interpreter, everything proceeds smoothly. However, an exception occurs and the program terminates upon input.

### Open Interpreter version

0.1.10

### Python version

Python 3.11.4

### Operating System name and version

macos 14.0

**Comment by ishaan-jaff** [comment]
how can I repro this - what llm are you calling ?

**Comment by krrqiw356** [comment]
> how can I repro this - what llm are you calling ?

I just installed and used the 3.5 model.

**Comment by MikeBirdTech** [comment]
Closing this stale issue. Please create a new issue if the problem is not resolved or explained in the documentation. Thanks!
