### ISSUE TITLE
how to solve this problem? I've read all the issues but nothing can solve this problem. .

### ISSUE THREAD

**Issue by zixingonline** [KillianLucas/open-interpreter#739]
### Describe the bug

My code:
`interpreter.chat("Please summarize this article：https://about.fb.com/news/2023/08/code-llama-ai-for-coding/")
interpreter.chat()`

Report an error:
`Exception in thread Thread-117 (handle_stream_output):
Traceback (most recent call last):
  File "C:\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\john\AppData\Roaming\Python\Python311\site-packages\interpreter\code_interpreters\subprocess_code_interpreter.py", line 121, in handle_stream_output
    for line in iter(stream.readline, ""):
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 870: illegal multibyte sequence`

![1699429214217](https://github.com/KillianLucas/open-interpreter/assets/51315718/8f9738f5-10fe-4154-a463-f8b029f2a3aa)

### Reproduce

`interpreter.chat("Please summarize this article：https://about.fb.com/news/2023/08/code-llama-ai-for-coding/")
interpreter.chat()`

### Expected behavior

..

### Open Interpreter version

0.1.11

### Python version

Python 3.11.4

### Operating System name and version

window10

**Comment by ericrallen** [comment]
Hey there, @zixingonline!

This looks like an issue that was reported previously (#446), but the reporter couldn’t verify it for us.

Thanks for reporting that it is still an issue with the current version of Open Interpreter.

It looks like we might need right sure we’re using the right encoding.

**Comment by Anthonyg5005** [comment]
I often get this or similar "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 715: invalid start byte"
code still runs but the model thinks there's an error in the code even if it's working fine

**Comment by ericrallen** [comment]
Hey there, folks!

Could someone who has this issue check out #742 to see if it resolves this issue?

**Comment by UlyssesWu** [comment]
> Please summarize this article：https://about.fb.com/news/2023/08/code-llama-ai-for-coding/

@ericrallen 

It seems still happens on v0.1.16.

```
File
"Python\Python311\Lib\site-packages\interpreter\core\code_interpreters\subprocess_code_interpreter.py", line 127, in handle_stream_output
    for line in iter(stream.readline, ""):
UnicodeDecodeError: 'gbk' codec can't decode byte 0x9d in position 1148: illegal multibyte sequence
```
