### ISSUE TITLE
Unable to operate

### ISSUE THREAD

**Issue by a554878526** [KillianLucas/open-interpreter#740]
### Describe the bug

I type interpreter -y prompt
` A new version of Open Interpreter is available.
 Please run: pip install --upgrade open-interpreter`

Update will still prompt
An error is reported after entering the `session`

```
Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python312\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python312\Lib\site-packages\interpreter\core\core.py", line 22, in cli
    cli(self)
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python312\Lib\site-packages\interpreter\cli\cli.py", line 254, in cli
    interpreter.chat()
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python312\Lib\site-packages\interpreter\core\core.py", line 76, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python312\Lib\site-packages\interpreter\core\core.py", line 97, in _streaming_chat
    yield from terminal_interface(self, message)
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python312\Lib\site-packages\interpreter\terminal_interface\terminal_interface.py", line 62, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python312\Lib\site-packages\interpreter\core\core.py", line 105, in _streaming_chat
    yield from self._respond()
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python312\Lib\site-packages\interpreter\core\core.py", line 131, in _respond
    yield from respond(self)
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python312\Lib\site-packages\interpreter\core\respond.py", line 61, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python312\Lib\site-packages\interpreter\llm\setup_openai_coding_llm.py", line 94, in coding_llm
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\utils.py", line 792, in wrapper
    raise e
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\utils.py", line 751, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\timeout.py", line 42, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\main.py", line 1183, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\utils.py", line 2959, in exception_type
    raise e
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\utils.py", line 2355, in exception_type
    raise original_exception
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\main.py", line 441, in completion
    raise e
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\main.py", line 423, in completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python312\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python312\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python312\Lib\site-packages\openai\api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python312\Lib\site-packages\openai\api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python312\Lib\site-packages\openai\api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.

```

### Reproduce

no

### Expected behavior

no

### Screenshots

![image](https://github.com/KillianLucas/open-interpreter/assets/70568691/2612c82b-9b16-4204-a419-8c75db0c472c)

### Open Interpreter version

0.1.8

### Python version

3.12.0

### Operating System name and version

window 10

**Comment by ericrallen** [comment]
Hey there, @a554878526!

It looks like you’re running an older version do Open Interpreter on an unsupported version of Python.

Could you try downgrading to Python 3.11 and upgrading to the latest Open Interpreter?

**Comment by a554878526** [comment]
> 嘿，@a554878526！
> 
> 看起来您正在不受支持的 Python 版本上运行旧版本的 Open Interpreter。
> 
> 您可以尝试降级到 Python 3.11 并升级到最新的 Open Interpreter 吗？

I downgraded Python to 3.11.0 open-interpreter and upgraded to 0.1.11 and still got this error

```
Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 24, in cli
    cli(self)
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\cli\cli.py", line 246, in cli
    interpreter.chat()
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 84, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 104, in _streaming_chat
    yield from terminal_interface(self, message)
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\terminal_interface\terminal_interface.py", line 91, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 112, in _streaming_chat
    yield from self._respond()
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 147, in _respond
    yield from respond(self)
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\respond.py", line 45, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\llm\setup_openai_coding_llm.py", line 114, in coding_llm
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 962, in wrapper
    raise e
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 899, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\timeout.py", line 42, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\main.py", line 1403, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 3574, in exception_type
    raise e
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 2885, in exception_type
    raise original_exception
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\main.py", line 509, in completion
    raise e
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\main.py", line 491, in completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.

```

**Comment by ericrallen** [comment]
Ah, I missed the final error message.

This is covered in our [Commonly Faced Issues](https://github.com/KillianLucas/open-interpreter/issues/164#issuecomment-1711992453).

Your OpenAI account needs to have prepaid billing setup for using the `gpt-4` model via the API.

**Comment by ericrallen** [comment]
I’m going to close this one as a duplicate. Please reopen it if you follow the instructions for the `gpt-4` model and still experience this issue.

**Comment by a554878526** [comment]
Hi buddy I just opened a gpt4 account and now prompt me for this


```
Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 492, in _make_request
    raise new_e
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 468, in _make_request
    self._validate_conn(conn)
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 1097, in _validate_conn
    conn.connect()
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x00000205DDF4EDD0>, 'Connection to api.openai.com timed out. (connect timeout=600)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 875, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 875, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 845, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000205DDF4EDD0>, 'Connection to api.openai.com timed out. (connect timeout=600)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 606, in request_raw
    result = _thread_context.session.request(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000205DDF4EDD0>, 'Connection to api.openai.com timed out. (connect timeout=600)'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 24, in cli
    cli(self)
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\cli\cli.py", line 246, in cli
    interpreter.chat()
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 84, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 104, in _streaming_chat
    yield from terminal_interface(self, message)
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\terminal_interface\terminal_interface.py", line 91, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 112, in _streaming_chat
    yield from self._respond()
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 147, in _respond
    yield from respond(self)
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\respond.py", line 45, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\llm\setup_openai_coding_llm.py", line 114, in coding_llm
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 962, in wrapper
    raise e
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 899, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\timeout.py", line 42, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\main.py", line 1403, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 3574, in exception_type
    raise e
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 2885, in exception_type
    raise original_exception
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\main.py", line 509, in completion
    raise e
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\main.py", line 491, in completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 289, in request
    result = self.request_raw(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 617, in request_raw
    raise error.Timeout("Request timed out: {}".format(e)) from e
openai.error.Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000205DDF4EDD0>, 'Connection to api.openai.com timed out. (connect timeout=600)'))
```



![image](https://github.com/KillianLucas/open-interpreter/assets/70568691/fdf4a573-4b1d-40f2-a8b3-d0dbdfccfa93)
