### ISSUE TITLE
Unable to access GPT-4 model

### ISSUE THREAD

**Issue by a554878526** [KillianLucas/open-interpreter#743]
### Describe the bug

I opened the chat4 account as you asked. Now prompt me for this

```
Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 24, in cli
    cli(self)
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\cli\cli.py", line 246, in cli
    interpreter.chat()
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 84, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 104, in _streaming_chat
    yield from terminal_interface(self, message)
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\terminal_interface\terminal_interface.py", line 91, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 112, in _streaming_chat
    yield from self._respond()
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 147, in _respond
    yield from respond(self)
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\respond.py", line 45, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\llm\setup_openai_coding_llm.py", line 114, in coding_llm
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 962, in wrapper
    raise e
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 899, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\timeout.py", line 42, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\main.py", line 1403, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 3574, in exception_type
    raise e
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 2885, in exception_type
    raise original_exception
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\main.py", line 509, in completion
    raise e
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\main.py", line 491, in completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\jiang.du\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.
```

![image](https://github.com/KillianLucas/open-interpreter/assets/70568691/3ce14bcd-9f35-4f14-91b0-c14b21c8dff5)

### Reproduce

none

### Expected behavior

none

### Open Interpreter version

 0.1.11

### Python version

3.11.0

### Operating System name and version

window10

**Comment by ericrallen** [comment]
Hey again, @a554878526!

That final error message still indicates that your account might not be set up for recurring API billing, which is required to use GPT-4 via the API.

**Comment by a554878526** [comment]
But I already have gpt4 on
![image](https://github.com/KillianLucas/open-interpreter/assets/70568691/f069ea4f-72fb-4f36-893c-2461959e4cce)

**Comment by ericrallen** [comment]
Just having CharGPT Plus isn’t enough to use the `gpt-4` models via the API.

You have to set up automated billing in your OpenAI account, too, and have made $1 in payments or the API will block requests to any `gpt-4` model.

This is mentioned in the link I sent in your original issue.

https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4

**Comment by ericrallen** [comment]
Going to close this one as GPT-4 access is an OpenAI account issue and not an Open Interpreter issue.
