### ISSUE TITLE
errors when loading local file

### ISSUE THREAD

**Issue by drnic** [KillianLucas/open-interpreter#748]
### Describe the bug

When I run `interpreter --vision` and give it a path to a local file I get the error:

```
  File "/opt/homebrew/Caskroom/miniconda/base/envs/open-interpreter/lib/python3.11/site-packages/interpreter/terminal_interface/terminal_interface.py", line 91, in terminal_interface
    image_path = find_image_path(message)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/open-interpreter/lib/python3.11/site-packages/interpreter/utils/find_image_path.py", line 14, in find_image_path
    matches += [match.replace("\\", "") for match in matches]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/open-interpreter/lib/python3.11/site-packages/interpreter/utils/find_image_path.py", line 14, in <listcomp>
    matches += [match.replace("\\", "") for match in matches]
                ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
```

### Reproduce

```
$ conda create -n open-interpreter python=3.11 -y
$ conda activate open-interpreter
$ pip install open-interpreter
...
Collecting open-interpreter
  Using cached open_interpreter-0.1.13-py3-none-any.whl.metadata (14 kB)

$ python --version
Python 3.11.5

$ interpreter --vision

▌ Vision enabled (experimental)


▌ Model set to gpt-4-vision-preview

Open Interpreter will require approval before running code.

Use interpreter -y to bypass this.

Press CTRL-C to exit.
```

Ok, now using the command:

```
> What's in this image? /Users/drnic/Desktop/sample.png
```

And the error:

```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/open-interpreter/bin/interpreter", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/open-interpreter/lib/python3.11/site-packages/interpreter/core/core.py", line 24, in cli
    cli(self)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/open-interpreter/lib/python3.11/site-packages/interpreter/cli/cli.py", line 268, in cli
    interpreter.chat()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/open-interpreter/lib/python3.11/site-packages/interpreter/core/core.py", line 86, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/open-interpreter/lib/python3.11/site-packages/interpreter/core/core.py", line 106, in _streaming_chat
    yield from terminal_interface(self, message)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/open-interpreter/lib/python3.11/site-packages/interpreter/terminal_interface/terminal_interface.py", line 91, in terminal_interface
    image_path = find_image_path(message)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/open-interpreter/lib/python3.11/site-packages/interpreter/utils/find_image_path.py", line 14, in find_image_path
    matches += [match.replace("\\", "") for match in matches]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/open-interpreter/lib/python3.11/site-packages/interpreter/utils/find_image_path.py", line 14, in <listcomp>
    matches += [match.replace("\\", "") for match in matches]
                ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
```

### Expected behavior

Was trying to reproduce this twitter demo https://twitter.com/hellokillian/status/1723106008061587651

### Screenshots

![image](https://github.com/KillianLucas/open-interpreter/assets/108/a155530a-8ac1-4c8e-9c51-eea11defa7dc)

### Open Interpreter version

0.1.13

### Python version

3.11.5

### Operating System name and version

Mac 13.6 (22G120)

**Comment by KillianLucas** [comment]
Hi @drnic, thank you so much for reporting this. Let me know if the latest version (0.1.14) works:

```shell
pip install --upgrade open-interpreter
interpreter
```

This should have been the result of a `regex` error I made, which the update should fix.

**Comment by drnic** [comment]
Thanks @KillianLucas that’s working a treat now
