### ISSUE TITLE
How to use interpreter -y?

### ISSUE THREAD

**Issue by mrphy77** [KillianLucas/open-interpreter#764]
### Describe the bug

How can I get rid of this problem?

### Reproduce

.

### Expected behavior

.

### Screenshots

![2023-11-16 15_52_20-Komut İstemi](https://github.com/KillianLucas/open-interpreter/assets/118127235/8c29b414-523b-45c5-8a46-dfe50679a7ce)

### Open Interpreter version

0.1.15

### Python version

3.11.15

### Operating System name and version

Windows 10

**Comment by ericrallen** [comment]
Hey there, @mrphy77!

`-y` is a command line flag that you pass when invoking `interpreter` initially to enable `auto_run` and not something you send to Open Interpreter once you’ve started a session.

**Comment by mrphy77** [comment]
> Hey there, @mrphy77!
> 
> `-y` is a command line flag that you pass when invoking `interpreter` initially to enable `auto_run` and not something you send to Open Interpreter once you’ve started a session.

**Comment by mrphy77** [comment]
> Hey there, @mrphy77!
> 
> `-y` is a command line flag that you pass when invoking `interpreter` initially to enable `auto_run` and not something you send to Open Interpreter once you’ve started a session.


im sorry i don't understand. what should i do tu use interpreter ? I can't get any further than this warning

**Comment by ericrallen** [comment]
It’s not a warning, it’s just informing you that if you don’t want it to ask for permission to run each code block, you can use that flag.

I’m not sure why that input produced an error, though.

Have you tried just asking it to do something after you start it?

**Comment by mrphy77** [comment]
> It’s not a warning, it’s just informing you that if you don’t want it to ask for permission to run each code block, you can use that flag.
> 
> I’m not sure why that input produced an error, though.
> 
> Have you tried just asking it to do something after you start it?

yes I tried but the same errors appear again

**Comment by ericrallen** [comment]
Can you share the full error output?

**Comment by mrphy77** [comment]
> Can you share the full error output?

C:\Users\onurb>interpreter

▌ Model set to gpt-4

Open Interpreter will require approval before running code.

Use interpreter -y to bypass this.

Press CTRL-C to exit.

> hello world

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.


        Python Version: 3.11.5
        Pip Version: 23.3.1
        Open-interpreter Version: cmd:Interpreter, pkg: 0.1.15
        OS Version and Architecture: Windows-10-10.0.19045-SP0
        CPU Info: AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD
        RAM Info: 15.92 GB, used: 6.86, free: 9.06


        Interpreter Info
        Vision: False
        Model: gpt-4
        Function calling: True
        Context window: None
        Max tokens: None

        Auto run: False
        API base: None
        Local: False

        Curl output: Not local


Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\onurb\AppData\Local\Programs\Python\Python311\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\onurb\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 24, in cli
    cli(self)
  File "C:\Users\onurb\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\cli\cli.py", line 268, in cli
    interpreter.chat()
  File "C:\Users\onurb\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 86, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "C:\Users\onurb\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 106, in _streaming_chat
    yield from terminal_interface(self, message)
  File "C:\Users\onurb\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\terminal_interface\terminal_interface.py", line 115, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "C:\Users\onurb\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 127, in _streaming_chat
    yield from self._respond()
  File "C:\Users\onurb\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 162, in _respond
    yield from respond(self)
  File "C:\Users\onurb\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\respond.py", line 49, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "C:\Users\onurb\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\llm\setup_openai_coding_llm.py", line 114, in coding_llm
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\onurb\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 962, in wrapper
    raise e
  File "C:\Users\onurb\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 899, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\onurb\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\onurb\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\onurb\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\onurb\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\timeout.py", line 42, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\onurb\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\main.py", line 1403, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\onurb\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 3574, in exception_type
    raise e
  File "C:\Users\onurb\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 2885, in exception_type
    raise original_exception
  File "C:\Users\onurb\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\main.py", line 509, in completion
    raise e
  File "C:\Users\onurb\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\main.py", line 491, in completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\onurb\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\onurb\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\onurb\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\onurb\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\onurb\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.

**Comment by ericrallen** [comment]
You don’t have API access to `gpt-4`:

https://github.com/KillianLucas/open-interpreter/issues/164#issuecomment-1711992453

**Comment by mrphy77** [comment]
> You don’t have API access to `gpt-4`:
> 
> [#164 (comment)](https://github.com/KillianLucas/open-interpreter/issues/164#issuecomment-1711992453)

I got the api key for the interpreter, but I don't have an OpenAI paid subscription. Could this be the reason?
