### ISSUE TITLE
ImportError: cannot import name 'Mapping' from 'collections

### ISSUE THREAD

**Issue by ostrolucky** [KillianLucas/open-interpreter#782]
### Describe the bug

```
❯ interpreter
Traceback (most recent call last):
  File "/opt/homebrew/bin/interpreter", line 5, in <module>
    from interpreter import cli
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/__init__.py", line 3, in <module>
    from .core.core import Interpreter
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/core/core.py", line 10, in <module>
    from ..cli.cli import cli
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/cli/cli.py", line 8, in <module>
    from ..terminal_interface.conversation_navigator import conversation_navigator
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/terminal_interface/conversation_navigator.py", line 14, in <module>
    from .render_past_conversation import render_past_conversation
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/terminal_interface/render_past_conversation.py", line 4, in <module>
    from .magic_commands import handle_magic_command
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/terminal_interface/magic_commands.py", line 4, in <module>
    from ..utils.count_tokens import count_messages_tokens
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/utils/count_tokens.py", line 2, in <module>
    from litellm import cost_per_token
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/__init__.py", line 2, in <module>
    import threading, requests
  File "/opt/homebrew/lib/python3.11/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/opt/homebrew/lib/python3.11/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/opt/homebrew/lib/python3.11/site-packages/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/opt/homebrew/lib/python3.11/site-packages/urllib3/connection.py", line 39, in <module>
    from .util.ssl_ import (
  File "/opt/homebrew/lib/python3.11/site-packages/urllib3/util/__init__.py", line 3, in <module>
    from .connection import is_connection_dropped
  File "/opt/homebrew/lib/python3.11/site-packages/urllib3/util/connection.py", line 3, in <module>
    from .wait import wait_for_read
  File "/opt/homebrew/lib/python3.11/site-packages/urllib3/util/wait.py", line 1, in <module>
    from .selectors import (
  File "/opt/homebrew/lib/python3.11/site-packages/urllib3/util/selectors.py", line 14, in <module>
    from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/collections/__init__.py)
```

### Reproduce

1. pip install open-interpreter
2. open-interpreter

### Expected behavior

not crash

### Open Interpreter version

0.1.15

### Python version

3.11.6

### Operating System name and version

macOS 14.1.1 (23B81)

**Comment by Notnaton** [comment]
@ostrolucky Can you run `pip show urllib3` and post the output here?

**Comment by ostrolucky** [comment]
```
Name: urllib3
Version: 1.21.1
Summary: HTTP library with thread-safe connection pooling, file post, and more.
Home-page: https://urllib3.readthedocs.io/
Author: Andrey Petrov
Author-email: andrey.petrov@shazow.net
License: MIT
Location: /opt/homebrew/lib/python3.11/site-packages
Requires:
Required-by: requests
```

**Comment by Notnaton** [comment]
@ostrolucky run `pip install --upgrade urllib3 `

Then try to launch interpreter again

**Comment by ostrolucky** [comment]
Indeed, that fixes it
