### ISSUE TITLE
API key is setted but display `openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it.` error

### ISSUE THREAD

**Issue by 0num4** [KillianLucas/open-interpreter#791]
### Describe the bug

About three months ago (just after it was released) I installed open-interpreter use `pip install open-interpriter`.
It's been a while since I've used it and I got the following error.
I try to update `pip install -U open-interpriter` and `echo echo $OPENAI_API_KEY` is nomally, but `interpreter`command is not worked

https://github.com/KillianLucas/open-interpreter/pull/773/files#diff-6e02c957cbc5e36b5a386dff120bb3e41f7a2edb9929fadcc7dcd4f3e5669b6b

### Reproduce

cd ~
interpreter

### Expected behavior

run nomally

### Screenshots

```
❯ interpreter                                                                

▌ Model set to GPT-4                                                                                                                                                                                           

Tip: To run locally, use interpreter --local                                                                                                                                                                     

Open Interpreter will require approval before running code. Use interpreter -y to bypass this.                                                                                                                   

Press CTRL-C to exit.                                                                                                                                                                                            

> f
Traceback (most recent call last):
  File "/Users/User/.anyenv/envs/pyenv/versions/3.11.3/bin/interpreter", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/User/.anyenv/envs/pyenv/versions/3.11.3/lib/python3.11/site-packages/interpreter/interpreter.py", line 104, in cli
    cli(self)
  File "/Users/User/.anyenv/envs/pyenv/versions/3.11.3/lib/python3.11/site-packages/interpreter/cli.py", line 46, in cli
    interpreter.chat()
  File "/Users/User/.anyenv/envs/pyenv/versions/3.11.3/lib/python3.11/site-packages/interpreter/interpreter.py", line 256, in chat
    self.respond()
  File "/Users/User/.anyenv/envs/pyenv/versions/3.11.3/lib/python3.11/site-packages/interpreter/interpreter.py", line 388, in respond
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/User/.anyenv/envs/pyenv/versions/3.11.3/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/User/.anyenv/envs/pyenv/versions/3.11.3/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/Users/User/.anyenv/envs/pyenv/versions/3.11.3/lib/python3.11/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/User/.anyenv/envs/pyenv/versions/3.11.3/lib/python3.11/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/Users/User/.anyenv/envs/pyenv/versions/3.11.3/lib/python3.11/site-packages/openai/api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.

```

### Open Interpreter version

0.1.1

### Python version

Python 3.11.3

### Operating System name and version

mac OS 14.1.1

**Comment by CyanideByte** [comment]
The gpt-4 models are only available to people who have attached a payment method and purchased api credits.
This is not the same as paying for ChatGPT Plus.

Link: https://platform.openai.com/account/billing/overview
You can still use your free credits if you use gpt-3.5 instead though by using --fast like below.
`interpreter --fast`

There is a fix to automatically detect this in the future on the current github version.
