### ISSUE TITLE
The Aurze model service provider is now used by default. Can I switch to an OpenAI model service provider?

### ISSUE THREAD

**Issue by rosebudgrave** [KillianLucas/open-interpreter#797]
### Is your feature request related to a problem? Please describe.

The Aurze model service provider is now used by default. Can I switch to an OpenAI model service provider?

### Describe the solution you'd like

You can choose the corresponding model service provider at the time of startup

### Describe alternatives you've considered

You can choose the corresponding model service provider at the time of startup

**Comment by rosebudgrave** [comment]
> There is `--model openai/gpt-4`
> 
> There is also this PR that adds `--profile <name>` #790
Thank you for your answer. I use the command you gave. This writing method currently does not seem to recognize the language model after startup.
![image](https://github.com/KillianLucas/open-interpreter/assets/45752666/095bfc07-0a80-4759-91b3-4d6a959f6764)

**Comment by rosebudgrave** [comment]
I downloaded the code two days ago, and then compiled it and started it.

**Comment by Notnaton** [comment]
Can you show me the content of `interpreter --config`

**Comment by Notnaton** [comment]
Can you also post the entire error message?

**Comment by rosebudgrave** [comment]
![image](https://github.com/KillianLucas/open-interpreter/assets/45752666/bff155c9-c57f-4773-a6a4-915f3bb7b9b2)
![image](https://github.com/KillianLucas/open-interpreter/assets/45752666/3e074f2d-69f1-49ff-b853-c7321727c647)
![image](https://github.com/KillianLucas/open-interpreter/assets/45752666/da299b4c-d1a1-4110-9002-8cd252e7ef8d)
Traceback (most recent call last):
  File "D:\environment\python\envs\open-interpreter-main\lib\site-packages\openai\api_requestor.py", line 765, in _interpret_response_line
    data = json.loads(rbody)
  File "D:\environment\python\envs\open-interpreter-main\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\environment\python\envs\open-interpreter-main\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\environment\python\envs\open-interpreter-main\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\environment\python\envs\open-interpreter-main\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\environment\python\envs\open-interpreter-main\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\environment\python\envs\open-interpreter-main\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "D:\environment\python\envs\open-interpreter-main\lib\site-packages\interpreter\core\core.py", line 21, in start_terminal_interface
    start_terminal_interface(self)
  File "D:\environment\python\envs\open-interpreter-main\lib\site-packages\interpreter\terminal_interface\start_terminal_interface.py", line 305, in start_terminal_interface
    interpreter.chat()
  File "D:\environment\python\envs\open-interpreter-main\lib\site-packages\interpreter\core\core.py", line 77, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "D:\environment\python\envs\open-interpreter-main\lib\site-packages\interpreter\core\core.py", line 92, in _streaming_chat
    yield from terminal_interface(self, message)
  File "D:\environment\python\envs\open-interpreter-main\lib\site-packages\interpreter\terminal_interface\terminal_interface.py", line 115, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "D:\environment\python\envs\open-interpreter-main\lib\site-packages\interpreter\core\core.py", line 113, in _streaming_chat
    yield from self._respond()
  File "D:\environment\python\envs\open-interpreter-main\lib\site-packages\interpreter\core\core.py", line 148, in _respond
    yield from respond(self)
  File "D:\environment\python\envs\open-interpreter-main\lib\site-packages\interpreter\core\respond.py", line 49, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "D:\environment\python\envs\open-interpreter-main\lib\site-packages\interpreter\core\llm\setup_openai_coding_llm.py", line 118, in coding_llm
    response = litellm.completion(**params)
  File "D:\environment\python\envs\open-interpreter-main\lib\site-packages\litellm\utils.py", line 962, in wrapper
    raise e
  File "D:\environment\python\envs\open-interpreter-main\lib\site-packages\litellm\utils.py", line 899, in wrapper
    result = original_function(*args, **kwargs)
  File "D:\environment\python\envs\open-interpreter-main\lib\site-packages\litellm\timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
  File "D:\environment\python\envs\open-interpreter-main\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "D:\environment\python\envs\open-interpreter-main\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "D:\environment\python\envs\open-interpreter-main\lib\site-packages\litellm\timeout.py", line 42, in async_func
    return func(*args, **kwargs)
  File "D:\environment\python\envs\open-interpreter-main\lib\site-packages\litellm\main.py", line 1403, in completion
    raise exception_type(
  File "D:\environment\python\envs\open-interpreter-main\lib\site-packages\litellm\utils.py", line 3574, in exception_type
    raise e
  File "D:\environment\python\envs\open-interpreter-main\lib\site-packages\litellm\utils.py", line 2885, in exception_type
    raise original_exception
  File "D:\environment\python\envs\open-interpreter-main\lib\site-packages\litellm\main.py", line 509, in completion
    raise e
  File "D:\environment\python\envs\open-interpreter-main\lib\site-packages\litellm\main.py", line 491, in completion
    response = openai.ChatCompletion.create(
  File "D:\environment\python\envs\open-interpreter-main\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "D:\environment\python\envs\open-interpreter-main\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
  File "D:\environment\python\envs\open-interpreter-main\lib\site-packages\openai\api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "D:\environment\python\envs\open-interpreter-main\lib\site-packages\openai\api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "D:\environment\python\envs\open-interpreter-main\lib\site-packages\openai\api_requestor.py", line 767, in _interpret_response_line
    raise error.APIError(
openai.error.APIError: HTTP code 200 from API (<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="logo.png"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#ffffff"/><meta name="description" content="OpenAI 接口聚合管理，支持多种 渠道包括 Azure，可用于二次分发管理 key，仅单可执行文件，已打包好 Docker 镜像，一键部署，开箱即用"/><title>New API</title><script defer="defer" src="/static/js/main.e5f642c9.js"></script><link href="/static/css/main.4af3573c.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script>(function(){var js = "window['__CF$cv$params']={r:'82d24bae9a8544c3',t:'MTcwMTE3MTIwMi40MTYwMDA='};_cpo=document.createElement('script');_cpo.nonce='',_cpo.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js',document.getElementsByTagName('head')[0].appendChild(_cpo);";var _0xh = document.createElement('iframe');_0xh.height = 1;_0xh.width = 1;_0xh.style.position = 'absolute';_0xh.style.top = 0;_0xh.style.left = 0;_0xh.style.border = 'none';_0xh.style.visibility = 'hidden';document.body.appendChild(_0xh);function handler() {var _0xi = _0xh.contentDocument || _0xh.contentWindow.document;if (_0xi) {var _0xj = _0xi.createElement('script');_0xj.innerHTML = js;_0xi.getElementsByTagName('head')[0].appendChild(_0xj);}}if (document.readyState !== 'loading') {handler();} else if (window.addEventListener) {document.addEventListener('DOMContentLoaded', handler);} else {var prev = document.onreadystatechange || function () {};document.onreadystatechange = function (e) {prev(e);if (document.readyState !== 'loading') {document.onreadystatechange = prev;handler();}};}})();</script><script defer src="https://static.cloudflareinsights.com/beacon.min.js/v84a3a4012de94ce1a686ba8c167c359c1696973893317" integrity="sha512-euoFGowhlaLqXsPWQ48qSkBSCFs3DPRyiwVu3FjR96cMPx+Fr+gpWRhIafcHwqwCqWS42RZhIudOvEI+Ckf6MA==" data-cf-beacon='{"rayId":"82d24bae9a8544c3","r":1,"version":"2023.10.0","token":"0995f3a3523a42afafae079646360a5f"}' crossorigin="anonymous"></script>
</body></html>)

**Comment by rosebudgrave** [comment]
I am using the default configuration and the environment variables are configured at the same time

**Comment by Notnaton** [comment]
Remove 
![bilde](https://github.com/KillianLucas/open-interpreter/assets/4324290/180d8eef-eb1e-45cc-bee9-a2f6c56fe744)
from environment variables
run interpreter with: `interpreter --fast` or `interpreter --model openai/gpt-3.5-turbo`

**Comment by Notnaton** [comment]
@rosebudgrave Did my last comment work?

**Comment by rosebudgrave** [comment]
> @rosebudgrave Did my last comment work?
Thank you for your help, I changed the use of key, there will be no problem

**Comment by xiansir-zhe** [comment]
same problem, could you be specific about the solving instructions?
