### ISSUE TITLE
Interpreter gets out of control after a Python exception happens

### ISSUE THREAD

**Issue by nadbp** [KillianLucas/open-interpreter#825]
### Describe the bug

 I let the interpreter to "Please summarize a paper at D:\tmp\p799-chen.pdf" 
 Then the interpreter gave me a plan and used the following code:

 from PyPDF2 import PdfReader

  pdf = PdfReader('D:\\tmp\\p799-chen.pdf')
  text = ''
  for page in pdf.pages:
      text += page.extract_text()
  text

The following exeception happened. However, there is NO ERROR when I ran the same code outside the interpreter.

Exception in thread Thread-310 (handle_stream_output):
Traceback (most recent call last):

  File "D:\Users\dell\anaconda3\envs\openinterpreter\lib\threading.py", line 1016, in _bootstrap_inner

    self.run()

  File "D:\Users\dell\anaconda3\envs\openinterpreter\lib\threading.py", line 953, in run

    self._target(*self._args, **self._kwargs)

  File
"D:\Users\dell\anaconda3\envs\openinterpreter\lib\site-packages\interpreter\core\code_interpreters\subprocess_code_inter
preter.py", line 127, in handle_stream_output

    for line in iter(stream.readline, ""):

UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 123: illegal multibyte sequence

When the error was thrown, the interpreter just stopped there without any response until I pressed ctrl+c. After I pressed ctrl+c, the interpreter became crazy. It did not wait for my response, proposed another plan but worked as I pressed n. It did not respond to any key until I pressed ctrl+c many times.

### Reproduce

1. interpreter (I use gpt-4 and simple conversation is fine)
2. Please summarize a paper at "path to a pdf file"
3. press y for its plan

### Expected behavior

The pdf reading code should work because it works well outside the interpreter (still in the same conda environment). Even there is an error, the interpreter should not get stuck or continues working without my response.

### Screenshots

![openinterprepter](https://github.com/KillianLucas/open-interpreter/assets/7585859/4dab40cf-605e-411b-b87e-7296a0cb152c)

### Open Interpreter version

0.1.17

### Python version

3.10.13

### Operating System name and version

Windows 10

**Comment by MikeBirdTech** [comment]
Closing this stale issue. If this is still a problem with the latest version of Open Interpreter, please alert me to re-open the issue. Thanks!
