### ISSUE TITLE
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by Nothingness-Void** [KillianLucas/open-interpreter#831]
### Describe the bug

After I entered 'interpreter' to run the program and started a conversation, the program threw an error, stating: TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'.

### Reproduce

First, I ran 'interpreter'. After the program started, I sent 'hi'. Then, the program threw an error.

### Expected behavior

The program running normally.

### Screenshots

![image](https://github.com/KillianLucas/open-interpreter/assets/55913486/9771fbed-77f8-4cdc-a6cd-38235e9bebf8)

### Open Interpreter version

0.1.17

### Python version

3.11.4

### Operating System name and version

Windows 11

**Comment by Notnaton** [comment]
Please show the entire error message

**Comment by Nothingness-Void** [comment]
> Please show the entire error message

`> hi

        Python Version: 3.11.4
        Pip Version: 23.1.2
        Open-interpreter Version: cmd:Interpreter, pkg: 0.1.17
        OS Version and Architecture: Windows-10-10.0.23601-SP0
        CPU Info: AMD64 Family 25 Model 68 Stepping 1, AuthenticAMD
        RAM Info: 15.19 GB, used: 9.62, free: 5.58


        Interpreter Info
        Vision: False
        Model: gpt-4
        Function calling: True
        Context window: None
        Max tokens: None

        Auto run: False
        API base: https://one-api.nothingnessvoid.top/v1
        Local: False

        Curl output: Not local


Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\17449\Miniconda3\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\17449\Miniconda3\Lib\site-packages\interpreter\core\core.py", line 21, in start_terminal_interface
    start_terminal_interface(self)
  File "C:\Users\17449\Miniconda3\Lib\site-packages\interpreter\terminal_interface\start_terminal_interface.py", line 304, in start_terminal_interface
    interpreter.chat()
  File "C:\Users\17449\Miniconda3\Lib\site-packages\interpreter\core\core.py", line 77, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "C:\Users\17449\Miniconda3\Lib\site-packages\interpreter\core\core.py", line 92, in _streaming_chat
    yield from terminal_interface(self, message)
  File "C:\Users\17449\Miniconda3\Lib\site-packages\interpreter\terminal_interface\terminal_interface.py", line 115, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "C:\Users\17449\Miniconda3\Lib\site-packages\interpreter\core\core.py", line 113, in _streaming_chat
    yield from self._respond()
  File "C:\Users\17449\Miniconda3\Lib\site-packages\interpreter\core\core.py", line 148, in _respond
    yield from respond(self)
  File "C:\Users\17449\Miniconda3\Lib\site-packages\interpreter\core\respond.py", line 49, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "C:\Users\17449\Miniconda3\Lib\site-packages\interpreter\core\llm\setup_openai_coding_llm.py", line 135, in coding_llm
    accumulated_deltas = merge_deltas(accumulated_deltas, delta)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\17449\Miniconda3\Lib\site-packages\interpreter\core\utils\merge_deltas.py", line 19, in merge_deltas
    original[key] += value
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'`

**Comment by madsamjp** [comment]
I'm also getting this error in 0.1.17.

**Comment by Notnaton** [comment]
Should be fixed now, closing
