### ISSUE TITLE
Cannot get it to run when spaces are in path name

### ISSUE THREAD

**Issue by tolidano-humane** [KillianLucas/open-interpreter#846]
### Describe the bug

```
Would you like to run this code? (y/n)

  y


  import azure.resource_groups as rg

  # Create a new resource group
  rg.ResourceGroup(name='my-resource-group').create()


  Traceback (most recent call last):
    File "/Users/Shawn/Library/Application Support/pipx/venvs/open-interpreter/lib/python3.11/site-packages/interpreter/core/code_interpreters/subprocess_code_interpreter.py", line 77, in run
      self.start_process()
    File "/Users/Shawn/Library/Application Support/pipx/venvs/open-interpreter/lib/python3.11/site-packages/interpreter/core/code_interpreters/subprocess_code_interpreter.py", line 48, in start_process
      self.process = subprocess.Popen(
                     ^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1950, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: "'/Users/Shawn/Library/Application"


  Hello Shawn! I'm here to help you with your task. Based on the output you provided, it seems that there was an error when trying to execute the code. The error message indicates that there is no such file or
  directory at '/Users/Shawn/Library/Application Support/pipx/venvs/open-interpreter/lib/python3.11/site-packages/interpreter/core/code_interpreters/subprocess_code_interpreter.py'.

  This error is likely caused by a package installation issue. It looks like the package 'interpreter' is not installed correctly. To fix this, we can try installing the package again using pipx.
```

### Reproduce

install brew
install python
install pipx
install openinterpreter with pipx
run interpreter with a local model connected to ollama

### Expected behavior

it understands and handles spaces in filenames

### Open Interpreter version

0.1.17

### Python version

3.11.6

### Operating System name and version

MacOS Sonoma 14.2

### Additional context

> pipx list
venvs are in /Users/Shawn/Library/Application Support/pipx/venvs
apps are exposed on your $PATH at /Users/Shawn/.local/bin
manual pages are exposed at /Users/Shawn/.local/share/man
   package open-interpreter 0.1.17, installed using Python 3.11.6
    - interpreter

**Comment by MikeBirdTech** [comment]
Closing this stale issue. If this is still a problem with the latest version of Open Interpreter, please alert me to re-open the issue. Thanks!
