### ISSUE TITLE
encoding problem

### ISSUE THREAD

**Issue by liaoke01** [KillianLucas/open-interpreter#857]
### Describe the bug

After installing the dependencies, the following error code appeared when running the second line of command:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 23, in start_terminal_interface
    start_terminal_interface(self)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\terminal_interface\start_terminal_interface.py", line 588, in start_terminal_interface
    interpreter = apply_config(interpreter)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\terminal_interface\utils\apply_config.py", line 17, in apply_config
    config = get_config(config_path)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\terminal_interface\utils\get_config.py", line 54, in get_config
    config = yaml.safe_load(file)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
             ^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
           ^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0x94 in position 353: illegal multibyte sequence

### Reproduce

After installing Python 3.11.7 on a streamlined version of Windows 10, and running the first line of command to install the dependencies, when running the second line of command within the corresponding folder, the error code related to character encoding issues appears

### Expected behavior

To fix this character encoding error

### Open Interpreter version

0.1.18

### Python version

3.11.7

### Operating System name and version

The system is Windows 10 streamlined version19045.3803 , and the system language is set to Chinese

### Additional context

And the same issue occurs on the Windows 11 streamlined version I previously used. I suspect it's not due to the Windows version but possibly due to the streamlined nature or the system language

**Comment by Notnaton** [comment]
This is a problem with the system language I suspect, yaml reader should be utf8

**Comment by liaoke01** [comment]
> This is a problem with the system language I suspect, yaml reader should be utf8

ok,The issue has been resolved.but How do I set the OpenAI base URL

**Comment by XiaoHua013** [comment]
怎么解决的

**Comment by 2catycm** [comment]
这是个重要的问题，系统语言很多用户遇到这个项目都是gbk，我现在需要手动在site-packages 里面修改python代码，才能跑通readme，真的很烦人
