### ISSUE TITLE
Cannot start Interpreter

### ISSUE THREAD

**Issue by filip-van-hoeckel** [KillianLucas/open-interpreter#859]
### Describe the bug

Starting Interpreter fails with the following error message
`Traceback (most recent call last):
  File "C:\laragon\bin\python\python-3.10\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\laragon\bin\python\python-3.10\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\laragon\bin\python\python-3.10\Scripts\interpreter.exe\__main__.py", line 4, in <module>
    from interpreter import interpreter
  File "C:\laragon\bin\python\python-3.10\lib\site-packages\interpreter\__init__.py", line 1, in <module>
    from .core.core import OpenInterpreter
  File "C:\laragon\bin\python\python-3.10\lib\site-packages\interpreter\core\core.py", line 10, in <module>
    from ..terminal_interface.start_terminal_interface import start_terminal_interface
  File "C:\laragon\bin\python\python-3.10\lib\site-packages\interpreter\terminal_interface\start_terminal_interface.py", line 16, in <module>
    from .validate_llm_settings import validate_llm_settings
  File "C:\laragon\bin\python\python-3.10\lib\site-packages\interpreter\terminal_interface\validate_llm_settings.py", line 5, in <module>
    import litellm
  File "C:\laragon\bin\python\python-3.10\lib\site-packages\litellm\__init__.py", line 472, in <module>
    from .timeout import timeout
  File "C:\laragon\bin\python\python-3.10\lib\site-packages\litellm\timeout.py", line 20, in <module>
    from litellm.exceptions import Timeout
  File "C:\laragon\bin\python\python-3.10\lib\site-packages\litellm\exceptions.py", line 12, in <module>
    from openai import (
ImportError: cannot import name 'AuthenticationError' from 'openai' (C:\laragon\bin\python\python-3.10\lib\site-packages\openai\__init__.py)`

### Reproduce

Start Interpreter.

### Expected behavior

A running Interpreter (sorry)

### Open Interpreter version

0.1.18

### Python version

3.10

### Operating System name and version

Windows 11 x64 Pro

**Comment by filip-van-hoeckel** [comment]
Upgrading OpenAI to the latest version seems to fix this issue (OpenAI should be larger than 1.x)

**Comment by KillianLucas** [comment]
Thanks for catching this bug and finding the fix @filip-van-hoeckel, have added `openai` requirement of > 1.x to our `pyproject.toml` which should repair this in `0.2.0`. Will let you know when it's on `pip`.

**Comment by Notnaton** [comment]
@filip-van-hoeckel Closing this as 0.2.0 is out, please reopen if you still have this error

**Comment by mayowaosibodu** [comment]
Experiencing this same issue with `open-interpreter=0.2.0` and `openai==1.9.0` on MacOS. I tried downgrading each library to see if that would change anything, but it didn't.

When I run the `interpreter` command, I get:

`Traceback (most recent call last):
  File "/usr/local/bin/interpreter", line 5, in <module>
    from interpreter import interpreter
  File "/usr/local/lib/python3.10/site-packages/interpreter/__init__.py", line 1, in <module>
    from .core.core import OpenInterpreter
  File "/usr/local/lib/python3.10/site-packages/interpreter/core/core.py", line 10, in <module>
    from ..terminal_interface.start_terminal_interface import start_terminal_interface
  File "/usr/local/lib/python3.10/site-packages/interpreter/terminal_interface/start_terminal_interface.py", line 16, in <module>
    from .validate_llm_settings import validate_llm_settings
  File "/usr/local/lib/python3.10/site-packages/interpreter/terminal_interface/validate_llm_settings.py", line 5, in <module>
    import litellm
  File "/usr/local/lib/python3.10/site-packages/litellm/__init__.py", line 472, in <module>
    from .timeout import timeout
  File "/usr/local/lib/python3.10/site-packages/litellm/timeout.py", line 20, in <module>
    from litellm.exceptions import Timeout
  File "/usr/local/lib/python3.10/site-packages/litellm/exceptions.py", line 12, in <module>
    from openai import (
ImportError: cannot import name 'AuthenticationError' from 'openai' (/usr/local/lib/python3.10/site-packages/openai/__init__.py)
`
