### ISSUE TITLE
AttributeError: dlsym(0x3c0c283b0, objc_msgSendSuper_stret): symbol not found

### ISSUE THREAD

**Issue by anegelya** [KillianLucas/open-interpreter#874]
### Describe the bug

After upgrading Open Interpreter to version 0.2.0 New Computer and trying to run it I got this error:

```bash
~ $ interpreter --os
Traceback (most recent call last):
  File "/Users/a.negelya/miniconda/bin/interpreter", line 8, in <module>
    sys.exit(interpreter.start_terminal_interface())
  File "/Users/a.negelya/miniconda/lib/python3.10/site-packages/interpreter/core/core.py", line 25, in start_terminal_interface
    start_terminal_interface(self)
  File "/Users/a.negelya/miniconda/lib/python3.10/site-packages/interpreter/terminal_interface/start_terminal_interface.py", line 463, in start_terminal_interface
    __import__(package)
  File "/Users/a.negelya/miniconda/lib/python3.10/site-packages/pyautogui/__init__.py", line 246, in <module>
    import mouseinfo
  File "/Users/a.negelya/miniconda/lib/python3.10/site-packages/mouseinfo/__init__.py", line 100, in <module>
    from rubicon.objc import ObjCClass, CGPoint
  File "/Users/a.negelya/miniconda/lib/python3.10/site-packages/rubicon/objc/__init__.py", line 33, in <module>
    from . import api, collections, runtime, types
  File "/Users/a.negelya/miniconda/lib/python3.10/site-packages/rubicon/objc/api.py", line 29, in <module>
    from .runtime import (
  File "/Users/a.negelya/miniconda/lib/python3.10/site-packages/rubicon/objc/runtime.py", line 460, in <module>
    libobjc.objc_msgSendSuper_stret.restype = None
  File "/Users/a.negelya/miniconda/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/Users/a.negelya/miniconda/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x3c0c283b0, objc_msgSendSuper_stret): symbol not found
```

Updating and reinstalling `rubicon-objc`, `pyautogui`, `mouseinfo` didn't help.

### Reproduce

1. Open Interpreter to version 0.2.0 
2. Run `$ interpreter --os`

### Expected behavior

Running Open Interpreter in OS mode

### Open Interpreter version

0.2.0

### Python version

3.10.10

### Operating System name and version

macOS Sonoma 14.2.1

**Comment by Notnaton** [comment]
Can you run 
```
pip install open-interpreter --force-reinstall
```
and see if that fixes it?

**Comment by anegelya** [comment]
It seems like I have successfully installed it on Python v3.9.13

**Comment by Notnaton** [comment]
Interesting... Might be a compatibility issue with python 3.10.10

**Comment by crossxx-labs** [comment]
It's a pyobjc issue. I switched to python3.8 and re-installed pyobjc from git repo,  then the error disappeared. [Details here](https://github.com/asweigart/pyautogui/issues/772#issuecomment-1931241870)

**Comment by MikeBirdTech** [comment]
Closing this stale issue. If this is still a problem with the latest version of Open Interpreter, please alert me to re-open the issue. Thanks!
