### ISSUE TITLE
Cannot run interpreter -os

### ISSUE THREAD

**Issue by alexeydemidovkz** [KillianLucas/open-interpreter#885]
### Describe the bug

Tried to run os control version of interpreter (the text version works fine), it asked to install some packages which I approved, but then give me this error:

```
interpreter -os

▌ OS Control enabled

To find items on the screen, Open Interpreter has been instructed to send screenshots to api.openinterpreter.com (we do not store them). Add --offline to
attempt this locally.

Make sure that screen recording permissions are enabled for your Terminal or Python environment.

Traceback (most recent call last):
  File "/opt/homebrew/bin/interpreter", line 8, in <module>
    sys.exit(interpreter.start_terminal_interface())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/core/core.py", line 25, in start_terminal_interface
    start_terminal_interface(self)
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/terminal_interface/start_terminal_interface.py", line 547, in start_terminal_interface
    for _ in interpreter.computer.run(
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/core/computer/terminal/terminal.py", line 38, in run
    self._active_languages[language] = self.get_language(language)()
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/core/computer/terminal/languages/jupyter_language.py", line 26, in __init__
    self.km.start_kernel()
  File "/opt/homebrew/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/jupyter_client/manager.py", line 96, in wrapper
    raise e
  File "/opt/homebrew/lib/python3.11/site-packages/jupyter_client/manager.py", line 87, in wrapper
    out = await method(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/jupyter_client/manager.py", line 439, in _async_start_kernel
    await self._async_launch_kernel(kernel_cmd, **kw)
  File "/opt/homebrew/lib/python3.11/site-packages/jupyter_client/manager.py", line 354, in _async_launch_kernel
    connection_info = await self.provisioner.launch_kernel(kernel_cmd, **kw)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/jupyter_client/provisioning/local_provisioner.py", line 210, in launch_kernel
    self.process = launch_kernel(cmd, **scrubbed_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/jupyter_client/launcher.py", line 170, in launch_kernel
    raise ex
  File "/opt/homebrew/lib/python3.11/site-packages/jupyter_client/launcher.py", line 155, in launch_kernel
    proc = Popen(cmd, **kwargs)  # noqa
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/alexeydemidov/miniforge3/envs/tf2/bin/python'
```

### Reproduce

1. Install open interpreter
2. run interpreter - os

### Expected behavior

Expect os version of interpreter to work

### Open Interpreter version

0.2.0

### Python version

3.11.7

### Operating System name and version

MacOS 14.2.1

**Comment by appenz** [comment]
Looks like an issue between brew and anaconda. I am not the expert here, but the two are hard to get to play together nicely. Did you check the paths (python, python3, jupyter etc.) in your anaconda environment?

I don't think this has anything to do with open-assistant.

**Comment by Arrendy** [comment]
Did you `Make sure that screen recording permissions are enabled for your Terminal or Python environment.`?
