### ISSUE TITLE
cannot run interpreter on my pc (windows)

### ISSUE THREAD

**Issue by chuangzhidan** [KillianLucas/open-interpreter#892]
### Describe the bug

C:\Users\Gavin>interpreter
Traceback (most recent call last):
  File "D:\Users\Gavin\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Users\Gavin\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Users\Gavin\anaconda3\Scripts\interpreter.exe\__main__.py", line 4, in <module>
  File "D:\Users\Gavin\anaconda3\lib\site-packages\interpreter\__init__.py", line 1, in <module>
    from .core.core import OpenInterpreter
  File "D:\Users\Gavin\anaconda3\lib\site-packages\interpreter\core\core.py", line 11, in <module>
    from ..terminal_interface.start_terminal_interface import start_terminal_interface
  File "D:\Users\Gavin\anaconda3\lib\site-packages\interpreter\terminal_interface\start_terminal_interface.py", line 16, in <module>
    from .validate_llm_settings import validate_llm_settings
  File "D:\Users\Gavin\anaconda3\lib\site-packages\interpreter\terminal_interface\validate_llm_settings.py", line 5, in <module>
    import litellm
  File "D:\Users\Gavin\anaconda3\lib\site-packages\litellm\__init__.py", line 6, in <module>
    from litellm.proxy._types import KeyManagementSystem
  File "D:\Users\Gavin\anaconda3\lib\site-packages\litellm\proxy\_types.py", line 62, in <module>
    class ModelInfo(LiteLLMBase):
  File "pydantic\main.py", line 198, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 661, in pydantic.fields.ModelField._type_analysis
  File "pydantic\fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "D:\Users\Gavin\anaconda3\lib\typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class

do not know where the problem is ,can you help?

### Reproduce

pip install  open-interpreter

run interpreter

### Expected behavior

Expect windows version of interpreter to work

### Open Interpreter version

newest  version, i believe, 0.2.0

### Python version

Python 3.9.13

### Operating System name and version

windows 11

**Comment by chuangzhidan** [comment]
work miraculously well, so kind of u to help
