### ISSUE TITLE
ValueError: System message exceeds token limit

### ISSUE THREAD

**Issue by jiarongji** [KillianLucas/open-interpreter#92]
Python 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import interpreter
>>> interpreter.chat("hello")

Welcome to Open Interpreter.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
▌ OpenAI API key not found

To use GPT-4 (recommended) please provide an OpenAI API key.

To use Code-Llama (free but less capable) press enter.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
OpenAI API key:

▌ Switching to Code-Llama...

Tip: Run interpreter --local to automatically use Code-Llama.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Open Interpreter will use Code Llama for local execution. Use your arrow keys to set up the model.
[?] Parameter count (smaller is faster, larger is more capable): 7B
 > 7B
   13B
   34B

[?] Quality (lower is faster, higher is more capable): Low | Size: 3.01 GB, RAM usage: 5.51 GB
 > Low | Size: 3.01 GB, RAM usage: 5.51 GB
   Medium | Size: 4.24 GB, RAM usage: 6.74 GB
   High | Size: 7.16 GB, RAM usage: 9.66 GB

[?] Use GPU? (Large models might crash on GPU, but will run more quickly) (Y/n): n

▌ Model set to Code-Llama

Open Interpreter will require approval before running code. Use interpreter -y to bypass this.

Press CTRL-C to exit.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\13749\AppData\Roaming\Python\Python310\site-packages\interpreter\interpreter.py", line 216, in chat
    self.respond()
  File "C:\Users\13749\AppData\Roaming\Python\Python310\site-packages\interpreter\interpreter.py", line 302, in respond
    messages = tt.trim(self.messages, self.model, system_message=system_message)
  File "C:\Users\13749\AppData\Roaming\Python\Python310\site-packages\tokentrim\tokentrim.py", line 145, in trim
    raise ValueError("System message exceeds token limit")
ValueError: System message exceeds token limit
>>>

**Comment by jiarongji** [comment]
What is the cause of the above error and how can I fix it?

**Comment by AshwinRamachandran2002** [comment]
The tokentrim repository has this particular code present in tokentrim.py that is raising the error
```
max_tokens -= system_message_tokens

if system_message_tokens > max_tokens:
      raise ValueError("System message exceeds token limit")
```

Might this be an error? Should the check be done before the modification to the max_tokens?``

**Comment by RickieBlaese** [comment]
Same issue here.

**Comment by AshwinRamachandran2002** [comment]
I have submitted a PR on the tokentrim.py to correct this problem, but could you try commenting out the line 

```
if system_message_tokens > max_tokens:
      raise ValueError("System message exceeds token limit")
```

from your local file tokentrim.py?

**Comment by kruemmelbande** [comment]
I've changed my max token number in the llama library to 1500 which works

**Comment by kruemmelbande** [comment]
I've changed my max token number in the llama library to 1500 which works

**Comment by wghuang-aigc** [comment]
pip install --upgrade open-interpreter

this not work,

**Comment by wghuang-aigc** [comment]
![image](https://github.com/KillianLucas/open-interpreter/assets/7413745/a7ff2509-1cac-4b2f-907f-1b308bfd9791)
how could it work ,

**Comment by wghuang-aigc** [comment]
Traceback (most recent call last):
  File "e:\项目代码\AIGC\project\modelscope-demo\interpreterdemo.py", line 24, in <module>
    interpreter.chat("求解类似 10x + 14 = 12 的方程") 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\python\Lib\site-packages\interpreter\interpreter.py", line 258, in chat
    self.respond()
  File "D:\Program Files\python\Lib\site-packages\interpreter\interpreter.py", line 510, in respond
    raise Exception(error)
Exception: Traceback (most recent call last):
  File "D:\Program Files\python\Lib\site-packages\interpreter\interpreter.py", line 495, in respond
    response = litellm.completion(
               ^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\python\Lib\site-packages\litellm\utils.py", line 584, in wrapper
    raise e
  File "D:\Program Files\python\Lib\site-packages\litellm\utils.py", line 544, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\python\Lib\site-packages\litellm\timeout.py", line 44, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\python\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\python\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "D:\Program Files\python\Lib\site-packages\litellm\timeout.py", line 33, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\python\Lib\site-packages\litellm\main.py", line 862, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "D:\Program Files\python\Lib\site-packages\litellm\utils.py", line 2022, in exception_type
    raise e
  File "D:\Program Files\python\Lib\site-packages\litellm\utils.py", line 1615, in exception_type
    raise original_exception
  File "D:\Program Files\python\Lib\site-packages\litellm\main.py", line 277, in completion
    raise e
  File "D:\Program Files\python\Lib\site-packages\litellm\main.py", line 260, in completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\python\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\python\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\python\Lib\site-packages\openai\api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\python\Lib\site-packages\openai\api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "D:\Program Files\python\Lib\site-packages\openai\api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Invalid URL (POST /chat/completions)

**Comment by cc8887** [comment]
试试用英文prompt？

**Comment by wghuang-aigc** [comment]
![image](https://github.com/KillianLucas/open-interpreter/assets/7413745/bc6e6e33-623d-4b55-917b-9ccdadfe40d9)
![image](https://github.com/KillianLucas/open-interpreter/assets/7413745/de7c8017-afe3-4321-835c-2c41e82f380a)
but it can work well in the terminal
![image](https://github.com/KillianLucas/open-interpreter/assets/7413745/3c56858e-7a0d-4bd4-b551-b1ecd754008e)

**Comment by wghuang-aigc** [comment]
> 试试用英文prompt？

it does't work

**Comment by YakinRubaiat** [comment]
@KillianLucas  we are facing this issue in version 0.2.5.
