### ISSUE TITLE
Quitting an interpreter session with CTRL-D causes an ugly traceback

### ISSUE THREAD

**Issue by deeplook** [KillianLucas/open-interpreter#925]
### Describe the bug

Quitting an interpreter session with CTRL-D instead of CTRL-C causes an ugly traceback.

### Reproduce

Enter `interpreter` in a terminal.
Wait for the `>` prompt.
Enter CTRL-D.

### Expected behavior

Gracefully quitting the session for CTRL-D like with CTRL-C, although the welcome message mentions only CTRL-C.

### Screenshots

```
% interpreter

▌ Model set to gpt-4

Open Interpreter will require approval before running code.

Use interpreter -y to bypass this.

Press CTRL-C to exit.

> Traceback (most recent call last):
  File "/Users/foobar/miniconda3/envs/oi-env/bin/interpreter", line 8, in <module>
    sys.exit(interpreter.start_terminal_interface())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/foobar/miniconda3/envs/oi-env/lib/python3.11/site-packages/interpreter/core/core.py", line 25, in start_terminal_interface
    start_terminal_interface(self)
  File "/Users/foobar/miniconda3/envs/oi-env/lib/python3.11/site-packages/interpreter/terminal_interface/start_terminal_interface.py", line 684, in start_terminal_interface
    interpreter.chat()
  File "/Users/foobar/miniconda3/envs/oi-env/lib/python3.11/site-packages/interpreter/core/core.py", line 86, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "/Users/foobar/miniconda3/envs/oi-env/lib/python3.11/site-packages/interpreter/core/core.py", line 113, in _streaming_chat
    yield from terminal_interface(self, message)
  File "/Users/foobar/miniconda3/envs/oi-env/lib/python3.11/site-packages/interpreter/terminal_interface/terminal_interface.py", line 78, in terminal_interface
    message = input("> ").strip()
              ^^^^^^^^^^^
EOFError
```

### Open Interpreter version

0.2.0

### Python version

3.11.7

### Operating System name and version

macOS 13.6.4 (arm M1)

**Comment by deeplook** [comment]
> In general, would be nice to have a 'stop generating' command - that didn't quit out as well.

Sounds like this would qualify as a separate ticket.

**Comment by teocns** [comment]
The issue I am facing might be related to it; Happens when trying to resume any of the `--conversations`:

```
Traceback (most recent call last):
  File "/Users/yea/.pyenv/versions/3.11.0/bin/interpreter", line 8, in <module>
    sys.exit(interpreter.start_terminal_interface())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yea/.pyenv/versions/3.11.0/lib/python3.11/site-packages/interpreter/core/core.py", line 25, in start_terminal_interface
    start_terminal_interface(self)
  File "/Users/yea/.pyenv/versions/3.11.0/lib/python3.11/site-packages/interpreter/terminal_interface/start_terminal_interface.py", line 677, in start_terminal_interface
    conversation_navigator(interpreter)
  File "/Users/yea/.pyenv/versions/3.11.0/lib/python3.11/site-packages/interpreter/terminal_interface/conversation_navigator.py", line 82, in conversation_navigator
    render_past_conversation(messages)
  File "/Users/yea/.pyenv/versions/3.11.0/lib/python3.11/site-packages/interpreter/terminal_interface/render_past_conversation.py", line 25, in render_past_conversation
    print(">", chunk["message"])
               ~~~~~^^^^^^^^^^^
KeyError: 'message'
```

**Comment by MikeBirdTech** [comment]
Hi @deeplook 
Thanks for opening the issue.
If a PR is made for this, we will review it, but seeing as CTRL-C works as expected, this will not be a priority. Thanks!
