### ISSUE TITLE
UnicodeEncodeError or UnicodeDecodeError

### ISSUE THREAD

**Issue by Rehan-stack** [KillianLucas/open-interpreter#93]
Giving error while running on git bash CLI.
Error:
$ interpreter

Welcome to Open Interpreter.

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\owlsense.intern\AppData\Local\Programs\Python\Python311\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\owlsense.intern\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\interpreter.py", line 91, in cli
    cli(self)
  File "C:\Users\owlsense.intern\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\cli.py", line 42, in cli
    interpreter.chat()
  File "C:\Users\owlsense.intern\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\interpreter.py", line 155, in chat
    self.verify_api_key()
  File "C:\Users\owlsense.intern\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\interpreter.py", line 269, in verify_api_key
    print(Rule(style="white"))
  File "C:\Users\owlsense.intern\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\__init__.py", line 74, in print
    return write_console.print(*objects, sep=sep, end=end)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owlsense.intern\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\console.py", line 1672, in print
    with self:
  File "C:\Users\owlsense.intern\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\console.py", line 864, in __exit__
    self._exit_buffer()
  File "C:\Users\owlsense.intern\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\console.py", line 822, in _exit_buffer
    self._check_buffer()
  File "C:\Users\owlsense.intern\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\console.py", line 2026, in _check_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
  File "C:\Users\owlsense.intern\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\_windows_renderer.py", line 17, in legacy_windows_render
    term.write_styled(text, style)
  File "C:\Users\owlsense.intern\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\_win32_console.py", line 442, in write_styled
    self.write_text(text)
  File "C:\Users\owlsense.intern\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\_win32_console.py", line 403, in write_text
    self.write(text)
  File "C:\Users\owlsense.intern\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-78: character maps to <undefined>

**Comment by jordanbtucker** [comment]
Thanks for reporting. Please make sure you are on the latest version of open-interpreter by running the following.

```
pip install --upgrade open-interpreter
```

If the issue still occurs, please report back.

**Comment by Rehan-stack** [comment]
> interpreter
still same error

**Comment by jordanbtucker** [comment]
I think #231 might fix this.

**Comment by fatelei** [comment]
here is solution:
1. export PYTHONIOENCODING=utf8
2. downgrade rich to 12.4.4

**Comment by ericrallen** [comment]
Hey there, folks!

#742 (thanks @fatelei!) _might_ fix this.

**Comment by Notnaton** [comment]
Should be fixed now with the next update
