### ISSUE TITLE
KeyError: 'XDG_SESSION_TYPE' on startup

### ISSUE THREAD

**Issue by twilwa** [KillianLucas/open-interpreter#946]
### Describe the bug

When starting interpreter --os from the command line, the command fails and the following error occurs:

(.venv) anon@Frankenbako:~/active-tools-stack/interpreter$ interpreter --os
Traceback (most recent call last):
  File "/home/anon/active-tools-stack/interpreter/.venv/bin/interpreter", line 8, in <module>
    sys.exit(interpreter.start_terminal_interface())
  File "/home/anon/active-tools-stack/interpreter/.venv/lib/python3.10/site-packages/interpreter/core/core.py", line 25, in start_terminal_interface
    start_terminal_interface(self)
  File "/home/anon/active-tools-stack/interpreter/.venv/lib/python3.10/site-packages/interpreter/terminal_interface/start_terminal_interface.py", line 463, in start_terminal_interface
    __import__(package)
  File "/home/anon/active-tools-stack/interpreter/.venv/lib/python3.10/site-packages/pywinctl/__init__.py", line 27, in <module>
    from ._main import (Re, Window, checkPermissions, getActiveWindow,
  File "/home/anon/active-tools-stack/interpreter/.venv/lib/python3.10/site-packages/pywinctl/_main.py", line 14, in <module>
    from pymonctl import findMonitorsAtPoint, getAllMonitors, getAllMonitorsDict
  File "/home/anon/active-tools-stack/interpreter/.venv/lib/python3.10/site-packages/pymonctl/__init__.py", line 22, in <module>
    from ._main import (getAllMonitors, getAllMonitorsDict, getMonitorsCount, getPrimary,
  File "/home/anon/active-tools-stack/interpreter/.venv/lib/python3.10/site-packages/pymonctl/_main.py", line 916, in <module>
    from ._pymonctl_linux import (_getAllMonitors, _getAllMonitorsDict, _getMonitorsCount, _getPrimary,
  File "/home/anon/active-tools-stack/interpreter/.venv/lib/python3.10/site-packages/pymonctl/_pymonctl_linux.py", line 22, in <module>
    from ewmhlib import defaultEwmhRoot, getProperty, getPropertyValue, getRoots, getRootsInfo, Props
  File "/home/anon/active-tools-stack/interpreter/.venv/lib/python3.10/site-packages/ewmhlib/__init__.py", line 23, in <module>
    from ._main import (displaysCount, getDisplays, getDisplaysInfo, getRoots, getRootsInfo,
  File "/home/anon/active-tools-stack/interpreter/.venv/lib/python3.10/site-packages/ewmhlib/_main.py", line 4, in <module>
    from ._ewmhlib import (displaysCount, getDisplays, getDisplaysInfo, getRoots, getRootsInfo,
  File "/home/anon/active-tools-stack/interpreter/.venv/lib/python3.10/site-packages/ewmhlib/_ewmhlib.py", line 60, in <module>
    displaysCount: int = len(getDisplays())
  File "/home/anon/active-tools-stack/interpreter/.venv/lib/python3.10/site-packages/ewmhlib/_ewmhlib.py", line 45, in getDisplays
    if not _displays and os.environ['XDG_SESSION_TYPE'].lower() != "wayland":
  File "/usr/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'XDG_SESSION_TYPE'

I'm running the application in a WSL2 environment on Windows Home 11 with Ubuntu 22.04 for the WSL env. I've installed interpreter via pip into a .venv folder in the 'interpreter' directory i created to house interpreter's workspace. .venv is currently activated.

### Reproduce

wsl.exe
cd ~/interpreter
source .venv/bin/activate
interpreter --os

### Expected behavior

Intepreter starts up successfully.

### Screenshots

![image](https://github.com/KillianLucas/open-interpreter/assets/111034762/b241fd01-907b-472a-801e-46ff8fadb0f5)

### Open Interpreter version

0.2.0

### Python version

3.10.12

### Operating System name and version

Windows 11 Home -- WSL2 env

**Comment by ar4wnnn** [comment]
I fixed that with:

`export XDG_SESSION_TYPE=x11`

can add that to .bashrc

**Comment by Notnaton** [comment]
`--os` mode doesn't work on wayland, due to pyautogui (clicks and keys) not supporting wayland.
as @ar4wnnn said `export XDG_SESSION_TYPE=x11` seems to be the way for now

**Comment by interpreterwork** [comment]
Thank you for reporting this and for helping build the classic Python version of Open Interpreter. This issue concerns the earlier Python/LiteLLM/Jupyter product; this repository now tracks the Rust Open Interpreter built on Codex. We are closing the legacy report here so current product tracking starts clean. If you still want to pursue it, the community-maintained classic fork is https://github.com/endolith/open-interpreter. If the same problem affects the current Interpreter release, please open a new issue with the current template and include the version, provider, model, wire API, harness, platform, and reproduction.
