### ISSUE TITLE
Open-Interpreter not Starting

### ISSUE THREAD

**Issue by mayowaosibodu** [KillianLucas/open-interpreter#957]
### Describe the bug

When I run the `interpreter` command, I get:

`Traceback (most recent call last):
  File "/usr/local/bin/interpreter", line 5, in <module>
    from interpreter import interpreter
  File "/usr/local/lib/python3.10/site-packages/interpreter/__init__.py", line 1, in <module>
    from .core.core import OpenInterpreter
  File "/usr/local/lib/python3.10/site-packages/interpreter/core/core.py", line 10, in <module>
    from ..terminal_interface.start_terminal_interface import start_terminal_interface
  File "/usr/local/lib/python3.10/site-packages/interpreter/terminal_interface/start_terminal_interface.py", line 16, in <module>
    from .validate_llm_settings import validate_llm_settings
  File "/usr/local/lib/python3.10/site-packages/interpreter/terminal_interface/validate_llm_settings.py", line 5, in <module>
    import litellm
  File "/usr/local/lib/python3.10/site-packages/litellm/__init__.py", line 472, in <module>
    from .timeout import timeout
  File "/usr/local/lib/python3.10/site-packages/litellm/timeout.py", line 20, in <module>
    from litellm.exceptions import Timeout
  File "/usr/local/lib/python3.10/site-packages/litellm/exceptions.py", line 12, in <module>
    from openai import (
ImportError: cannot import name 'AuthenticationError' from 'openai' (/usr/local/lib/python3.10/site-packages/openai/__init__.py)
`

### Reproduce

Running `interpreter`

### Expected behavior

Interpreter startup

### Open Interpreter version

0.2.0

### Python version

3.10.8

### Operating System name and version

MacOS 12

### Additional context

There's a closed issue about this error here: https://github.com/KillianLucas/open-interpreter/issues/859#issue-2062077441

The bug should've been completely fixed in `0.2.0`, but I'm still experiencing it.
I commented in the thread but didn't have access to reopen the issue, so I decided to open this.

I'm experiencing this with `open-interpreter=0.2.0` and `openai==1.9.0` on MacOS. I tried downgrading each library to see if that would change anything, but it didn't.

**Comment by Notnaton** [comment]
Try installing this version of OpenAI:
`pip install openai==1.7.2`

If that doesn't work, do this:
`pip install --force-reinstall open-interpreter`

**Comment by mayowaosibodu** [comment]
> Try installing this version of OpenAI: `pip install openai==1.7.2`
> 
> If that doesn't work, do this: `pip install --force-reinstall open-interpreter`

I tried these, but they didn't resolve the issue.

A fresh install on Python 3.11 was how I was able to get things working.
