### ISSUE TITLE
Open Interpreter installed a python package and now it stopped working

### ISSUE THREAD

**Issue by FalconTheBerd** [KillianLucas/open-interpreter#958]
### Describe the bug

Can't find module openai._models

### Reproduce

I asked it to summarise the latest BBC news article, it pip installed something to do that and it stopped working.

### Expected behavior

I expected it to summarise the article. Then continue working. Instead it didn't summarise it, then stopped working.

### Screenshots

Traceback (most recent call last):
  File "c:\Users\user\OneDrive\Desktop\Python\Interpreter\scripts.py", line 1, in <module>
    from interpreter import interpreter
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\interpreter\__init__.py", line 1, in <module>
    from .core.core import OpenInterpreter
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\interpreter\core\core.py", line 11, in <module>
    from ..terminal_interface.start_terminal_interface import start_terminal_interface
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\interpreter\terminal_interface\start_terminal_interface.py", line 16, in <module>
    from .validate_llm_settings import validate_llm_settings
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\interpreter\terminal_interface\validate_llm_settings.py", line 5, in <module>
    import litellm
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\litellm\__init__.py", line 4, in <module>
    from litellm.caching import Cache
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\litellm\caching.py", line 14, in <module>
    from openai._models import BaseModel as OpenAIObject
ModuleNotFoundError: No module named 'openai._models'

### Open Interpreter version

0.2.0

### Python version

3.11.7

### Operating System name and version

Windows 11

### Additional context

It did mention something about a dependency error when pip installing whatever it did. I forgot what it installed, but it failed to install due to a dependency. It was OpenAI that was preventing the thing to get downloaded.

**Comment by FalconTheBerd** [comment]
i found the thing it installed, uninstalled it and it still doesn't work

**Comment by FalconTheBerd** [comment]
now none of my openAI things work. my python script that used the API doesn't work

**Comment by ghnnshymm** [comment]
try installing it in virtual environment

**Comment by Notnaton** [comment]
Can you run:
```
pip show openai
pip show litellm
```

**Comment by FalconTheBerd** [comment]
i had to re install openai and open interpreter. it got fixed after that
