### ISSUE TITLE
Trying to fix the conversation restoration problem in version 0.2.0 New Computer

### ISSUE THREAD

**Issue by Steve235lab** [KillianLucas/open-interpreter#962]
### Describe the bug

It can list but cannot restore conversation in the version of 0.2.0 (actually some latest 0.1.x versions also have this problem).

I think this is a known problem because the line "This feature is not working as of 0.2.0 (The New Computer Update). Please consider submitting a PR to repair it with the new streaming format." is hard-coded in the repo.

I'm trying to fix this.

### Reproduce

1. With command

   ```shell
   interpreter --conversations
   ```

   It will list the conversation history along with this

   ```text
   This feature is not working as of 0.2.0 (The New Computer Update). Please consider submitting a PR to repair it with the new streaming format.
   ```

2. Pick one conversation you want to restore, an error occurs:

   ```text
   Traceback (most recent call last):
     File "/usr/local/bin/interpreter", line 8, in <module>
       sys.exit(interpreter.start_terminal_interface())
     File "/usr/local/lib/python3.10/dist-packages/interpreter/core/core.py", line 25, in start_terminal_interface
       start_terminal_interface(self)
     File "/usr/local/lib/python3.10/dist-packages/interpreter/terminal_interface/start_terminal_interface.py", line 677, in start_terminal_interface
       conversation_navigator(interpreter)
     File "/usr/local/lib/python3.10/dist-packages/interpreter/terminal_interface/conversation_navigator.py", line 82, in conversation_navigator
       render_past_conversation(messages)
     File "/usr/local/lib/python3.10/dist-packages/interpreter/terminal_interface/render_past_conversation.py", line 25, in render_past_conversation
       print(">", chunk["message"])
   KeyError: 'message'
   ```

 

### Expected behavior

Restore a conversation.

### Open Interpreter version

0.2.0

### Python version

Python 3.10.12

### Operating System name and version

Ubuntu 22.04.3 LTS

### Additional context

I'm going to fix this in the next few days, so if anybody know anything about this problem (for example, what new feature breaks it) please post here which would be very helpful!

**Comment by tyfiero** [comment]
If you run into any issues with this let me know, I might be able to help

**Comment by Steve235lab** [comment]
@https://github.com/yuhanj2 has also helped with this offline.
