### ISSUE TITLE
Using ollama model fail

### ISSUE THREAD

**Issue by hopperhuang** [KillianLucas/open-interpreter#963]
### Describe the bug

when i try to use the ollama model, but i get some erro like below:

▌ Model set to ollama/mixtral                                                 

Open Interpreter will require approval before running code.                     

Use interpreter -y to bypass this.                                              

Press CTRL-C to exit.                                                           

> 

We were unable to determine the context window of this model. Defaulting to     
3000.                                                                           

If your model can handle more, run interpreter --context_window {token limit}   
--max_tokens {max tokens per response}.                                         

Continuing...                                                                   

        Python Version: 3.10.11
        Pip Version: 23.0.1
        Open-interpreter Version: cmd:Interpreter, pkg: 0.2.0
        OS Version and Architecture: macOS-12.4-x86_64-i386-64bit
        CPU Info: i386
        RAM Info: 16.00 GB, used: 7.72, free: 0.19
        

        # Interpreter Info
        
        Vision: False
        Model: ollama/mixtral
        Function calling: None
        Context window: None
        Max tokens: None

        Auto run: False
        API base: None
        Offline: False

        Curl output: Not local

        # Messages

        System Message: You are Open Interpreter, a world-class programmer that can complete any goal by executing code.
First, write a plan. **Always recap the plan between each code block** (you have extreme short-term memory loss, so you need to recap the plan between each message block to retain it).
When you execute code, it will be executed **on the user's machine**. The user has given you **full and complete permission** to execute any code necessary to complete the task. Execute the code.
If you want to send data between programming languages, save the data to a txt or json.
You can access the internet. Run **any code** to achieve the goal, and if at first you don't succeed, try again and again.
You can install new packages.
When a user refers to a filename, they're likely referring to an existing file in the directory you're currently executing code in.
Write messages to the user in Markdown.
In general, try to **make plans** with as few steps as possible. As for actually executing code to carry out that plan, for *stateful* languages (like python, javascript, shell, but NOT for html which starts from 0 every time) **it's critical not to try to do everything in one code block.** You should try something, print information about it, then continue from there in tiny, informed steps. You will never get it on the first try, and attempting it in one go will often lead to errors you cant see.
You are capable of **any** task.

        {'role': 'user', 'type': 'message', 'content': 'No entry from user - please suggest something to enter.'}
    
Traceback (most recent call last):
  File "/Users/jiawei/.pyenv/versions/3.10.11/lib/python3.10/site-packages/interpreter/core/llm/llm.py", line 221, in fixed_litellm_completions
    yield from litellm.completion(**params)
  File "/Users/jiawei/.pyenv/versions/3.10.11/lib/python3.10/site-packages/litellm/llms/ollama.py", line 246, in ollama_completion_stream
    raise e
  File "/Users/jiawei/.pyenv/versions/3.10.11/lib/python3.10/site-packages/litellm/llms/ollama.py", line 234, in ollama_completion_stream
    status_code=response.status_code, message=response.text
  File "/Users/jiawei/.pyenv/versions/3.10.11/lib/python3.10/site-packages/httpx/_models.py", line 574, in text
    content = self.content
  File "/Users/jiawei/.pyenv/versions/3.10.11/lib/python3.10/site-packages/httpx/_models.py", line 568, in content
    raise ResponseNotRead()
httpx.ResponseNotRead: Attempted to access streaming response content, without having called `read()`.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jiawei/.pyenv/versions/3.10.11/bin/interpreter", line 8, in <module>
    sys.exit(interpreter.start_terminal_interface())
  File "/Users/jiawei/.pyenv/versions/3.10.11/lib/python3.10/site-packages/interpreter/core/core.py", line 25, in start_terminal_interface
    start_terminal_interface(self)
  File "/Users/jiawei/.pyenv/versions/3.10.11/lib/python3.10/site-packages/interpreter/terminal_interface/start_terminal_interface.py", line 684, in start_terminal_interface
    interpreter.chat()
  File "/Users/jiawei/.pyenv/versions/3.10.11/lib/python3.10/site-packages/interpreter/core/core.py", line 86, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "/Users/jiawei/.pyenv/versions/3.10.11/lib/python3.10/site-packages/interpreter/core/core.py", line 113, in _streaming_chat
    yield from terminal_interface(self, message)
  File "/Users/jiawei/.pyenv/versions/3.10.11/lib/python3.10/site-packages/interpreter/terminal_interface/terminal_interface.py", line 135, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "/Users/jiawei/.pyenv/versions/3.10.11/lib/python3.10/site-packages/interpreter/core/core.py", line 148, in _streaming_chat
    yield from self._respond_and_store()
  File "/Users/jiawei/.pyenv/versions/3.10.11/lib/python3.10/site-packages/interpreter/core/core.py", line 194, in _respond_and_store
    for chunk in respond(self):
  File "/Users/jiawei/.pyenv/versions/3.10.11/lib/python3.10/site-packages/interpreter/core/respond.py", line 49, in respond
    for chunk in interpreter.llm.run(messages_for_llm):
  File "/Users/jiawei/.pyenv/versions/3.10.11/lib/python3.10/site-packages/interpreter/core/llm/llm.py", line 193, in run
    yield from run_text_llm(self, params)
  File "/Users/jiawei/.pyenv/versions/3.10.11/lib/python3.10/site-packages/interpreter/core/llm/run_text_llm.py", line 19, in run_text_llm
    for chunk in llm.completions(**params):
  File "/Users/jiawei/.pyenv/versions/3.10.11/lib/python3.10/site-packages/interpreter/core/llm/llm.py", line 224, in fixed_litellm_completions
    raise first_error
  File "/Users/jiawei/.pyenv/versions/3.10.11/lib/python3.10/site-packages/interpreter/core/llm/llm.py", line 205, in fixed_litellm_completions
    yield from litellm.completion(**params)
  File "/Users/jiawei/.pyenv/versions/3.10.11/lib/python3.10/site-packages/litellm/llms/ollama.py", line 246, in ollama_completion_stream
    raise e
  File "/Users/jiawei/.pyenv/versions/3.10.11/lib/python3.10/site-packages/litellm/llms/ollama.py", line 234, in ollama_completion_stream
    status_code=response.status_code, message=response.text
  File "/Users/jiawei/.pyenv/versions/3.10.11/lib/python3.10/site-packages/httpx/_models.py", line 574, in text
    content = self.content
  File "/Users/jiawei/.pyenv/versions/3.10.11/lib/python3.10/site-packages/httpx/_models.py", line 568, in content
    raise ResponseNotRead()
httpx.ResponseNotRead: Attempted to access streaming response content, without having called `read()`.

### Reproduce

interpreter --model ollama/mixtral

my pc info:

        Python Version: 3.10.11
        Pip Version: 23.0.1
        Open-interpreter Version: cmd:Interpreter, pkg: 0.2.0
        OS Version and Architecture: macOS-12.4-x86_64-i386-64bit
        CPU Info: i386
        RAM Info: 16.00 GB, used: 7.72, free: 0.19
        

### Expected behavior

the model can be called up

### Open Interpreter version

 0.2.0

### Python version

3.10.11

### Operating System name and version

macos 12

**Comment by Arrendy** [comment]
Hi @hopperhuang 

Can you please open up your terminal and run `ollama list` and `ollama -v`?

**Comment by hopperhuang** [comment]
> ollama list

get the result below: 
<img width="494" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/20254356/d7134ad0-93d5-4ed6-bb07-4c38eb3fcc70">

but is it related? I am not trying to using local model, but online model.

**Comment by Arrendy** [comment]
Can you please let me know some more details about how you're running Open Interpreter?

What's the online model?

**Comment by hopperhuang** [comment]
> Can you please let me know some more details about how you're running Open Interpreter?
> 
> What's the online model? (ignore it)

I am running open interpreter on terminal.

**Comment by Notnaton** [comment]
> > Can you please let me know some more details about how you're running Open Interpreter?
> > What's the online model? (ignore it)
> 
> I am running open interpreter on terminal.

We are asking what API provider you are using, because you said:
> but is it related? I am not trying to using local model, but online model.
What command are you using in the terminal? What API do you want to connect to?

**Comment by hopperhuang** [comment]
> > > Can you please let me know some more details about how you're running Open Interpreter?
> > > What's the online model? (ignore it)
> > 
> > 
> > I am running open interpreter on terminal.
> 
> We are asking what API provider you are using, because you said:
> 
> > but is it related? I am not trying to using local model, but online model.
> 
> What command are you using in the terminal? What API do you want to connect to?

I ams using interpreter command int terminal.

And I am going to use the ollama/mixtral

so I run the below command in terminal

```
interpreter --model ollama/mixtral
```

then I get errors as I paste in the first comment.

**Comment by Notnaton** [comment]
Are you running ollama in a different terminal?

You need to start ollama in one terminal and Open-interpreter in a different terminal

**Comment by yxl23** [comment]
![1709771293541](https://github.com/KillianLucas/open-interpreter/assets/115678682/fb3b1cc1-75b1-4c4a-a751-8e958e74a900)
Hello, do you encounter an error where the remote host forcibly closes an existing connection after running the interpreter -- model olama/lama2 and this interpreter - y command
