### ISSUE TITLE
Can't use interpreter --model gpt-4-0125-preview

### ISSUE THREAD

**Issue by markxbaker** [KillianLucas/open-interpreter#971]
### Describe the bug

We were unable to determine the context window of this model. Defaulting to 3000.

### Reproduce

(Openint) C:\Open Interpreter>interpreter --model gpt-4-0125-preview

▌ Model set to gpt-4-0125-preview

Open Interpreter will require approval before running code.

Use interpreter -y to bypass this.

Press CTRL-C to exit.

> interpreter

We were unable to determine the context window of this model. Defaulting to 3000.

If your model can handle more, run interpreter --context_window {token limit} --max_tokens {max tokens per response}.

Continuing...

        Python Version: 3.11.7
        Pip Version: 23.2.1
        Open-interpreter Version: cmd:Interpreter, pkg: 0.2.0
        OS Version and Architecture: Windows-10-10.0.19045-SP0
        CPU Info: Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
        RAM Info: 7.85 GB, used: 4.62, free: 3.23

        # Interpreter Info

        Vision: False
        Model: gpt-4-0125-preview
        Function calling: None
        Context window: None
        Max tokens: None

        Auto run: False
        API base: None
        Offline: False

        Curl output: Not local

        # Messages

        System Message: You are Open Interpreter, a world-class programmer that can complete any goal by executing code.
First, write a plan. **Always recap the plan between each code block** (you have extreme short-term memory loss, so you need to recap the plan between each message block to retain it).
When you execute code, it will be executed **on the user's machine**. The user has given you **full and complete permission** to execute any code necessary to complete the task. Execute the code.
If you want to send data between programming languages, save the data to a txt or json.
You can access the internet. Run **any code** to achieve the goal, and if at first you don't succeed, try again and again.
You can install new packages.
When a user refers to a filename, they're likely referring to an existing file in the directory you're currently executing code in.
Write messages to the user in Markdown.
In general, try to **make plans** with as few steps as possible. As for actually executing code to carry out that plan, for *stateful* languages (like python, javascript, shell, but NOT for html which starts from 0 every time) **it's critical not to try to do everything in one code block.** You should try something, print information about it, then continue from there in tiny, informed steps. You will never get it on the first try, and attempting it in one go will often lead to errors you cant see.
You are capable of **any** task.

        {'role': 'user', 'type': 'message', 'content': 'interpreter'}

Traceback (most recent call last):
  File "C:\Open Interpreter\Openint\Lib\site-packages\litellm\main.py", line 572, in completion
    model, custom_llm_provider, dynamic_api_key, api_base = get_llm_provider(
                                                            ^^^^^^^^^^^^^^^^^
  File "C:\Open Interpreter\Openint\Lib\site-packages\litellm\utils.py", line 4184, in get_llm_provider
    raise e
  File "C:\Open Interpreter\Openint\Lib\site-packages\litellm\utils.py", line 4171, in get_llm_provider
    raise litellm.exceptions.BadRequestError(  # type: ignore
litellm.exceptions.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=gpt-4-0125-preview
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Open Interpreter\Openint\Lib\site-packages\interpreter\core\llm\llm.py", line 221, in fixed_litellm_completions
    yield from litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Open Interpreter\Openint\Lib\site-packages\litellm\utils.py", line 2171, in wrapper
    raise e
  File "C:\Open Interpreter\Openint\Lib\site-packages\litellm\utils.py", line 2078, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Open Interpreter\Openint\Lib\site-packages\litellm\main.py", line 1806, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Open Interpreter\Openint\Lib\site-packages\litellm\utils.py", line 6689, in exception_type
    raise e
  File "C:\Open Interpreter\Openint\Lib\site-packages\litellm\utils.py", line 6657, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=gpt-4-0125-preview
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Open Interpreter\Openint\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Open Interpreter\Openint\Lib\site-packages\interpreter\core\core.py", line 25, in start_terminal_interface
    start_terminal_interface(self)
  File "C:\Open Interpreter\Openint\Lib\site-packages\interpreter\terminal_interface\start_terminal_interface.py", line 684, in start_terminal_interface
    interpreter.chat()
  File "C:\Open Interpreter\Openint\Lib\site-packages\interpreter\core\core.py", line 86, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "C:\Open Interpreter\Openint\Lib\site-packages\interpreter\core\core.py", line 113, in _streaming_chat
    yield from terminal_interface(self, message)
  File "C:\Open Interpreter\Openint\Lib\site-packages\interpreter\terminal_interface\terminal_interface.py", line 135, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "C:\Open Interpreter\Openint\Lib\site-packages\interpreter\core\core.py", line 148, in _streaming_chat
    yield from self._respond_and_store()
  File "C:\Open Interpreter\Openint\Lib\site-packages\interpreter\core\core.py", line 194, in _respond_and_store
    for chunk in respond(self):
  File "C:\Open Interpreter\Openint\Lib\site-packages\interpreter\core\respond.py", line 49, in respond
    for chunk in interpreter.llm.run(messages_for_llm):
  File "C:\Open Interpreter\Openint\Lib\site-packages\interpreter\core\llm\llm.py", line 193, in run
    yield from run_text_llm(self, params)
  File "C:\Open Interpreter\Openint\Lib\site-packages\interpreter\core\llm\run_text_llm.py", line 19, in run_text_llm
    for chunk in llm.completions(**params):
  File "C:\Open Interpreter\Openint\Lib\site-packages\interpreter\core\llm\llm.py", line 224, in fixed_litellm_completions
    raise first_error
  File "C:\Open Interpreter\Openint\Lib\site-packages\interpreter\core\llm\llm.py", line 205, in fixed_litellm_completions
    yield from litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Open Interpreter\Openint\Lib\site-packages\litellm\utils.py", line 2171, in wrapper
    raise e
  File "C:\Open Interpreter\Openint\Lib\site-packages\litellm\utils.py", line 2078, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Open Interpreter\Openint\Lib\site-packages\litellm\main.py", line 1806, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Open Interpreter\Openint\Lib\site-packages\litellm\utils.py", line 6689, in exception_type
    raise e
  File "C:\Open Interpreter\Openint\Lib\site-packages\litellm\utils.py", line 6657, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=gpt-4-0125-preview
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers

(Openint) C:\Open Interpreter>interpreter --context_window {128000} --max_tokens {4096}.
usage: interpreter [-h] [-ci CUSTOM_INSTRUCTIONS] [-s SYSTEM_MESSAGE] [-y] [-v] [-m MODEL] [-t TEMPERATURE] [-lsv]
                   [-lsf] [-c CONTEXT_WINDOW] [-x MAX_TOKENS] [-b MAX_BUDGET] [-ab API_BASE] [-ak API_KEY]
                   [-av API_VERSION] [-xo MAX_OUTPUT] [-fc] [-dt] [-o] [-sm] [-safe {off,ask,auto}] [-cf CONFIG_FILE]
                   [-f] [-l] [-vi] [-os] [--config] [--reset_config] [--conversations] [--version]
interpreter: error: argument -c/--context_window: invalid int value: '{128000}'

(Openint) C:\Open Interpreter>

### Expected behavior

Run interpreter as normal cat responses

### Open Interpreter version

0.2.0

### Python version

3.11.7

### Operating System name and version

Windows-10-10.0.19045-SP0

**Comment by Arrendy** [comment]
Hi @markxbaker 

Open Interpreter leverages LiteLLM who does not yet support `gpt-4-0125-preview`. LiteLLM will be supporting this model as of next week. 

https://github.com/BerriAI/litellm/issues/1622#issuecomment-1911123999

**Comment by markxbaker** [comment]
Thanks, will check back.

**Comment by markxbaker** [comment]
Thanks, will check back.

**Comment by ishaan-jaff** [comment]
Hi I'm the litellm maintainer, do you already have access to `gpt-4-0125-preview.` ? Afaik OpenAI has not made this available as yet
