### ISSUE TITLE
NameError: name 'computer' is not defined

### ISSUE THREAD

**Issue by AntDX316** [KillianLucas/open-interpreter#973]
### Describe the bug

I keeps saying NameError: name 'computer' is not defined a lot

### Reproduce

ask it to do windows tasks

### Expected behavior

no error and it should work

### Open Interpreter version

latest

### Python version

latest

### Operating System name and version

latest

**Comment by Steve235lab** [comment]
May you paste the trace back, so we can find which line in the code caused the problem.

**Comment by AntDX316** [comment]
what is a trace back?

**Comment by Steve235lab** [comment]
> what is a trace back?

The detailed error messages, like this:
```
Traceback (most recent call last):
  File "/usr/local/bin/interpreter", line 8, in <module>
    sys.exit(interpreter.start_terminal_interface())
  File "/usr/local/lib/python3.10/dist-packages/interpreter/core/core.py", line 25, in start_terminal_interface
    start_terminal_interface(self)
  File "/usr/local/lib/python3.10/dist-packages/interpreter/terminal_interface/start_terminal_interface.py", line 677, in start_terminal_interface
    conversation_navigator(interpreter)
  File "/usr/local/lib/python3.10/dist-packages/interpreter/terminal_interface/conversation_navigator.py", line 82, in conversation_navigator
    render_past_conversation(messages)
  File "/usr/local/lib/python3.10/dist-packages/interpreter/terminal_interface/render_past_conversation.py", line 25, in render_past_conversation
    print(">", chunk["message"])
KeyError: 'message'
```

**Comment by AntDX316** [comment]
it seems to be fixed somehow
